version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    labels:
      - dependencies
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: actions
