export type LegacySourceKind='income-bot'|'system';
export interface LegacyCapabilitySource { id:string; kind:LegacySourceKind; name:string; path:string; range?:string; featureCount?:number; status:'registered'|'implemented'|'blocked'; }
export interface LegacyRegistry { version:string; sourceOfTruth:string; incomeBotCount:number; incomeCategoryCount:number; systemCount:number; declaredSystemFeatureCount:number; sources:LegacyCapabilitySource[]; }
const systems:[string,string,string][]=[
['master-bot-system','Master Bot System','original-bots/systems/master-bot-system.md'],['saas-automation','SaaS Automation & Monetization Bot','original-bots/systems/saas-automation-bot.md'],['api-automation','API Automation & Integration Bot','original-bots/systems/api-automation-bot.md'],['crypto-mining','Crypto Mining, Blockchain & Wallet Bot','original-bots/systems/crypto-mining-bot.md'],['import-export','Import/Export, Travel & Global Business Bot','original-bots/systems/import-export-bot.md'],['drop-shipping','Drop Shipping, Affiliate Marketing & E-commerce Bot','original-bots/systems/drop-shipping-bot.md'],['schools-coaching','Schools, Masterclasses, Seminars & Coaching Bot','original-bots/systems/schools-coaching-bot.md'],['penny-stock-trading','Penny Stock, Trading & Investment Bot','original-bots/systems/penny-stock-trading-bot.md'],['ai-leaps-robot','AI Leaps, Robot Builders & Full Automation Bot','original-bots/systems/ai-leaps-robot-bot.md'],['contracts-legal','Contracts, Legal Documents & Digital Products Bot','original-bots/systems/contracts-legal-bot.md'],['youtube-streaming','YouTube, Streaming & Content Creation Bot','original-bots/systems/youtube-streaming-bot.md'],['consulting-agency','Autonomous Consulting & Digital Agency Bot','original-bots/systems/consulting-agency-bot.md']];
const categories=[['category-1','Digital & SaaS Automation','original-bots/autonomous-income-network/category-1-digital-saas.md','1–25'],['category-2','Finance, Trading & Investments','original-bots/autonomous-income-network/category-2-finance-trading.md','26–50'],['category-3','E-commerce & Retail','original-bots/autonomous-income-network/category-3-ecommerce-retail.md','51–75'],['category-4','Media, Content & Publishing','original-bots/autonomous-income-network/category-4-media-content.md','76–100'],['category-5','AI, Robotics & Automation','original-bots/autonomous-income-network/category-5-ai-robotics.md','101–125'],['category-6','Franchising, Licensing & Royalties','original-bots/autonomous-income-network/category-6-franchising-licensing.md','126–150'],['category-7','E-commerce & Retail Automation','original-bots/autonomous-income-network/category-7-ecommerce-automation.md','151–175'],['category-8','Services, Real Estate & Global Expansion','original-bots/autonomous-income-network/category-8-services-global.md','176–200']];
export function buildLegacyRegistry():LegacyRegistry { return {version:'1.0.0',sourceOfTruth:'original-bots/README.md',incomeBotCount:200,incomeCategoryCount:8,systemCount:12,declaredSystemFeatureCount:2400,sources:[...categories.map(([id,name,path,range])=>({id,kind:'income-bot' as const,name,path,range,status:'registered' as const})),...systems.map(([id,name,path])=>({id,kind:'system' as const,name,path,featureCount:200,status:'registered' as const}))]}; }
export function legacyCapabilityTotals(r=buildLegacyRegistry()){return {incomeBots:r.incomeBotCount,systems:r.systemCount,declaredSystemFeatures:r.declaredSystemFeatureCount,registeredSources:r.sources.length};}
export function assertLegacyRegistryComplete(r=buildLegacyRegistry()):void { if(r.incomeBotCount!==200||r.incomeCategoryCount!==8||r.systemCount!==12) throw new Error('Legacy inventory does not match original-bots manifest'); if(r.sources.length!==20) throw new Error('Legacy source registry is incomplete'); }
