export const FORMULA_CATEGORIES = [
    "Real Estate",
    "Car Flipping",
    "Sales",
    "Capital Deployment",
    "Risk Management",
    "Revenue Intelligence",
];
export const FORMULA_LIBRARY = [
    // ===== SECTION 1: REAL ESTATE (1-40) =====
    {
        name: "Core Flip Spread",
        category: "Real Estate",
        description: "Determines if a property is a strong flip candidate by calculating the spread between ARV and total costs",
        formula: "Deal Score = (ARV * 0.70) - (Purchase Price + Repairs)",
        variables: ["ARV", "Purchase Price", "Repairs"],
        target: "Deal Score > $25,000 = Strong Flip Candidate",
        tags: ["flip", "spread", "acquisition"],
    },
    {
        name: "Rental Cashflow",
        category: "Real Estate",
        description: "Calculates cash-on-cash return for rental properties to ensure minimum profitability",
        formula: "Cash-on-Cash Return = (Annual Net Income / Total Cash Invested) * 100",
        variables: ["Monthly Rent", "Monthly Expenses", "Total Cash Invested"],
        target: "Minimum 8-12% Cash-on-Cash Return",
        tags: ["rental", "cashflow", "hold"],
    },
    {
        name: "Equity Capture",
        category: "Real Estate",
        description: "Measures instant equity gained at purchase to ensure built-in profit margin",
        formula: "Instant Equity % = (ARV - Purchase Price) / ARV * 100",
        variables: ["ARV", "Purchase Price"],
        target: "15%+ minimum instant equity",
        tags: ["equity", "acquisition", "leverage"],
    },
    {
        name: "Motivation Score",
        category: "Real Estate",
        description: "Scores seller motivation level to determine negotiation leverage",
        formula: "Score = (Days on Market * 0.2) + (Price Drops * 5) + (Vacant Flag * 10)",
        variables: ["Days on Market", "Price Drops", "Vacant Flag"],
        target: "Higher score = higher negotiation leverage",
        tags: ["negotiation", "seller", "acquisition"],
    },
    {
        name: "BRRRR Recycle",
        category: "Real Estate",
        description: "Validates if a BRRRR deal returns all invested capital through refinance",
        formula: "Refi Amount >= Total Investment (Purchase + Repairs + Holding Costs)",
        variables: ["ARV", "LTV Ratio", "Purchase Price", "Repairs", "Holding Costs"],
        target: "Refi Amount >= Total Investment",
        tags: ["brrrr", "refinance", "recycle"],
    },
    {
        name: "Maximum Allowable Offer",
        category: "Real Estate",
        description: "Calculates the maximum price to offer on a flip deal using the 70% rule",
        formula: "MAO = (ARV * 0.70) - Repair Costs",
        variables: ["ARV", "Repair Costs"],
        target: "Never exceed MAO for profitable flips",
        tags: ["flip", "offer", "acquisition"],
    },
    {
        name: "Rental Yield",
        category: "Real Estate",
        description: "Calculates annual rental yield as a percentage of property value",
        formula: "Yield = (Annual Rent / Property Value) * 100",
        variables: ["Monthly Rent", "Property Value"],
        target: "5%+ gross yield for rental properties",
        tags: ["rental", "yield", "analysis"],
    },
    {
        name: "Debt Service Coverage",
        category: "Real Estate",
        description: "Measures ability to cover debt payments from rental income",
        formula: "DSCR = Net Operating Income / Annual Debt Service",
        variables: ["Net Operating Income", "Annual Debt Service"],
        target: "DSCR >= 1.25 for safe leverage",
        tags: ["leverage", "debt", "risk"],
    },
    {
        name: "Wholesale Assignment Fee",
        category: "Real Estate",
        description: "Calculates the assignment fee potential in a wholesale deal",
        formula: "Fee = End Buyer Price - Contract Price",
        variables: ["End Buyer Price", "Contract Price"],
        target: "Minimum $5,000 assignment fee",
        tags: ["wholesale", "assignment", "quick-profit"],
    },
    {
        name: "Section 8 Premium",
        category: "Real Estate",
        description: "Compares Section 8 voucher rates vs market rent for premium analysis",
        formula: "Premium = (Section 8 Rate - Market Rent) / Market Rent * 100",
        variables: ["Section 8 Rate", "Market Rent"],
        target: "Positive premium indicates above-market returns",
        tags: ["section8", "rental", "government"],
    },
    {
        name: "Market Heat Index",
        category: "Real Estate",
        description: "Measures market competitiveness by comparing sold to active listings for timing decisions",
        formula: "Market Heat Index = Sold Listings / Active Listings",
        variables: ["Sold Listings", "Active Listings"],
        target: "Above 1.0 = seller's market, below 0.5 = buyer's market",
        tags: ["market", "heat", "timing"],
    },
    {
        name: "Rent Growth Rate",
        category: "Real Estate",
        description: "Tracks rental income growth to project future cashflow and property appreciation",
        formula: "Rent Growth Rate = (New Rent - Old Rent) / Old Rent * 100",
        variables: ["New Rent", "Old Rent"],
        target: "3-5% annual growth indicates healthy market",
        tags: ["rent", "growth", "projection"],
    },
    {
        name: "Equity Growth Rate",
        category: "Real Estate",
        description: "Combines appreciation and loan paydown to measure total equity building speed",
        formula: "Equity Growth Rate = Appreciation % + Principal Paydown %",
        variables: ["Appreciation %", "Principal Paydown %"],
        target: "8%+ combined equity growth annually",
        tags: ["equity", "growth", "wealth"],
    },
    {
        name: "Tax Impact",
        category: "Real Estate",
        description: "Calculates taxable rental income after depreciation deductions to optimize tax strategy",
        formula: "Tax Impact = Rental Income - Depreciation",
        variables: ["Rental Income", "Depreciation"],
        target: "Lower taxable amount = better tax efficiency",
        tags: ["tax", "depreciation", "strategy"],
    },
    {
        name: "Airbnb Yield",
        category: "Real Estate",
        description: "Evaluates short-term rental profitability relative to property cost",
        formula: "Airbnb Yield = (Annual STR Revenue / Property Cost) * 100",
        variables: ["Annual STR Revenue", "Property Cost"],
        target: "10%+ yield for viable short-term rental",
        tags: ["airbnb", "str", "yield"],
    },
    {
        name: "Price-to-Rent Ratio",
        category: "Real Estate",
        description: "Determines if a market favors buying or renting for investment decisions",
        formula: "Price-to-Rent Ratio = Median Price / Annual Rent",
        variables: ["Median Price", "Annual Rent"],
        target: "Below 15 = strong buy market, above 20 = rent market",
        tags: ["price", "rent", "market-analysis"],
    },
    {
        name: "Cashflow Margin",
        category: "Real Estate",
        description: "Measures the percentage of gross rent retained as net cashflow",
        formula: "Cashflow Margin = (Cashflow / Gross Rent) * 100",
        variables: ["Cashflow", "Gross Rent"],
        target: "25%+ cashflow margin for strong rentals",
        tags: ["cashflow", "margin", "rental"],
    },
    {
        name: "Rehab Time Cost",
        category: "Real Estate",
        description: "Calculates total holding cost during renovation to factor into deal analysis",
        formula: "Rehab Time Cost = Days * Daily Holding Cost",
        variables: ["Rehab Days", "Daily Holding Cost"],
        target: "Minimize rehab duration to reduce holding costs",
        tags: ["rehab", "holding", "time"],
    },
    {
        name: "Insurance Impact Ratio",
        category: "Real Estate",
        description: "Evaluates insurance cost as a percentage of rental income for expense management",
        formula: "Insurance Impact Ratio = (Annual Insurance / Annual Rent) * 100",
        variables: ["Annual Insurance", "Annual Rent"],
        target: "Below 5% of gross rent for optimal returns",
        tags: ["insurance", "expense", "ratio"],
    },
    {
        name: "Property Liquidity Score",
        category: "Real Estate",
        description: "Assesses how quickly properties sell in a given area using average days on market",
        formula: "Property Liquidity Score = Avg DOM by Zip",
        variables: ["Average Days on Market", "Zip Code"],
        target: "Under 30 DOM = high liquidity market",
        tags: ["liquidity", "dom", "market"],
    },
    {
        name: "Construction Overrun Risk",
        category: "Real Estate",
        description: "Measures the variance between estimated and actual repair costs to quantify risk",
        formula: "Construction Overrun Risk = ((Actual Cost - Estimated Cost) / Estimated Cost) * 100",
        variables: ["Actual Cost", "Estimated Cost"],
        target: "Keep variance under 15% with contingency buffer",
        tags: ["construction", "overrun", "risk"],
    },
    {
        name: "Zoning Arbitrage Spread",
        category: "Real Estate",
        description: "Identifies profit opportunity from rezoning a property to higher-value use",
        formula: "Zoning Arbitrage Spread = Commercial Value - Residential Value",
        variables: ["Commercial Value", "Residential Value"],
        target: "Positive spread indicates rezoning opportunity",
        tags: ["zoning", "arbitrage", "upside"],
    },
    {
        name: "Equity Leverage Ratio",
        category: "Real Estate",
        description: "Measures how much of the property value is financed versus owned outright",
        formula: "Equity Leverage Ratio = Loan Balance / Market Value",
        variables: ["Loan Balance", "Market Value"],
        target: "Below 0.75 for conservative leverage positioning",
        tags: ["equity", "leverage", "loan"],
    },
    {
        name: "Seller Concession Value",
        category: "Real Estate",
        description: "Quantifies the value of closing credits as a percentage of purchase price",
        formula: "Seller Concession Value = (Closing Credits / Purchase Price) * 100",
        variables: ["Closing Credits", "Purchase Price"],
        target: "3-6% concession reduces effective purchase price",
        tags: ["concession", "closing", "negotiation"],
    },
    {
        name: "Offer Acceptance Probability",
        category: "Real Estate",
        description: "Estimates likelihood of an offer being accepted based on motivation and discount",
        formula: "Offer Acceptance Probability = Motivation Score * Discount %",
        variables: ["Motivation Score", "Discount %"],
        target: "Higher score = greater acceptance likelihood",
        tags: ["offer", "probability", "negotiation"],
    },
    {
        name: "Loan-to-Value (LTV)",
        category: "Real Estate",
        description: "Standard lending metric comparing loan amount to appraised property value",
        formula: "LTV = (Loan Amount / Appraised Value) * 100",
        variables: ["Loan Amount", "Appraised Value"],
        target: "Below 80% to avoid PMI requirements",
        tags: ["ltv", "loan", "financing"],
    },
    {
        name: "Portfolio Yield",
        category: "Real Estate",
        description: "Calculates overall return across an entire real estate portfolio",
        formula: "Portfolio Yield = (Total NOI / Portfolio Value) * 100",
        variables: ["Total NOI", "Portfolio Value"],
        target: "6%+ portfolio yield for balanced portfolio",
        tags: ["portfolio", "yield", "performance"],
    },
    {
        name: "Cash Reserve Coverage",
        category: "Real Estate",
        description: "Measures how many months of expenses are covered by cash reserves",
        formula: "Cash Reserve Coverage = Reserves / Monthly Expenses",
        variables: ["Cash Reserves", "Monthly Expenses"],
        target: "6+ months coverage per property minimum",
        tags: ["reserves", "coverage", "safety"],
    },
    {
        name: "Cap Rate Analysis",
        category: "Real Estate",
        description: "Evaluates property investment return independent of financing structure",
        formula: "Cap Rate = (NOI / Property Value) * 100",
        variables: ["NOI", "Property Value"],
        target: "5-10% cap rate depending on market and risk",
        tags: ["cap-rate", "analysis", "valuation"],
    },
    {
        name: "Rehab ROI",
        category: "Real Estate",
        description: "Calculates return on investment for property rehabilitation projects",
        formula: "Rehab ROI = ((Post-Repair Value - Total Cost) / Total Cost) * 100",
        variables: ["Post-Repair Value", "Total Cost"],
        target: "25%+ ROI for profitable rehab projects",
        tags: ["rehab", "roi", "renovation"],
    },
    {
        name: "Gross Rent Multiplier",
        category: "Real Estate",
        description: "Quick screening metric comparing property price to annual rental income",
        formula: "GRM = Property Price / Annual Rent",
        variables: ["Property Price", "Annual Rent"],
        target: "Lower GRM = better rental investment value",
        tags: ["grm", "screening", "rental"],
    },
    {
        name: "Operating Expense Ratio",
        category: "Real Estate",
        description: "Measures operating expenses as a percentage of gross income for efficiency tracking",
        formula: "OER = (Operating Expenses / Gross Income) * 100",
        variables: ["Operating Expenses", "Gross Income"],
        target: "Below 40% for well-managed properties",
        tags: ["expenses", "efficiency", "operations"],
    },
    {
        name: "Break-Even Occupancy",
        category: "Real Estate",
        description: "Determines minimum occupancy rate needed to cover all operating expenses",
        formula: "Break-Even Occupancy = (Operating Expenses / Gross Potential Income) * 100",
        variables: ["Operating Expenses", "Gross Potential Income"],
        target: "Below 75% for adequate vacancy cushion",
        tags: ["occupancy", "break-even", "risk"],
    },
    {
        name: "Vacancy Loss Factor",
        category: "Real Estate",
        description: "Quantifies expected revenue loss due to vacancy periods",
        formula: "Vacancy Loss = Potential Rent * Vacancy Rate",
        variables: ["Potential Rent", "Vacancy Rate"],
        target: "Budget 5-10% vacancy for conservative projections",
        tags: ["vacancy", "loss", "projection"],
    },
    {
        name: "Net Operating Income",
        category: "Real Estate",
        description: "Core profitability metric subtracting all operating expenses from gross income",
        formula: "NOI = Gross Income - Operating Expenses",
        variables: ["Gross Income", "Operating Expenses"],
        target: "Positive and growing NOI year-over-year",
        tags: ["noi", "income", "profitability"],
    },
    {
        name: "Property Tax Impact",
        category: "Real Estate",
        description: "Measures property tax burden relative to property value for cost comparison",
        formula: "Property Tax Impact = (Annual Tax / Property Value) * 100",
        variables: ["Annual Property Tax", "Property Value"],
        target: "Below 2% effective tax rate preferred",
        tags: ["tax", "property", "expense"],
    },
    {
        name: "Appreciation Leverage",
        category: "Real Estate",
        description: "Amplifies appreciation returns through leverage to measure wealth acceleration",
        formula: "Appreciation Leverage = Appreciation % * Leverage Ratio",
        variables: ["Appreciation %", "Leverage Ratio"],
        target: "Higher leverage amplifies appreciation gains",
        tags: ["appreciation", "leverage", "wealth"],
    },
    {
        name: "Refinance Break-Even",
        category: "Real Estate",
        description: "Calculates months needed to recoup refinancing costs through monthly savings",
        formula: "Refinance Break-Even = Closing Costs / Monthly Savings",
        variables: ["Closing Costs", "Monthly Savings"],
        target: "Break-even under 24 months for worthwhile refi",
        tags: ["refinance", "break-even", "savings"],
    },
    {
        name: "1031 Exchange Benefit",
        category: "Real Estate",
        description: "Evaluates tax deferral value relative to exchange transaction costs",
        formula: "1031 Exchange Benefit = Deferred Tax / Exchange Cost",
        variables: ["Deferred Tax Amount", "Exchange Cost"],
        target: "Ratio above 3.0 for beneficial exchange",
        tags: ["1031", "exchange", "tax-deferral"],
    },
    {
        name: "Multi-Family Scale Factor",
        category: "Real Estate",
        description: "Projects total portfolio NOI based on unit count and average per-unit income",
        formula: "Multi-Family Scale Factor = Units * Avg NOI per Unit",
        variables: ["Number of Units", "Avg NOI per Unit"],
        target: "Scale factor grows with portfolio expansion",
        tags: ["multi-family", "scale", "portfolio"],
    },
    // ===== SECTION 2: CAR FLIPPING (41-70) =====
    {
        name: "Car Spread Formula",
        category: "Car Flipping",
        description: "Calculates the profit spread between market value and total costs",
        formula: "Spread = Market Value - (Purchase + Repairs + Fees)",
        variables: ["Market Value", "Purchase Price", "Repair Cost", "Fees"],
        target: "Minimum 15-20% spread for viable deals",
        tags: ["spread", "profit", "acquisition"],
    },
    {
        name: "Demand Velocity Score",
        category: "Car Flipping",
        description: "Measures how quickly a vehicle model sells in a given market",
        formula: "Velocity = Listings Sold Last 30 Days / Active Listings",
        variables: ["Listings Sold (30 days)", "Active Listings"],
        target: "Above 1.0 = high demand vehicle",
        tags: ["demand", "velocity", "market"],
    },
    {
        name: "Repair Risk Multiplier",
        category: "Car Flipping",
        description: "Adjusts profit for repair cost uncertainty with a safety buffer",
        formula: "Adjusted Profit = Spread - (Repair Estimate * 1.3)",
        variables: ["Spread", "Repair Estimate"],
        target: "Must remain positive after 30% buffer",
        tags: ["repair", "risk", "buffer"],
    },
    {
        name: "Time-to-Liquidation",
        category: "Car Flipping",
        description: "Predicts average days to sell based on model and zip code data",
        formula: "TTL = Average Days on Market (Model + Zip Code)",
        variables: ["Vehicle Model", "Zip Code", "Avg Market Days"],
        target: "Target under 21 days for rapid turn",
        tags: ["liquidation", "speed", "turnover"],
    },
    {
        name: "Max Purchase Price",
        category: "Car Flipping",
        description: "Calculates the maximum purchase price for profitable car flips",
        formula: "Max Purchase = (Expected Sale * 0.75) - Repair Costs",
        variables: ["Expected Sale Price", "Repair Costs"],
        target: "Never exceed max purchase for profitability",
        tags: ["acquisition", "max-price", "limit"],
    },
    {
        name: "Capital Turn Rate",
        category: "Car Flipping",
        description: "Measures how many times capital is recycled per year",
        formula: "Turn Rate = 365 / Average Hold Period",
        variables: ["Average Hold Period (days)"],
        target: "12+ turns per year for maximum capital efficiency",
        tags: ["capital", "turnover", "efficiency"],
    },
    {
        name: "Daily Profit Rate",
        category: "Car Flipping",
        description: "Calculates profit per day held to compare deal efficiency",
        formula: "Daily Profit = Net Profit / Days Held",
        variables: ["Net Profit", "Days Held"],
        target: "Higher daily profit = better capital deployment",
        tags: ["profit", "daily", "efficiency"],
    },
    {
        name: "Auction Arbitrage %",
        category: "Car Flipping",
        description: "Measures profit margin between auction purchase price and retail sale value",
        formula: "Auction Arbitrage % = ((Retail Price - Auction Price) / Retail Price) * 100",
        variables: ["Retail Price", "Auction Price"],
        target: "25%+ arbitrage for profitable auction buys",
        tags: ["auction", "arbitrage", "margin"],
    },
    {
        name: "Seasonal Index",
        category: "Car Flipping",
        description: "Identifies seasonal pricing trends to time purchases and sales optimally",
        formula: "Seasonal Index = Avg Seasonal Price / Yearly Avg Price",
        variables: ["Avg Seasonal Price", "Yearly Avg Price"],
        target: "Buy below 1.0 index, sell above 1.0 index",
        tags: ["seasonal", "timing", "pricing"],
    },
    {
        name: "Demand Index",
        category: "Car Flipping",
        description: "Quantifies buyer demand relative to available supply for a vehicle type",
        formula: "Demand Index = Search Volume / Active Listings",
        variables: ["Search Volume", "Active Listings"],
        target: "Above 5.0 = high demand, prioritize acquisition",
        tags: ["demand", "supply", "market"],
    },
    {
        name: "Reconditioning ROI",
        category: "Car Flipping",
        description: "Calculates return on investment for vehicle reconditioning and detailing",
        formula: "Reconditioning ROI = Increased Sale Price - Repair Cost",
        variables: ["Increased Sale Price", "Repair Cost"],
        target: "3:1 return ratio on reconditioning spend",
        tags: ["reconditioning", "roi", "detail"],
    },
    {
        name: "Risk Multiplier",
        category: "Car Flipping",
        description: "Assesses mechanical risk based on vehicle mileage thresholds",
        formula: "Risk Multiplier = Mileage / 100000",
        variables: ["Mileage"],
        target: "Below 1.0 = lower risk, above 1.5 = high risk",
        tags: ["mileage", "risk", "assessment"],
    },
    {
        name: "Margin Safety Buffer",
        category: "Car Flipping",
        description: "Ensures sufficient profit margin after accounting for unexpected repair costs",
        formula: "Margin Safety Buffer = Spread - Repair Buffer",
        variables: ["Spread", "Repair Buffer"],
        target: "Positive buffer required for deal approval",
        tags: ["margin", "safety", "buffer"],
    },
    {
        name: "Dealer Trade Gap",
        category: "Car Flipping",
        description: "Identifies profit opportunity between retail and trade-in values",
        formula: "Dealer Trade Gap = Retail Value - Trade-In Value",
        variables: ["Retail Value", "Trade-In Value"],
        target: "Larger gap = greater flip opportunity",
        tags: ["dealer", "trade", "spread"],
    },
    {
        name: "Title Risk Discount",
        category: "Car Flipping",
        description: "Applies appropriate discount for salvage or rebuilt title vehicles",
        formula: "Title Risk Discount = Clean Title Value * Salvage Deduction %",
        variables: ["Clean Title Value", "Salvage Deduction %"],
        target: "30-50% discount for salvage titles",
        tags: ["title", "salvage", "discount"],
    },
    {
        name: "Financing Profit Boost",
        category: "Car Flipping",
        description: "Calculates additional revenue from offering in-house financing options",
        formula: "Financing Profit Boost = Sale Price * Financing Upsell %",
        variables: ["Sale Price", "Financing Upsell %"],
        target: "5-15% additional revenue from financing",
        tags: ["financing", "upsell", "revenue"],
    },
    {
        name: "Inventory Turnover",
        category: "Car Flipping",
        description: "Measures how quickly vehicle inventory converts to sales",
        formula: "Inventory Turnover = Total Sales / Average Inventory",
        variables: ["Total Sales", "Average Inventory"],
        target: "2+ monthly turnover for healthy operations",
        tags: ["inventory", "turnover", "efficiency"],
    },
    {
        name: "Insurance Risk",
        category: "Car Flipping",
        description: "Evaluates insurance cost risk based on model-specific claim rates",
        formula: "Insurance Risk = Model Claim Rate * Average Claim Cost",
        variables: ["Model Claim Rate", "Average Claim Cost"],
        target: "Lower risk score = more insurable inventory",
        tags: ["insurance", "risk", "claims"],
    },
    {
        name: "Repossession Discount %",
        category: "Car Flipping",
        description: "Calculates expected discount when purchasing repossessed vehicles",
        formula: "Repossession Discount = ((Market Value - Repo Price) / Market Value) * 100",
        variables: ["Market Value", "Repo Price"],
        target: "40%+ discount for viable repo acquisitions",
        tags: ["repo", "discount", "acquisition"],
    },
    {
        name: "Wholesale Quick Flip",
        category: "Car Flipping",
        description: "Calculates minimum margin for rapid wholesale vehicle transactions",
        formula: "Wholesale Quick Flip = Spread - 5%",
        variables: ["Spread", "Quick Flip Fee"],
        target: "Positive margin after 5% quick-flip cost",
        tags: ["wholesale", "quick-flip", "margin"],
    },
    {
        name: "Negotiation Margin",
        category: "Car Flipping",
        description: "Measures negotiation room between asking and target offer price",
        formula: "Negotiation Margin = Asking Price - Offer Price",
        variables: ["Asking Price", "Offer Price"],
        target: "10-20% negotiation room on private sales",
        tags: ["negotiation", "margin", "offer"],
    },
    {
        name: "Buyer Close Probability",
        category: "Car Flipping",
        description: "Predicts buyer conversion rate from initial inquiry to sale close",
        formula: "Buyer Close Probability = (Inquiries / Views) * 100",
        variables: ["Inquiries", "Ad Views"],
        target: "5%+ inquiry-to-view ratio indicates strong listing",
        tags: ["buyer", "close", "probability"],
    },
    {
        name: "Ad Conversion Rate",
        category: "Car Flipping",
        description: "Measures advertising effectiveness by tracking message-to-view ratio",
        formula: "Ad Conversion Rate = (Messages / Views) * 100",
        variables: ["Messages Received", "Ad Views"],
        target: "3%+ conversion rate for effective ad spend",
        tags: ["advertising", "conversion", "marketing"],
    },
    {
        name: "High-Demand Score",
        category: "Car Flipping",
        description: "Identifies high-demand vehicles based on rapid sales velocity",
        formula: "High-Demand Score = Sold in 30 Days / Total Listed",
        variables: ["Sold in 30 Days", "Total Listed"],
        target: "Above 0.7 = high-demand vehicle to prioritize",
        tags: ["demand", "score", "priority"],
    },
    {
        name: "Mileage Adjustment",
        category: "Car Flipping",
        description: "Adjusts vehicle value based on mileage deviation from average",
        formula: "Mileage Adjustment = Base Value - (Excess Mileage * Penalty per Mile)",
        variables: ["Base Value", "Excess Mileage", "Penalty per Mile"],
        target: "Accurate pricing based on mileage impact",
        tags: ["mileage", "adjustment", "valuation"],
    },
    {
        name: "Trim Premium Spread",
        category: "Car Flipping",
        description: "Calculates price premium for higher trim levels versus base models",
        formula: "Trim Premium Spread = Higher Trim Value - Base Trim Value",
        variables: ["Higher Trim Value", "Base Trim Value"],
        target: "Identify trims with best premium-to-cost ratio",
        tags: ["trim", "premium", "spread"],
    },
    {
        name: "Accident Impact Deduction",
        category: "Car Flipping",
        description: "Quantifies value reduction from accident history on vehicle reports",
        formula: "Accident Impact Deduction = Clean Value * Accident Severity %",
        variables: ["Clean Value", "Accident Severity %"],
        target: "10-30% deduction depending on severity",
        tags: ["accident", "deduction", "history"],
    },
    {
        name: "Fleet Liquidation Discount",
        category: "Car Flipping",
        description: "Calculates discount opportunity when purchasing fleet vehicles in bulk",
        formula: "Fleet Liquidation Discount = ((Retail - Fleet Price) / Retail) * 100",
        variables: ["Retail Value", "Fleet Price"],
        target: "20%+ discount for fleet liquidation buys",
        tags: ["fleet", "liquidation", "bulk"],
    },
    {
        name: "Dealer Undervaluation Index",
        category: "Car Flipping",
        description: "Identifies vehicles undervalued by dealers relative to private market",
        formula: "Dealer Undervaluation Index = Private Market Value / Dealer Price",
        variables: ["Private Market Value", "Dealer Price"],
        target: "Above 1.2 = dealer undervaluing the vehicle",
        tags: ["dealer", "undervaluation", "opportunity"],
    },
    {
        name: "Depreciation Curve",
        category: "Car Flipping",
        description: "Models future vehicle value based on annual depreciation rate over time",
        formula: "Future Value = Current Value * (1 - Depreciation Rate) ^ Years",
        variables: ["Current Value", "Depreciation Rate", "Years"],
        target: "Buy on steep depreciation curve for best value",
        tags: ["depreciation", "curve", "projection"],
    },
    // ===== SECTION 3: SALES (71-110) =====
    {
        name: "Lead Value Formula",
        category: "Sales",
        description: "Calculates the expected value of each lead based on conversion probability",
        formula: "Expected Value = Close Rate * Average Deal Size",
        variables: ["Close Rate", "Average Deal Size"],
        target: "Prioritize leads with highest expected value",
        tags: ["leads", "value", "conversion"],
    },
    {
        name: "CAC Efficiency",
        category: "Sales",
        description: "Measures customer acquisition efficiency by comparing lifetime value to cost",
        formula: "LTV/CAC Ratio = Customer Lifetime Value / Customer Acquisition Cost",
        variables: ["Customer Lifetime Value", "Customer Acquisition Cost"],
        target: "LTV/CAC >= 3 for healthy unit economics",
        tags: ["cac", "ltv", "efficiency"],
    },
    {
        name: "Funnel Leak Detection",
        category: "Sales",
        description: "Identifies conversion drop-offs between sales funnel stages",
        formula: "Drop-Off % = (Stage N Count - Stage N+1 Count) / Stage N Count * 100",
        variables: ["Stage N Count", "Stage N+1 Count"],
        target: "Identify stages with > 40% drop-off for optimization",
        tags: ["funnel", "conversion", "optimization"],
    },
    {
        name: "Pipeline Velocity",
        category: "Sales",
        description: "Measures the speed of revenue flowing through the sales pipeline",
        formula: "Velocity = (Opportunities * Win Rate * Deal Size) / Sales Cycle Days",
        variables: ["Opportunities", "Win Rate", "Average Deal Size", "Sales Cycle Days"],
        target: "Increasing velocity indicates improving sales efficiency",
        tags: ["pipeline", "velocity", "revenue"],
    },
    {
        name: "Commission ROI",
        category: "Sales",
        description: "Calculates return on investment for commission-based sales teams",
        formula: "ROI = (Revenue Generated - Total Commission Paid) / Total Commission Paid * 100",
        variables: ["Revenue Generated", "Total Commission Paid"],
        target: "Minimum 300% ROI on commission spend",
        tags: ["commission", "roi", "team"],
    },
    {
        name: "Closing Probability",
        category: "Sales",
        description: "Predicts deal closing likelihood based on engagement signals",
        formula: "Probability = (Meetings * 0.3) + (Proposal Sent * 0.4) + (Champion Score * 0.3)",
        variables: ["Meetings Held", "Proposal Sent", "Champion Score"],
        target: "Above 70% = high-confidence close",
        tags: ["closing", "probability", "prediction"],
    },
    {
        name: "Expected Revenue",
        category: "Sales",
        description: "Projects total revenue from lead pipeline based on volume and conversion metrics",
        formula: "Expected Revenue = Leads * Close Rate * Avg Deal Size",
        variables: ["Leads", "Close Rate", "Avg Deal Size"],
        target: "Use for monthly and quarterly revenue forecasting",
        tags: ["revenue", "forecast", "pipeline"],
    },
    {
        name: "Cost per Lead",
        category: "Sales",
        description: "Calculates the average cost to generate a single qualified lead",
        formula: "Cost per Lead = Total Marketing Spend / Total Leads Generated",
        variables: ["Total Marketing Spend", "Total Leads Generated"],
        target: "Lower CPL while maintaining lead quality",
        tags: ["cpl", "marketing", "cost"],
    },
    {
        name: "Revenue per Lead",
        category: "Sales",
        description: "Measures average revenue generated per lead across all channels",
        formula: "Revenue per Lead = Total Revenue / Total Leads",
        variables: ["Total Revenue", "Total Leads"],
        target: "Track RPL trend to optimize lead sources",
        tags: ["revenue", "leads", "efficiency"],
    },
    {
        name: "Break-Even Leads",
        category: "Sales",
        description: "Determines minimum lead volume needed to cover sales costs",
        formula: "Break-Even Leads = Total Sales Costs / Revenue per Lead",
        variables: ["Total Sales Costs", "Revenue per Lead"],
        target: "Exceed break-even by 2x for profitable operations",
        tags: ["break-even", "leads", "threshold"],
    },
    {
        name: "Close Velocity",
        category: "Sales",
        description: "Measures the speed at which deals progress from opportunity to close",
        formula: "Close Velocity = Deals Closed / Time Period (days)",
        variables: ["Deals Closed", "Time Period"],
        target: "Increasing velocity indicates pipeline health",
        tags: ["close", "velocity", "speed"],
    },
    {
        name: "Sales Efficiency Ratio",
        category: "Sales",
        description: "Evaluates revenue output relative to total sales department expenditure",
        formula: "Sales Efficiency Ratio = Revenue / Total Sales Expense",
        variables: ["Revenue", "Total Sales Expense"],
        target: "Above 3.0 for efficient sales operations",
        tags: ["efficiency", "sales", "ratio"],
    },
    {
        name: "Churn Rate",
        category: "Sales",
        description: "Tracks the rate of customer loss over a defined period",
        formula: "Churn Rate = (Lost Customers / Total Customers) * 100",
        variables: ["Lost Customers", "Total Customers"],
        target: "Below 5% monthly churn for sustainable growth",
        tags: ["churn", "retention", "customers"],
    },
    {
        name: "Retention Rate",
        category: "Sales",
        description: "Measures the percentage of customers retained over a given period",
        formula: "Retention Rate = ((End Customers - New Customers) / Start Customers) * 100",
        variables: ["End Customers", "New Customers", "Start Customers"],
        target: "90%+ retention rate for recurring revenue models",
        tags: ["retention", "customers", "loyalty"],
    },
    {
        name: "Upsell Rate",
        category: "Sales",
        description: "Tracks the percentage of existing customers upgrading to higher-value products",
        formula: "Upsell Rate = (Upsold Customers / Total Customers) * 100",
        variables: ["Upsold Customers", "Total Customers"],
        target: "15%+ upsell rate indicates strong product value",
        tags: ["upsell", "expansion", "revenue"],
    },
    {
        name: "Cross-Sell Lift",
        category: "Sales",
        description: "Measures incremental revenue generated from cross-selling additional products",
        formula: "Cross-Sell Lift = Cross-Sell Revenue / Base Revenue * 100",
        variables: ["Cross-Sell Revenue", "Base Revenue"],
        target: "10%+ lift from cross-sell initiatives",
        tags: ["cross-sell", "lift", "revenue"],
    },
    {
        name: "Referral Multiplier",
        category: "Sales",
        description: "Quantifies the revenue amplification effect of customer referrals",
        formula: "Referral Multiplier = Referral Revenue / Referral Program Cost",
        variables: ["Referral Revenue", "Referral Program Cost"],
        target: "5x+ multiplier for effective referral programs",
        tags: ["referral", "multiplier", "growth"],
    },
    {
        name: "Ad ROAS",
        category: "Sales",
        description: "Calculates return on ad spend to evaluate advertising campaign profitability",
        formula: "ROAS = Revenue from Ads / Ad Spend",
        variables: ["Revenue from Ads", "Ad Spend"],
        target: "3x+ ROAS for profitable ad campaigns",
        tags: ["roas", "advertising", "roi"],
    },
    {
        name: "Pipeline Value",
        category: "Sales",
        description: "Calculates total weighted value of all deals in the sales pipeline",
        formula: "Pipeline Value = Sum(Deal Value * Win Probability)",
        variables: ["Deal Values", "Win Probabilities"],
        target: "3x target revenue in pipeline for quota coverage",
        tags: ["pipeline", "value", "forecast"],
    },
    {
        name: "Forecast Accuracy",
        category: "Sales",
        description: "Measures how closely actual revenue matches forecasted revenue",
        formula: "Forecast Accuracy = (1 - |Actual - Forecast| / Forecast) * 100",
        variables: ["Actual Revenue", "Forecasted Revenue"],
        target: "85%+ accuracy for reliable business planning",
        tags: ["forecast", "accuracy", "planning"],
    },
    {
        name: "Revenue Growth Rate",
        category: "Sales",
        description: "Tracks period-over-period revenue growth as a percentage",
        formula: "Revenue Growth Rate = ((Current Revenue - Prior Revenue) / Prior Revenue) * 100",
        variables: ["Current Revenue", "Prior Revenue"],
        target: "20%+ quarterly growth for scaling businesses",
        tags: ["growth", "revenue", "trend"],
    },
    {
        name: "Net Revenue Retention",
        category: "Sales",
        description: "Measures total revenue retention including expansion and contraction from existing customers",
        formula: "NRR = ((Start MRR + Expansion - Contraction - Churn) / Start MRR) * 100",
        variables: ["Start MRR", "Expansion Revenue", "Contraction", "Churn"],
        target: "110%+ NRR indicates strong net expansion",
        tags: ["nrr", "retention", "expansion"],
    },
    {
        name: "Gross Margin",
        category: "Sales",
        description: "Calculates the percentage of revenue retained after direct costs",
        formula: "Gross Margin = ((Revenue - COGS) / Revenue) * 100",
        variables: ["Revenue", "Cost of Goods Sold"],
        target: "60%+ gross margin for service businesses",
        tags: ["margin", "profitability", "cogs"],
    },
    {
        name: "Price Elasticity",
        category: "Sales",
        description: "Measures how demand changes relative to price adjustments",
        formula: "Price Elasticity = % Change in Demand / % Change in Price",
        variables: ["% Change in Demand", "% Change in Price"],
        target: "Elasticity < 1 allows price increases without demand loss",
        tags: ["pricing", "elasticity", "demand"],
    },
    {
        name: "Offer Conversion Index",
        category: "Sales",
        description: "Tracks how effectively offers convert prospects into paying customers",
        formula: "Offer Conversion Index = Conversions / Offers Presented * 100",
        variables: ["Conversions", "Offers Presented"],
        target: "25%+ conversion rate for optimized offers",
        tags: ["offer", "conversion", "optimization"],
    },
    {
        name: "Sales Rep Productivity",
        category: "Sales",
        description: "Measures revenue generated per sales representative for team optimization",
        formula: "Sales Rep Productivity = Total Revenue / Number of Sales Reps",
        variables: ["Total Revenue", "Number of Sales Reps"],
        target: "Increasing per-rep productivity over time",
        tags: ["productivity", "rep", "team"],
    },
    {
        name: "Objection Frequency Index",
        category: "Sales",
        description: "Tracks common objection patterns to improve sales training and scripts",
        formula: "Objection Frequency Index = Objection Count / Total Calls",
        variables: ["Objection Count", "Total Calls"],
        target: "Decreasing index indicates improved pitch quality",
        tags: ["objection", "frequency", "training"],
    },
    {
        name: "Win/Loss Ratio",
        category: "Sales",
        description: "Compares won deals to lost deals for competitive performance analysis",
        formula: "Win/Loss Ratio = Deals Won / Deals Lost",
        variables: ["Deals Won", "Deals Lost"],
        target: "Above 2.0 ratio for competitive sales teams",
        tags: ["win", "loss", "competitive"],
    },
    {
        name: "Deal Slippage Rate",
        category: "Sales",
        description: "Measures the percentage of deals that slip past their expected close date",
        formula: "Deal Slippage Rate = (Slipped Deals / Total Forecasted Deals) * 100",
        variables: ["Slipped Deals", "Total Forecasted Deals"],
        target: "Below 15% slippage for reliable forecasting",
        tags: ["slippage", "forecast", "timing"],
    },
    {
        name: "Cold Outreach Yield",
        category: "Sales",
        description: "Measures response and conversion rate from cold outreach campaigns",
        formula: "Cold Outreach Yield = (Responses / Total Outreach) * 100",
        variables: ["Responses", "Total Outreach"],
        target: "5%+ response rate for effective cold campaigns",
        tags: ["cold", "outreach", "yield"],
    },
    {
        name: "Email Open-to-Close Ratio",
        category: "Sales",
        description: "Tracks the full funnel from email open to deal close for email campaigns",
        formula: "Email Open-to-Close Ratio = (Deals Closed / Emails Opened) * 100",
        variables: ["Deals Closed", "Emails Opened"],
        target: "1%+ open-to-close for high-performing emails",
        tags: ["email", "close", "funnel"],
    },
    {
        name: "SMS Close Rate",
        category: "Sales",
        description: "Measures deal closure rate from SMS-based sales outreach",
        formula: "SMS Close Rate = (SMS Deals Closed / SMS Sent) * 100",
        variables: ["SMS Deals Closed", "SMS Sent"],
        target: "2%+ close rate for SMS campaigns",
        tags: ["sms", "close", "channel"],
    },
    {
        name: "Demo-to-Close Ratio",
        category: "Sales",
        description: "Measures conversion effectiveness from product demos to closed deals",
        formula: "Demo-to-Close Ratio = (Deals Closed / Demos Given) * 100",
        variables: ["Deals Closed", "Demos Given"],
        target: "30%+ close rate from demos indicates strong product-market fit",
        tags: ["demo", "close", "conversion"],
    },
    {
        name: "Enterprise Deal Lift",
        category: "Sales",
        description: "Quantifies revenue premium from enterprise versus standard deals",
        formula: "Enterprise Deal Lift = Avg Enterprise Deal / Avg Standard Deal",
        variables: ["Avg Enterprise Deal Size", "Avg Standard Deal Size"],
        target: "5x+ lift justifies enterprise sales investment",
        tags: ["enterprise", "lift", "premium"],
    },
    {
        name: "High-Ticket Margin",
        category: "Sales",
        description: "Calculates profit margin on high-value sales transactions",
        formula: "High-Ticket Margin = ((Sale Price - Total Cost) / Sale Price) * 100",
        variables: ["Sale Price", "Total Cost"],
        target: "40%+ margin on high-ticket offerings",
        tags: ["high-ticket", "margin", "profit"],
    },
    {
        name: "Affiliate Revenue Share",
        category: "Sales",
        description: "Tracks revenue generated through affiliate partnerships and commission splits",
        formula: "Affiliate Revenue Share = Affiliate Revenue / Total Revenue * 100",
        variables: ["Affiliate Revenue", "Total Revenue"],
        target: "Optimize affiliate mix for maximum ROI",
        tags: ["affiliate", "revenue", "partnership"],
    },
    {
        name: "Partner ROI",
        category: "Sales",
        description: "Measures return on investment from strategic partnership channels",
        formula: "Partner ROI = (Partner Revenue - Partner Costs) / Partner Costs * 100",
        variables: ["Partner Revenue", "Partner Costs"],
        target: "200%+ ROI for valuable partnerships",
        tags: ["partner", "roi", "channel"],
    },
    {
        name: "Revenue per Employee",
        category: "Sales",
        description: "Benchmarks organizational efficiency by revenue generated per team member",
        formula: "Revenue per Employee = Total Revenue / Total Employees",
        variables: ["Total Revenue", "Total Employees"],
        target: "$200K+ per employee for efficient operations",
        tags: ["revenue", "employee", "efficiency"],
    },
    {
        name: "Sales Scaling Factor",
        category: "Sales",
        description: "Measures how revenue scales relative to sales team growth",
        formula: "Sales Scaling Factor = Revenue Growth % / Team Growth %",
        variables: ["Revenue Growth %", "Team Growth %"],
        target: "Above 1.0 = scaling efficiently with team growth",
        tags: ["scaling", "growth", "efficiency"],
    },
    {
        name: "Drop-Off %",
        category: "Sales",
        description: "Identifies the percentage of prospects lost at each sales stage",
        formula: "Drop-Off % = (Lost at Stage / Entered Stage) * 100",
        variables: ["Lost at Stage", "Entered Stage"],
        target: "Below 30% drop-off at each stage for healthy funnel",
        tags: ["drop-off", "funnel", "loss"],
    },
    // ===== SECTION 4: CAPITAL DEPLOYMENT (111-150) =====
    {
        name: "Liquidity Ratio",
        category: "Capital Deployment",
        description: "Ensures adequate operating reserves relative to monthly burn rate",
        formula: "Ratio = Operating Reserves / Monthly Burn Rate",
        variables: ["Operating Reserves", "Monthly Burn Rate"],
        target: ">= 6 months of reserves for safety",
        tags: ["liquidity", "reserves", "safety"],
    },
    {
        name: "Reinvestment Multiplier",
        category: "Capital Deployment",
        description: "Calculates the optimal profit reinvestment percentage for growth",
        formula: "Reinvest Amount = Net Profit * 0.60",
        variables: ["Net Profit"],
        target: "60% reinvest, 30% reserve, 10% expansion",
        tags: ["reinvestment", "growth", "allocation"],
    },
    {
        name: "Capital Deployment Efficiency",
        category: "Capital Deployment",
        description: "Measures how efficiently deployed capital generates returns",
        formula: "Efficiency = Annual Returns / Total Capital Deployed * 100",
        variables: ["Annual Returns", "Total Capital Deployed"],
        target: "15%+ annual return on deployed capital",
        tags: ["efficiency", "returns", "deployment"],
    },
    {
        name: "Debt-to-Equity Ratio",
        category: "Capital Deployment",
        description: "Monitors leverage levels across the portfolio",
        formula: "D/E = Total Liabilities / Total Equity",
        variables: ["Total Liabilities", "Total Equity"],
        target: "D/E < 2.0 for conservative leverage",
        tags: ["leverage", "debt", "equity"],
    },
    {
        name: "Quick Ratio",
        category: "Capital Deployment",
        description: "Measures ability to meet short-term obligations with liquid assets only",
        formula: "Quick Ratio = (Cash + Receivables + Short-Term Investments) / Current Liabilities",
        variables: ["Cash", "Receivables", "Short-Term Investments", "Current Liabilities"],
        target: "Above 1.0 for adequate short-term liquidity",
        tags: ["quick-ratio", "liquidity", "solvency"],
    },
    {
        name: "Debt-to-Income",
        category: "Capital Deployment",
        description: "Evaluates total debt burden relative to income for lending qualification",
        formula: "DTI = (Total Monthly Debt Payments / Gross Monthly Income) * 100",
        variables: ["Total Monthly Debt Payments", "Gross Monthly Income"],
        target: "Below 36% for favorable lending terms",
        tags: ["dti", "debt", "income"],
    },
    {
        name: "Leverage Multiplier",
        category: "Capital Deployment",
        description: "Calculates how leverage amplifies returns on invested capital",
        formula: "Leverage Multiplier = Total Assets / Total Equity",
        variables: ["Total Assets", "Total Equity"],
        target: "2-4x leverage for balanced risk-return profile",
        tags: ["leverage", "multiplier", "amplification"],
    },
    {
        name: "Return on Assets",
        category: "Capital Deployment",
        description: "Measures profitability relative to total assets deployed",
        formula: "ROA = (Net Income / Total Assets) * 100",
        variables: ["Net Income", "Total Assets"],
        target: "5%+ ROA for efficient asset utilization",
        tags: ["roa", "assets", "profitability"],
    },
    {
        name: "Return on Equity",
        category: "Capital Deployment",
        description: "Calculates the return generated on shareholder equity investment",
        formula: "ROE = (Net Income / Shareholders Equity) * 100",
        variables: ["Net Income", "Shareholders Equity"],
        target: "15%+ ROE for strong equity returns",
        tags: ["roe", "equity", "returns"],
    },
    {
        name: "Break-Even Revenue",
        category: "Capital Deployment",
        description: "Determines minimum revenue needed to cover all fixed and variable costs",
        formula: "Break-Even Revenue = Fixed Costs / (1 - Variable Cost Ratio)",
        variables: ["Fixed Costs", "Variable Cost Ratio"],
        target: "Exceed break-even by 30%+ for margin of safety",
        tags: ["break-even", "revenue", "threshold"],
    },
    {
        name: "Burn Rate",
        category: "Capital Deployment",
        description: "Tracks monthly cash consumption rate for runway planning",
        formula: "Burn Rate = (Start Balance - End Balance) / Months",
        variables: ["Start Balance", "End Balance", "Months"],
        target: "Decreasing burn rate indicates path to profitability",
        tags: ["burn", "cash", "runway"],
    },
    {
        name: "Runway Months",
        category: "Capital Deployment",
        description: "Calculates how many months of operation remaining at current burn rate",
        formula: "Runway Months = Cash Balance / Monthly Burn Rate",
        variables: ["Cash Balance", "Monthly Burn Rate"],
        target: "18+ months runway for comfortable operations",
        tags: ["runway", "survival", "planning"],
    },
    {
        name: "Compound Growth Formula",
        category: "Capital Deployment",
        description: "Projects future value of capital with compound interest over time",
        formula: "FV = PV * (1 + Rate) ^ Periods",
        variables: ["Present Value", "Rate", "Periods"],
        target: "Use to project long-term wealth accumulation",
        tags: ["compound", "growth", "projection"],
    },
    {
        name: "Portfolio Diversification Score",
        category: "Capital Deployment",
        description: "Quantifies how well-diversified a portfolio is across asset classes",
        formula: "Diversification Score = 1 - Sum(Asset Weight^2)",
        variables: ["Asset Weights"],
        target: "Above 0.7 for well-diversified portfolio",
        tags: ["diversification", "portfolio", "allocation"],
    },
    {
        name: "Volatility Index",
        category: "Capital Deployment",
        description: "Measures portfolio value fluctuation to assess investment risk level",
        formula: "Volatility Index = Standard Deviation of Returns / Mean Return",
        variables: ["Returns Data", "Mean Return"],
        target: "Lower volatility = more stable returns",
        tags: ["volatility", "risk", "stability"],
    },
    {
        name: "Asset Allocation %",
        category: "Capital Deployment",
        description: "Tracks percentage distribution of capital across different asset classes",
        formula: "Asset Allocation % = (Asset Class Value / Total Portfolio Value) * 100",
        variables: ["Asset Class Value", "Total Portfolio Value"],
        target: "Maintain target allocation within 5% drift bands",
        tags: ["allocation", "balance", "portfolio"],
    },
    {
        name: "Capital Rotation Speed",
        category: "Capital Deployment",
        description: "Measures how quickly capital cycles through investments and returns",
        formula: "Capital Rotation Speed = Annual Revenue / Average Capital Employed",
        variables: ["Annual Revenue", "Average Capital Employed"],
        target: "2x+ rotation for efficient capital usage",
        tags: ["rotation", "speed", "efficiency"],
    },
    {
        name: "Reserve Ratio",
        category: "Capital Deployment",
        description: "Measures the proportion of capital held in reserve versus deployed",
        formula: "Reserve Ratio = Reserves / Total Capital * 100",
        variables: ["Reserves", "Total Capital"],
        target: "15-25% reserve ratio for balanced safety",
        tags: ["reserve", "ratio", "safety"],
    },
    {
        name: "Equity Accumulation Rate",
        category: "Capital Deployment",
        description: "Tracks the speed of equity building across all investments",
        formula: "Equity Accumulation Rate = (Equity End - Equity Start) / Equity Start * 100",
        variables: ["Equity End", "Equity Start"],
        target: "10%+ annual equity accumulation rate",
        tags: ["equity", "accumulation", "growth"],
    },
    {
        name: "Loan Coverage Ratio",
        category: "Capital Deployment",
        description: "Assesses ability to service debt obligations from operating income",
        formula: "Loan Coverage Ratio = Operating Income / Total Debt Payments",
        variables: ["Operating Income", "Total Debt Payments"],
        target: "Above 1.5 for comfortable debt service",
        tags: ["loan", "coverage", "debt-service"],
    },
    {
        name: "Financing Spread",
        category: "Capital Deployment",
        description: "Calculates the margin between borrowing cost and investment return",
        formula: "Financing Spread = Investment Return % - Borrowing Cost %",
        variables: ["Investment Return %", "Borrowing Cost %"],
        target: "Positive spread required for leveraged investments",
        tags: ["financing", "spread", "arbitrage"],
    },
    {
        name: "Weighted Average Cost of Capital",
        category: "Capital Deployment",
        description: "Calculates blended cost of all capital sources for investment hurdle rates",
        formula: "WACC = (E/V * Re) + (D/V * Rd * (1 - Tax Rate))",
        variables: ["Equity Weight", "Cost of Equity", "Debt Weight", "Cost of Debt", "Tax Rate"],
        target: "Investment returns must exceed WACC",
        tags: ["wacc", "cost-of-capital", "hurdle"],
    },
    {
        name: "Net Present Value",
        category: "Capital Deployment",
        description: "Calculates the present value of future cash flows minus initial investment",
        formula: "NPV = Sum(Cash Flow / (1 + Discount Rate)^t) - Initial Investment",
        variables: ["Cash Flows", "Discount Rate", "Initial Investment"],
        target: "Positive NPV required for investment approval",
        tags: ["npv", "valuation", "investment"],
    },
    {
        name: "Internal Rate of Return",
        category: "Capital Deployment",
        description: "Determines the discount rate that makes NPV equal to zero for an investment",
        formula: "IRR = Rate where NPV = 0",
        variables: ["Cash Flows", "Initial Investment"],
        target: "IRR must exceed WACC for viable investments",
        tags: ["irr", "return", "threshold"],
    },
    {
        name: "Profit Retention Rate",
        category: "Capital Deployment",
        description: "Measures the percentage of profits retained for reinvestment versus distributed",
        formula: "Profit Retention Rate = (Net Income - Distributions) / Net Income * 100",
        variables: ["Net Income", "Distributions"],
        target: "60%+ retention for aggressive growth phase",
        tags: ["retention", "profit", "reinvestment"],
    },
    {
        name: "Investor Yield",
        category: "Capital Deployment",
        description: "Calculates the annual yield returned to investors on their capital",
        formula: "Investor Yield = (Annual Distributions / Invested Capital) * 100",
        variables: ["Annual Distributions", "Invested Capital"],
        target: "8-12% annual yield for competitive investor returns",
        tags: ["investor", "yield", "distributions"],
    },
    {
        name: "Cash Conversion Cycle",
        category: "Capital Deployment",
        description: "Measures time between cash outflow and cash collection for working capital",
        formula: "CCC = Days Inventory + Days Receivable - Days Payable",
        variables: ["Days Inventory Outstanding", "Days Sales Outstanding", "Days Payable Outstanding"],
        target: "Shorter cycle = more efficient cash management",
        tags: ["cash", "conversion", "cycle"],
    },
    {
        name: "Asset Turnover",
        category: "Capital Deployment",
        description: "Measures how efficiently assets generate revenue",
        formula: "Asset Turnover = Revenue / Average Total Assets",
        variables: ["Revenue", "Average Total Assets"],
        target: "Higher turnover = more efficient asset utilization",
        tags: ["asset", "turnover", "efficiency"],
    },
    {
        name: "Expansion Multiplier",
        category: "Capital Deployment",
        description: "Projects growth impact of reinvesting capital at compound returns",
        formula: "Expansion Multiplier = (1 + Reinvestment Rate * ROE) ^ Years",
        variables: ["Reinvestment Rate", "ROE", "Years"],
        target: "2x+ expansion over 5-year projection",
        tags: ["expansion", "multiplier", "growth"],
    },
    {
        name: "Acquisition Cost per Asset",
        category: "Capital Deployment",
        description: "Tracks average all-in cost to acquire each income-producing asset",
        formula: "Acquisition Cost per Asset = Total Acquisition Costs / Number of Assets",
        variables: ["Total Acquisition Costs", "Number of Assets"],
        target: "Decreasing cost indicates improving deal flow",
        tags: ["acquisition", "cost", "asset"],
    },
    {
        name: "Portfolio Risk Score",
        category: "Capital Deployment",
        description: "Aggregate risk rating across all portfolio holdings weighted by position size",
        formula: "Portfolio Risk Score = Sum(Asset Risk * Asset Weight)",
        variables: ["Asset Risk Scores", "Asset Weights"],
        target: "Below 6.0 for moderate risk tolerance",
        tags: ["portfolio", "risk", "score"],
    },
    {
        name: "Inflation Hedge Factor",
        category: "Capital Deployment",
        description: "Measures how well portfolio returns offset inflation erosion",
        formula: "Inflation Hedge Factor = Real Return / Inflation Rate",
        variables: ["Real Return", "Inflation Rate"],
        target: "Above 1.5 for effective inflation protection",
        tags: ["inflation", "hedge", "protection"],
    },
    {
        name: "Tax Shield Value",
        category: "Capital Deployment",
        description: "Calculates tax savings from deductible expenses like depreciation and interest",
        formula: "Tax Shield Value = Deductible Amount * Tax Rate",
        variables: ["Deductible Amount", "Tax Rate"],
        target: "Maximize tax shield to improve after-tax returns",
        tags: ["tax", "shield", "deduction"],
    },
    {
        name: "Depreciation Benefit",
        category: "Capital Deployment",
        description: "Quantifies the annual tax benefit from asset depreciation schedules",
        formula: "Depreciation Benefit = (Asset Value / Useful Life) * Tax Rate",
        variables: ["Asset Value", "Useful Life", "Tax Rate"],
        target: "Accelerated depreciation maximizes early benefits",
        tags: ["depreciation", "tax", "benefit"],
    },
    {
        name: "Asset Liquidity Index",
        category: "Capital Deployment",
        description: "Rates how quickly each asset can be converted to cash without value loss",
        formula: "Asset Liquidity Index = Liquid Assets / Total Assets * 100",
        variables: ["Liquid Assets", "Total Assets"],
        target: "30%+ liquidity index for financial flexibility",
        tags: ["liquidity", "index", "flexibility"],
    },
    {
        name: "Credit Utilization",
        category: "Capital Deployment",
        description: "Tracks the percentage of available credit currently in use",
        formula: "Credit Utilization = (Used Credit / Total Credit Limit) * 100",
        variables: ["Used Credit", "Total Credit Limit"],
        target: "Below 30% utilization for optimal credit health",
        tags: ["credit", "utilization", "health"],
    },
    {
        name: "Credit Expansion Potential",
        category: "Capital Deployment",
        description: "Estimates additional borrowing capacity based on current financial position",
        formula: "Credit Expansion Potential = (Max DTI - Current DTI) * Gross Income",
        variables: ["Max DTI Ratio", "Current DTI Ratio", "Gross Income"],
        target: "Positive potential indicates room for additional leverage",
        tags: ["credit", "expansion", "capacity"],
    },
    {
        name: "Investment Spread",
        category: "Capital Deployment",
        description: "Measures the gap between investment return and cost of capital",
        formula: "Investment Spread = Investment Return - Cost of Capital",
        variables: ["Investment Return", "Cost of Capital"],
        target: "Positive spread required for value creation",
        tags: ["investment", "spread", "value"],
    },
    {
        name: "Passive Income Ratio",
        category: "Capital Deployment",
        description: "Measures the proportion of total income derived from passive sources",
        formula: "Passive Income Ratio = (Passive Income / Total Income) * 100",
        variables: ["Passive Income", "Total Income"],
        target: "50%+ passive income ratio for financial freedom",
        tags: ["passive", "income", "ratio"],
    },
    {
        name: "Capital Efficiency",
        category: "Capital Deployment",
        description: "Measures how effectively each dollar of capital generates profit",
        formula: "Capital Efficiency = Net Profit / Total Capital Deployed",
        variables: ["Net Profit", "Total Capital Deployed"],
        target: "Above 0.20 for efficient capital allocation",
        tags: ["capital", "efficiency", "profit"],
    },
    // ===== SECTION 5: RISK MANAGEMENT (151-175) =====
    {
        name: "Risk-Adjusted Return",
        category: "Risk Management",
        description: "Adjusts returns for risk level to compare deals fairly",
        formula: "RAR = Expected Return / Risk Score",
        variables: ["Expected Return", "Risk Score"],
        target: "Higher RAR = better risk-adjusted opportunity",
        tags: ["risk", "return", "comparison"],
    },
    {
        name: "Portfolio Concentration",
        category: "Risk Management",
        description: "Measures exposure to any single asset type or market",
        formula: "Concentration = Single Asset Value / Total Portfolio Value * 100",
        variables: ["Single Asset Value", "Total Portfolio Value"],
        target: "No single asset > 25% of total portfolio",
        tags: ["diversification", "concentration", "portfolio"],
    },
    {
        name: "Drawdown Recovery",
        category: "Risk Management",
        description: "Calculates time to recover from a portfolio drawdown",
        formula: "Recovery Time = Loss Amount / Monthly Net Income",
        variables: ["Loss Amount", "Monthly Net Income"],
        target: "Recovery within 6 months for acceptable risk",
        tags: ["drawdown", "recovery", "risk"],
    },
    {
        name: "Risk Score",
        category: "Risk Management",
        description: "Quantifies deal risk by multiplying probability of failure by financial impact",
        formula: "Risk Score = Probability * Impact",
        variables: ["Probability", "Impact"],
        target: "Score below 25 for acceptable risk level",
        tags: ["risk", "score", "assessment"],
    },
    {
        name: "Fraud Detection Threshold",
        category: "Risk Management",
        description: "Sets alert thresholds for transactions that deviate from normal patterns",
        formula: "Fraud Flag = Transaction Value > (Avg Transaction * Threshold Multiplier)",
        variables: ["Transaction Value", "Avg Transaction", "Threshold Multiplier"],
        target: "Flag transactions 3x above average for review",
        tags: ["fraud", "detection", "threshold"],
    },
    {
        name: "Anomaly Variance %",
        category: "Risk Management",
        description: "Identifies data points that deviate significantly from expected ranges",
        formula: "Anomaly Variance = ((Actual - Expected) / Expected) * 100",
        variables: ["Actual Value", "Expected Value"],
        target: "Investigate variances exceeding 20%",
        tags: ["anomaly", "variance", "detection"],
    },
    {
        name: "Loss Exposure",
        category: "Risk Management",
        description: "Calculates maximum potential financial loss from a single position or deal",
        formula: "Loss Exposure = Position Size * Maximum Loss %",
        variables: ["Position Size", "Maximum Loss %"],
        target: "Never exceed 5% of total capital in single exposure",
        tags: ["loss", "exposure", "limit"],
    },
    {
        name: "Reserve Coverage",
        category: "Risk Management",
        description: "Measures how well financial reserves cover potential worst-case losses",
        formula: "Reserve Coverage = Total Reserves / Maximum Potential Loss",
        variables: ["Total Reserves", "Maximum Potential Loss"],
        target: "Above 2.0 for adequate loss protection",
        tags: ["reserve", "coverage", "protection"],
    },
    {
        name: "Worst Case Scenario Margin",
        category: "Risk Management",
        description: "Calculates remaining margin after applying worst-case assumptions",
        formula: "Worst Case Margin = Expected Return - Worst Case Loss",
        variables: ["Expected Return", "Worst Case Loss"],
        target: "Positive margin even in worst-case scenarios",
        tags: ["worst-case", "margin", "stress"],
    },
    {
        name: "Sensitivity Analysis",
        category: "Risk Management",
        description: "Measures how output changes when key input variables are adjusted",
        formula: "Sensitivity = % Change in Output / % Change in Input",
        variables: ["Output Change %", "Input Change %"],
        target: "Identify variables with highest sensitivity for risk focus",
        tags: ["sensitivity", "analysis", "variables"],
    },
    {
        name: "Stress Test Outcome",
        category: "Risk Management",
        description: "Projects portfolio performance under extreme market conditions",
        formula: "Stress Test Outcome = Portfolio Value * (1 - Stress Scenario Drop %)",
        variables: ["Portfolio Value", "Stress Scenario Drop %"],
        target: "Maintain positive equity after 30% market drop",
        tags: ["stress", "test", "scenario"],
    },
    {
        name: "Volatility Buffer",
        category: "Risk Management",
        description: "Calculates additional capital buffer needed to absorb market volatility",
        formula: "Volatility Buffer = Position Size * Volatility % * Safety Factor",
        variables: ["Position Size", "Volatility %", "Safety Factor"],
        target: "Maintain buffer equal to 2x expected volatility",
        tags: ["volatility", "buffer", "capital"],
    },
    {
        name: "Operational Risk Ratio",
        category: "Risk Management",
        description: "Measures operational losses relative to gross revenue for risk monitoring",
        formula: "Operational Risk Ratio = (Operational Losses / Gross Revenue) * 100",
        variables: ["Operational Losses", "Gross Revenue"],
        target: "Below 2% for well-managed operations",
        tags: ["operational", "risk", "ratio"],
    },
    {
        name: "Market Downturn Impact",
        category: "Risk Management",
        description: "Projects portfolio value impact during various market correction scenarios",
        formula: "Market Downturn Impact = Portfolio Value * Beta * Market Drop %",
        variables: ["Portfolio Value", "Portfolio Beta", "Market Drop %"],
        target: "Limit downturn impact to 15% of portfolio value",
        tags: ["downturn", "impact", "market"],
    },
    {
        name: "Overleveraging Ratio",
        category: "Risk Management",
        description: "Detects when debt levels exceed safe thresholds relative to income",
        formula: "Overleveraging Ratio = Total Debt / Annual Net Income",
        variables: ["Total Debt", "Annual Net Income"],
        target: "Below 4.0 to avoid overleveraging risk",
        tags: ["overleveraging", "debt", "warning"],
    },
    {
        name: "Exposure Concentration",
        category: "Risk Management",
        description: "Identifies over-concentration in any single market, asset, or counterparty",
        formula: "Exposure Concentration = Largest Exposure / Total Exposure * 100",
        variables: ["Largest Exposure", "Total Exposure"],
        target: "No single exposure exceeding 20% of total",
        tags: ["exposure", "concentration", "diversification"],
    },
    {
        name: "Liquidity Shock Test",
        category: "Risk Management",
        description: "Simulates ability to meet obligations during sudden liquidity demands",
        formula: "Liquidity Shock Test = Liquid Assets / Immediate Obligations",
        variables: ["Liquid Assets", "Immediate Obligations"],
        target: "Above 1.5 for surviving liquidity shocks",
        tags: ["liquidity", "shock", "stress"],
    },
    {
        name: "Recovery Time Estimate",
        category: "Risk Management",
        description: "Projects months needed to recover from a significant financial setback",
        formula: "Recovery Time = Total Loss / Monthly Recovery Rate",
        variables: ["Total Loss", "Monthly Recovery Rate"],
        target: "Under 12 months for acceptable recovery timeline",
        tags: ["recovery", "time", "estimate"],
    },
    {
        name: "Portfolio Beta",
        category: "Risk Management",
        description: "Measures portfolio sensitivity to overall market movements",
        formula: "Portfolio Beta = Sum(Asset Beta * Asset Weight)",
        variables: ["Asset Betas", "Asset Weights"],
        target: "Beta near 1.0 for market-neutral, below 0.8 for defensive",
        tags: ["beta", "portfolio", "sensitivity"],
    },
    {
        name: "Revenue Stability Index",
        category: "Risk Management",
        description: "Measures revenue consistency by tracking variance from monthly averages",
        formula: "Revenue Stability Index = 1 - (Revenue Std Dev / Revenue Mean)",
        variables: ["Monthly Revenue Data"],
        target: "Above 0.8 for stable and predictable revenue",
        tags: ["stability", "revenue", "consistency"],
    },
    {
        name: "Contract Risk Weight",
        category: "Risk Management",
        description: "Assigns risk weight to contracts based on complexity, value, and counterparty",
        formula: "Contract Risk Weight = Contract Value * Risk Factor * Counterparty Score",
        variables: ["Contract Value", "Risk Factor", "Counterparty Score"],
        target: "Lower weighted score = lower contract risk",
        tags: ["contract", "risk", "weight"],
    },
    {
        name: "Counterparty Risk Score",
        category: "Risk Management",
        description: "Evaluates the creditworthiness and reliability of business counterparties",
        formula: "Counterparty Risk Score = (Credit Rating + Payment History + Financial Health) / 3",
        variables: ["Credit Rating", "Payment History", "Financial Health"],
        target: "Score above 7/10 for approved counterparties",
        tags: ["counterparty", "risk", "credit"],
    },
    {
        name: "Compliance Score",
        category: "Risk Management",
        description: "Tracks regulatory compliance status across all business operations",
        formula: "Compliance Score = (Compliant Items / Total Items) * 100",
        variables: ["Compliant Items", "Total Required Items"],
        target: "95%+ compliance score for regulatory safety",
        tags: ["compliance", "regulatory", "audit"],
    },
    {
        name: "Audit Variance",
        category: "Risk Management",
        description: "Measures discrepancies found during financial audits against expected values",
        formula: "Audit Variance = |Reported Value - Audited Value| / Audited Value * 100",
        variables: ["Reported Value", "Audited Value"],
        target: "Below 2% variance for clean audit results",
        tags: ["audit", "variance", "accuracy"],
    },
    {
        name: "Deal Failure Probability",
        category: "Risk Management",
        description: "Estimates the likelihood of a deal falling through based on risk indicators",
        formula: "Deal Failure Probability = 1 - (Due Diligence Score * Funding Score * Market Score)",
        variables: ["Due Diligence Score", "Funding Score", "Market Score"],
        target: "Below 20% failure probability for deal approval",
        tags: ["deal", "failure", "probability"],
    },
    // ===== SECTION 6: REVENUE INTELLIGENCE (176-200) =====
    {
        name: "Revenue Per Bot",
        category: "Revenue Intelligence",
        description: "Tracks revenue generation efficiency per AI agent",
        formula: "RPB = Total Revenue / Active Bots",
        variables: ["Total Revenue", "Active Bot Count"],
        target: "Increasing RPB indicates platform efficiency",
        tags: ["revenue", "bots", "efficiency"],
    },
    {
        name: "Churn Prediction Score",
        category: "Revenue Intelligence",
        description: "Predicts customer churn likelihood based on usage patterns",
        formula: "Score = (Login Frequency * 0.3) + (Feature Usage * 0.4) + (Support Tickets * -0.3)",
        variables: ["Login Frequency", "Feature Usage", "Support Tickets"],
        target: "Score < 40 = high churn risk, intervene immediately",
        tags: ["churn", "prediction", "retention"],
    },
    {
        name: "Dynamic Pricing Optimizer",
        category: "Revenue Intelligence",
        description: "Adjusts pricing based on demand, competition, and capacity",
        formula: "Optimal Price = Base Price * (1 + Demand Factor) * (1 - Competition Pressure)",
        variables: ["Base Price", "Demand Factor", "Competition Pressure"],
        target: "Maximize revenue while maintaining conversion",
        tags: ["pricing", "dynamic", "optimization"],
    },
    {
        name: "Revenue Leak Score",
        category: "Revenue Intelligence",
        description: "Identifies and quantifies revenue losses across the system",
        formula: "Leak Score = (Failed Transactions + Cart Abandonment + Pricing Errors) * Avg Order Value",
        variables: ["Failed Transactions", "Cart Abandonment Rate", "Pricing Errors", "Avg Order Value"],
        target: "Minimize leak score to zero",
        tags: ["leak", "revenue", "detection"],
    },
    {
        name: "Confidence Score",
        category: "Revenue Intelligence",
        description: "Aggregates multiple data signals to produce an overall deal confidence rating",
        formula: "Confidence Score = (Data Quality * 0.4) + (Historical Accuracy * 0.3) + (Market Signal * 0.3)",
        variables: ["Data Quality", "Historical Accuracy", "Market Signal"],
        target: "Above 80% confidence for automated deal execution",
        tags: ["confidence", "score", "reliability"],
    },
    {
        name: "Scenario ROI Delta",
        category: "Revenue Intelligence",
        description: "Compares ROI outcomes across different strategic scenarios",
        formula: "Scenario ROI Delta = Best Case ROI - Worst Case ROI",
        variables: ["Best Case ROI", "Worst Case ROI"],
        target: "Narrower delta = more predictable outcome",
        tags: ["scenario", "roi", "comparison"],
    },
    {
        name: "Competitive Threat Index",
        category: "Revenue Intelligence",
        description: "Quantifies competitive pressure from market entrants and incumbent actions",
        formula: "Competitive Threat Index = (New Entrants * 0.4) + (Price Wars * 0.3) + (Market Share Loss * 0.3)",
        variables: ["New Entrants", "Price Wars", "Market Share Loss"],
        target: "Below 5.0 for manageable competitive environment",
        tags: ["competitive", "threat", "market"],
    },
    {
        name: "Demand Elasticity",
        category: "Revenue Intelligence",
        description: "Measures how responsive customer demand is to changes in pricing or offers",
        formula: "Demand Elasticity = % Change in Quantity / % Change in Price",
        variables: ["% Change in Quantity", "% Change in Price"],
        target: "Inelastic demand (<1) supports premium pricing",
        tags: ["demand", "elasticity", "pricing"],
    },
    {
        name: "Opportunity Cost",
        category: "Revenue Intelligence",
        description: "Calculates the cost of choosing one investment over the next best alternative",
        formula: "Opportunity Cost = Return of Best Alternative - Return of Chosen Option",
        variables: ["Return of Best Alternative", "Return of Chosen Option"],
        target: "Minimize opportunity cost across portfolio decisions",
        tags: ["opportunity", "cost", "alternative"],
    },
    {
        name: "Efficiency Gap",
        category: "Revenue Intelligence",
        description: "Identifies the gap between current performance and optimal efficiency",
        formula: "Efficiency Gap = (Optimal Output - Actual Output) / Optimal Output * 100",
        variables: ["Optimal Output", "Actual Output"],
        target: "Below 10% gap for near-optimal operations",
        tags: ["efficiency", "gap", "optimization"],
    },
    {
        name: "Cost Optimization %",
        category: "Revenue Intelligence",
        description: "Tracks cost reduction achievements relative to baseline spending",
        formula: "Cost Optimization % = (Baseline Cost - Current Cost) / Baseline Cost * 100",
        variables: ["Baseline Cost", "Current Cost"],
        target: "10%+ annual cost optimization target",
        tags: ["cost", "optimization", "savings"],
    },
    {
        name: "Scaling Friction Index",
        category: "Revenue Intelligence",
        description: "Measures resistance to growth from operational bottlenecks and constraints",
        formula: "Scaling Friction Index = Cost Growth % / Revenue Growth %",
        variables: ["Cost Growth %", "Revenue Growth %"],
        target: "Below 1.0 indicates efficient scaling",
        tags: ["scaling", "friction", "growth"],
    },
    {
        name: "Automation Impact Score",
        category: "Revenue Intelligence",
        description: "Quantifies productivity gains from automation initiatives",
        formula: "Automation Impact Score = (Manual Hours Saved * Hourly Cost) / Automation Cost",
        variables: ["Manual Hours Saved", "Hourly Cost", "Automation Cost"],
        target: "Above 3.0 for justified automation investment",
        tags: ["automation", "impact", "productivity"],
    },
    {
        name: "Labor Dependency Ratio",
        category: "Revenue Intelligence",
        description: "Measures how dependent revenue is on manual labor versus automated systems",
        formula: "Labor Dependency Ratio = Labor Costs / Total Revenue * 100",
        variables: ["Labor Costs", "Total Revenue"],
        target: "Below 30% for scalable business model",
        tags: ["labor", "dependency", "scalability"],
    },
    {
        name: "Tech Leverage Multiplier",
        category: "Revenue Intelligence",
        description: "Calculates the revenue amplification effect of technology investments",
        formula: "Tech Leverage Multiplier = Revenue per Tech Dollar / Revenue per Labor Dollar",
        variables: ["Revenue per Tech Dollar", "Revenue per Labor Dollar"],
        target: "Above 5x for strong technology leverage",
        tags: ["technology", "leverage", "multiplier"],
    },
    {
        name: "Operational Margin",
        category: "Revenue Intelligence",
        description: "Measures profitability from core operations after all operating expenses",
        formula: "Operational Margin = (Operating Income / Revenue) * 100",
        variables: ["Operating Income", "Revenue"],
        target: "20%+ operational margin for healthy business",
        tags: ["operational", "margin", "profitability"],
    },
    {
        name: "Strategic Optionality Index",
        category: "Revenue Intelligence",
        description: "Values the strategic flexibility created by maintaining multiple growth paths",
        formula: "Strategic Optionality Index = Number of Viable Paths * Avg Path Value",
        variables: ["Number of Viable Paths", "Avg Path Value"],
        target: "Higher index = more strategic flexibility",
        tags: ["strategic", "optionality", "flexibility"],
    },
    {
        name: "Portfolio Resilience Score",
        category: "Revenue Intelligence",
        description: "Measures portfolio ability to withstand market shocks and recover",
        formula: "Portfolio Resilience Score = (Recovery Speed * 0.5) + (Diversification * 0.3) + (Cash Position * 0.2)",
        variables: ["Recovery Speed", "Diversification Score", "Cash Position"],
        target: "Above 7.0 for resilient portfolio positioning",
        tags: ["resilience", "portfolio", "stability"],
    },
    {
        name: "Diversification Spread",
        category: "Revenue Intelligence",
        description: "Measures the breadth of revenue sources across markets and products",
        formula: "Diversification Spread = 1 - HHI (Sum of Market Share Squares)",
        variables: ["Market Share per Segment"],
        target: "Above 0.7 for well-diversified revenue streams",
        tags: ["diversification", "spread", "revenue"],
    },
    {
        name: "Growth Sustainability Index",
        category: "Revenue Intelligence",
        description: "Evaluates whether current growth rate can be maintained long-term",
        formula: "Growth Sustainability Index = Retention Rate * ROE * Reinvestment Rate",
        variables: ["Retention Rate", "ROE", "Reinvestment Rate"],
        target: "Above 0.15 for sustainable growth trajectory",
        tags: ["growth", "sustainability", "index"],
    },
    {
        name: "Performance Momentum",
        category: "Revenue Intelligence",
        description: "Tracks acceleration or deceleration in key performance metrics",
        formula: "Performance Momentum = Current Period Growth - Prior Period Growth",
        variables: ["Current Period Growth", "Prior Period Growth"],
        target: "Positive momentum indicates accelerating performance",
        tags: ["momentum", "performance", "trend"],
    },
    {
        name: "Yield Compression Indicator",
        category: "Revenue Intelligence",
        description: "Detects declining yields that may signal market saturation or increased competition",
        formula: "Yield Compression Indicator = (Current Yield - Prior Yield) / Prior Yield * 100",
        variables: ["Current Yield", "Prior Yield"],
        target: "Negative trend requires strategic pivot evaluation",
        tags: ["yield", "compression", "warning"],
    },
    {
        name: "Competitive Advantage Score",
        category: "Revenue Intelligence",
        description: "Quantifies sustainable competitive advantages across key business dimensions",
        formula: "Competitive Advantage Score = (Market Share * 0.3) + (Brand Strength * 0.3) + (Cost Advantage * 0.2) + (Tech Moat * 0.2)",
        variables: ["Market Share", "Brand Strength", "Cost Advantage", "Tech Moat"],
        target: "Above 7.0 for durable competitive position",
        tags: ["competitive", "advantage", "moat"],
    },
    {
        name: "Innovation ROI",
        category: "Revenue Intelligence",
        description: "Measures return on investment in innovation and R&D initiatives",
        formula: "Innovation ROI = (Revenue from New Products / R&D Spend) * 100",
        variables: ["Revenue from New Products", "R&D Spend"],
        target: "200%+ ROI on innovation spend",
        tags: ["innovation", "roi", "research"],
    },
    {
        name: "Empire Expansion Rate",
        category: "Revenue Intelligence",
        description: "Tracks the overall growth rate of the business empire across all divisions",
        formula: "Empire Expansion Rate = (Total Value End - Total Value Start) / Total Value Start * 100",
        variables: ["Total Value End", "Total Value Start"],
        target: "25%+ annual expansion for aggressive growth",
        tags: ["empire", "expansion", "growth"],
    },
];
