const test=require('node:test'), assert=require('node:assert/strict');
const vm=require('node:vm'), fs=require('node:fs'), path=require('node:path');
const context={URL};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../website/buddy-knowledge-core.js'),'utf8'),context);
const {source,retrieve,compare}=context.BuddyKnowledge;
const note=()=>source('JavaScript arrays remove duplicates using new Set. Keep the first occurrence of each value.','Course notes','https://example.com/course',true);
test('authorized source produces cited retrieval and an actual before/after comparison',()=>{const s=note();assert.equal(retrieve([s],'How do arrays remove duplicates?')[0].label,'Course notes');const e=compare([],[s],'How do arrays remove duplicates?','new Set');assert.equal(e.baseline.passed,false);assert.equal(e.current.passed,true);assert.equal(e.improved,true);assert.equal(e.model_weights_changed,false);});
test('unrelated material and absent expected phrase cannot count as improvement',()=>{assert.equal(compare([],[note()],'astronomy planets orbit','new Set').current.passed,false);assert.equal(compare([],[note()],'arrays remove duplicates','invented answer').improved,false);assert.equal(compare([note()],[note()],'arrays remove duplicates','new Set').improved,false);});
test('permission, length, credentials and URL protocols are validated',()=>{for(const url of ['javascript:alert(1)','file:///tmp/a','https://user:pass@example.com'])assert.throws(()=>source('A sufficiently long source note.','a',url,true));assert.throws(()=>source('A sufficiently long source note.','a','',false));assert.throws(()=>source('short','a','',true));assert.throws(()=>source('x'.repeat(200001),'a','',true));assert.throws(()=>compare([],[],'a','b'));});
test('markup stays plain data and each chunk retains its citation',()=>{const s=source('<script>alert(1)</script> '+ 'arrays duplicate example '.repeat(200),'Markup','',true);assert.ok(s.chunks.length>1);assert.ok(retrieve([s],'arrays duplicate').every(r=>r.label==='Markup'));});
