import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {solveArmTarget} from '../website/invention-kinematics.js';
test('inverse kinematics reconstructs reachable targets',()=>{for(const [x,y,z] of [[2,1.4,1],[2,.22,1],[-1.9,2.2,-1.2],[-1.9,.35,-1.2],[0,3.2,0]]){const p=solveArmTarget(x,y,z);assert.ok(p);const r=2*Math.sin(p.shoulder)+2*Math.sin(p.shoulder+p.elbow),height=.65+2*Math.cos(p.shoulder)+2*Math.cos(p.shoulder+p.elbow);assert.ok(Math.abs(r*Math.cos(p.yaw)-x)<1e-8);assert.ok(Math.abs(-r*Math.sin(p.yaw)-z)<1e-8);assert.ok(Math.abs(height-y)<1e-8)}});
test('invalid and unreachable targets do not produce a pose',()=>{for(const t of [[9,9,9],[NaN,1,0],[0,.65,0]])assert.equal(solveArmTarget(...t),null)});
test('directory retains every pre-existing feature page',()=>{const actual=readdirSync(new URL('../website',import.meta.url)).filter(n=>n.endsWith('.html')&&!['index.html','404.html','command-center.html'].includes(n)).sort();const data=JSON.parse(readFileSync(new URL('../website/data/command-center-features.json',import.meta.url)));assert.deepEqual(data.features.map(x=>x.href).sort(),actual);assert.ok(data.features.every(x=>['user','owner'].includes(x.area)))});
test('search projection preserves every canonical bot and truthful readiness',()=>{const c=JSON.parse(readFileSync(new URL('../website/data/bot-fleet-catalog.json',import.meta.url))),d=JSON.parse(readFileSync(new URL('../website/data/command-center-catalog.json',import.meta.url)));assert.deepEqual(d.bots.map(b=>b.slug).sort(),c.bots.map(b=>b.identity.slug).sort());assert.deepEqual(d.summary,c.summary)});

import {questionsFor} from '../website/bot-intake-questions.js';
test('every source intake profile has 30 distinct contextual questions and its own page',()=>{const data=JSON.parse(readFileSync(new URL('../website/data/bot-intake-profiles.json',import.meta.url))),pages=readdirSync(new URL('../website/bot-pages',import.meta.url));assert.equal(new Set(data.profiles.map(p=>p.slug)).size,data.profiles.length);assert.deepEqual(pages.filter(p=>p.endsWith('.html')).sort(),data.profiles.map(p=>p.slug+'.html').sort());for(const p of data.profiles){const q=questionsFor(p);assert.equal(q.length,30,p.slug);assert.equal(new Set(q.map(q=>q.text)).size,30,p.slug);assert.ok(q.some(q=>q.text.includes(p.mission)));assert.ok(q.some(q=>q.text.includes(p.capabilities[0])));assert.ok(q.every(q=>q.id&&q.section));}});
test('every division profile has an intake page and registered routes match the fleet exactly',()=>{const data=JSON.parse(readFileSync(new URL('../website/data/bot-intake-profiles.json',import.meta.url))),slugs=new Set(data.profiles.map(p=>p.slug));for(const name of readdirSync(new URL('../App_bots',import.meta.url)).filter(n=>n.endsWith('.json'))){const d=JSON.parse(readFileSync(new URL('../App_bots/'+name,import.meta.url)));for(const b of d.bots||[])assert.ok(slugs.has(b.slug),b.slug)}const fleet=JSON.parse(readFileSync(new URL('../website/data/bot-fleet-catalog.json',import.meta.url)));assert.deepEqual(data.profiles.filter(p=>p.routeRegistered).map(p=>p.slug).sort(),fleet.bots.map(b=>b.identity.slug).sort());});
