export const CORE_OPERATIONAL_GROUPS = [
  {
    title: 'Deployment & Runtime',
    icon: '🚀',
    buttons: [
      'Deploy All Bots',
      'Deploy Selected Bot',
      'Restart All Services',
      'Restart Selected Bot',
      'Rollback Last Deployment',
      'Health Check All Bots',
      'Emergency Stop',
      'Safe Mode',
      'Scale Workers',
      'Container Status',
    ],
  },
  {
    title: 'AI Operations',
    icon: '🤖',
    buttons: [
      'Run Autonomous Task',
      'Start Agent Swarm',
      'Stop Agent Swarm',
      'Memory Sync',
      'Knowledge Refresh',
      'Model Update',
      'Agent Training',
      'Agent Evaluation',
      'Prompt Optimization',
      'Agent Diagnostics',
    ],
  },
  {
    title: 'Revenue Operations',
    icon: '💰',
    buttons: [
      'Revenue Dashboard',
      'Affiliate Earnings',
      'Product Sales',
      'Lead Generation',
      'Client Pipeline',
      'Invoice Generator',
      'Revenue Forecast',
      'Profit Analysis',
      'Marketing Campaigns',
      'ROI Calculator',
    ],
  },
  {
    title: 'Intelligence & Analytics',
    icon: '📊',
    buttons: [
      'Global Metrics',
      'Division Analytics',
      'User Activity',
      'Trend Detection',
      'Predictive Analytics',
      'Competitor Monitoring',
      'Market Scanner',
      'Opportunity Finder',
      'Risk Analysis',
      'Executive Dashboard',
    ],
  },
  {
    title: 'Division Management',
    icon: '🏢',
    buttons: [
      'View All Divisions',
      'Launch Division',
      'Create Division',
      'Division Health',
      'Division Revenue',
      'Division Tasks',
      'Division Staffing',
      'Division Automation',
      'Division Reports',
      'Division Leaderboard',
    ],
  },
  {
    title: 'Automation',
    icon: '🔄',
    buttons: [
      'Create Workflow',
      'Run Workflow',
      'Schedule Workflow',
      'Automation Builder',
      'Trigger Automation',
      'Workflow Monitor',
      'Automation Logs',
      'AI Workflow Generator',
      'Auto Fix Issues',
      'Auto Scale Infrastructure',
    ],
  },
  {
    title: 'Security',
    icon: '🔒',
    buttons: [
      'Security Dashboard',
      'Access Control',
      'Threat Detection',
      'Audit Logs',
      'API Key Manager',
      'Secrets Manager',
      'Vulnerability Scan',
      'Compliance Check',
      'Backup Systems',
      'Restore Systems',
    ],
  },
  {
    title: 'Development',
    icon: '🧪',
    buttons: [
      'GitHub Sync',
      'Pull Requests',
      'Repository Audit',
      'Test Suite',
      'Coverage Reports',
      'CI/CD Status',
      'Generate Code',
      'Code Review',
      'Bug Detection',
      'Release Manager',
    ],
  },
];

export const MUST_HAVE_BUTTONS = [
  'Empire Overview',
  'DreamCo Copilot',
  'Revenue Opportunities',
  'Auto CEO Briefing',
  'Swarm Builder',
  'Mission Control',
  'One Click Empire Sync',
  'AI Workforce Manager',
  'Autonomous Growth Mode',
  'Self-Heal System',
  'Opportunity Scanner',
  'Competitor Radar',
  'DreamOS Console',
  'Auto Builder',
  'Acquisition Finder',
  'Dream Browser',
  'Investor Mode',
  'War Room',
  'Future Forecast',
  'Launch Everything',
];

export const PINNED_TOP_ACTIONS = [
  'Launch Everything',
  'Mission Control',
  'DreamCo Copilot',
  'Empire Overview',
];

export const SIDEBAR_STRUCTURE = [
  '🏠 Home',
  '🤖 Bots',
  '🧠 AI Swarms',
  '💰 Revenue',
  '📊 Analytics',
  '🏢 Divisions',
  '🔄 Automation',
  '🧪 Development',
  '🔒 Security',
  '🌐 Dream Browser',
  '🚀 Mission Control',
  '⚙️ Settings',
];
