import { useMemo, useState } from "react";
import { Link } from "wouter";
import AppShell from "@/components/AppShell";
import Seo from "@/components/Seo";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { Activity, ArrowRight, CheckCircle2, ChevronDown, FlaskConical, Play, ShieldCheck, Search, Wrench, RefreshCw, PackageCheck, Gauge, ClipboardCheck } from "lucide-react";

const suggestions: Record<string, string[]> = {
  doctor: ["Check Node and Python runtime versions","Check package-lock and dependency consistency","Check required environment variables without exposing values","Check database connectivity configuration","Check filesystem permissions","Check required directories and generated assets","Check API route registration","Check health and readiness endpoints","Check worker and queue configuration","Check GitHub integration configuration","Check model and provider configuration","Check stale generated catalogs","Check duplicate module identifiers","Check missing module dependencies","Check invalid capability metadata","Check workflow configuration consistency","Check deployment configuration drift","Check port and host configuration","Produce a dependency and root-cause graph","Create a machine-readable doctor report"],
  test: ["Run fast unit-test suite","Run Actions-page tests","Run dynamic-fleet tests","Run Superbot routing tests","Run questionnaire tests","Run custom-page tests","Run integration tests","Run API contract tests","Run database tests against an isolated database","Run authentication and authorization tests","Run external-integration mocks","Run regression tests for every repaired defect","Run failure-path tests","Run concurrency tests","Run timeout and retry tests","Run serialization and schema tests","Run production-build smoke tests","Preserve the first reproducible failure with logs","Generate a test evidence manifest","Gate promotion on applicable passing evidence"],
  lint: ["Run TypeScript compiler checks","Run JavaScript and TypeScript lint rules","Run Python lint checks","Run formatting checks","Detect unused imports","Detect unreachable code","Detect unsafe any usage where configured","Detect duplicate configuration keys","Detect dead workflow references","Detect missing type declarations","Detect inconsistent module exports","Detect invalid JSON and YAML","Detect circular dependency candidates","Detect hard-coded fleet ceilings","Detect hard-coded credential patterns","Detect client-side secret references","Detect missing error handling","Detect unsafe console logging","Generate a static-quality report","Fail CI on configured blocking rules"],
  security: ["Scan dependencies for known vulnerabilities","Scan repository for committed secrets","Check authentication boundaries","Check authorization on privileged Actions","Check API input validation","Check output encoding","Check session configuration","Check CSRF protections where applicable","Check CORS policy","Check webhook signature validation","Check rate-limit configuration","Check upload and file handling","Check path-traversal defenses","Check command-execution boundaries","Check SSRF defenses","Check sensitive logging","Check dependency provenance","Check production environment separation","Run a least-privilege configuration audit","Block promotion on unresolved critical findings"],
  benchmark: ["Benchmark Actions-page load time","Benchmark Buddy routing latency","Benchmark module discovery throughput","Benchmark Superbot route selection","Benchmark questionnaire planning","Benchmark API response latency","Benchmark database query latency","Benchmark cache hit rate","Benchmark queue throughput","Benchmark concurrent requests","Benchmark memory usage","Benchmark CPU utilization","Benchmark startup time","Benchmark cold-start behavior","Benchmark failure-recovery time","Benchmark model and provider routing latency","Benchmark custom-page generation","Compare before and after optimization results","Store reproducible benchmark inputs","Reject fabricated or non-reproducible benchmark scores"],
  repair: ["Capture the smallest reproducible failure","Identify the first failing dependency","Group related failures by root cause","Check recent commits for regression source","Compare working and failing configurations","Create a minimal repair plan","Prefer shared fixes over duplicated patches","Add a regression test before closing a defect","Validate rollback behavior","Validate fallback behavior","Quarantine failed modules where appropriate","Verify repaired routes","Verify repaired Actions","Verify repaired database migrations","Verify repaired integrations","Check for collateral regressions","Record changed files and rationale","Record evidence before marking repaired","Re-run dependent checks","Require explicit evidence before declaring the repair complete"],
  pages: ["Verify every Actions control has a visible card","Verify every Action has a usable status","Verify prospectus data reaches the UI","Verify suggestion data reaches each Action","Verify Action buttons map to stable IDs","Verify loading states","Verify failure states","Verify blocked states","Verify evidence links","Verify timestamps are displayed","Verify stale data is marked","Verify route and capability results render","Verify custom-page capability results render","Verify mobile layout","Verify keyboard accessibility","Verify screen-reader labels","Verify no secrets appear in page data","Verify dashboard metrics against source evidence","Verify production deployment renders the same registry","Run an end-to-end Pages smoke test"],
  bundle: ["Build the documented local runtime","Validate package metadata","Validate installation instructions","Run clean-install smoke test","Run launch smoke test","Run local health check","Verify required permissions","Verify local configuration validation","Verify safe offline behavior","Verify local Actions execution boundaries","Verify logs do not expose secrets","Verify uninstall and cleanup behavior","Verify macOS package path","Verify Linux package path","Verify Windows package path when supported","Verify version reporting","Verify checksum and provenance metadata","Verify upgrade path","Verify rollback path","Publish only artifacts that passed smoke tests"],
  refresh: ["Fetch current workflow run status","Associate runs with commit SHAs","Detect stale run data","Detect missing workflow evidence","Refresh Action status cards","Refresh benchmark evidence","Refresh test evidence","Refresh security evidence","Refresh deployment evidence","Refresh module counts","Refresh Superbot health","Refresh capability availability","Refresh custom-page catalog data","Record refresh timestamp","Handle GitHub API rate limits","Handle partial API failures","Preserve last-known-good evidence","Mark live state unavailable instead of guessing","Compare current and previous snapshots","Expose refresh provenance"],
  production_readiness: ["Run the complete build gate","Run the complete test gate","Run static quality gates","Run security gates","Verify required environment configuration","Verify database migration state","Verify backup and recovery readiness","Verify runtime health endpoints","Verify observability and request correlation","Verify timeout, retry, and backpressure policies","Verify dynamic fleet discovery","Verify Superbot routing evidence","Verify all ten Actions are wired","Verify custom-page questionnaire flow","Verify privileged Action authorization","Verify production deployment smoke test","Verify rollback procedure","Verify critical user journeys","Generate a release evidence manifest","Only mark production-ready when all applicable gates have evidence"]
};

const controls = [
  { id: "doctor", name: "Run Doctor", icon: Activity, category: "Diagnostics", purpose: "Find repository, runtime, dependency, configuration, and connection problems." },
  { id: "test", name: "Run Tests", icon: FlaskConical, category: "Quality", purpose: "Execute the test system and preserve reproducible failures." },
  { id: "lint", name: "Run Lint", icon: ClipboardCheck, category: "Engineering", purpose: "Check formatting, imports, types, static quality, and architectural rules." },
  { id: "security", name: "Security Check", icon: ShieldCheck, category: "Security", purpose: "Check secrets, dependencies, permissions, boundaries, and supply-chain risk." },
  { id: "benchmark", name: "Benchmark Locally", icon: Gauge, category: "Performance", purpose: "Measure quality, latency, throughput, efficiency, and reproducibility." },
  { id: "repair", name: "Find Repair Plan", icon: Wrench, category: "Remediation", purpose: "Turn failures into the smallest safe repair plus regression evidence." },
  { id: "pages", name: "Verify Pages Data", icon: Search, category: "Transparency", purpose: "Verify repository evidence and Action state reach the dashboard." },
  { id: "bundle", name: "Prepare Device Bundle", icon: PackageCheck, category: "Distribution", purpose: "Validate reproducible local Buddy packages and their permission boundaries." },
  { id: "refresh", name: "Refresh GitHub Runs", icon: RefreshCw, category: "Observability", purpose: "Refresh timestamped workflow evidence and detect stale state." },
  { id: "production_readiness", name: "Production Readiness", icon: CheckCircle2, category: "Release", purpose: "Run the evidence gate before declaring DreamCo production-ready." }
] as const;

export default function ActionsControlPage() {
  const [open, setOpen] = useState<string | null>("production_readiness");
  const [filter, setFilter] = useState("");
  const filtered = useMemo(() => controls.filter(c => !filter || `${c.name} ${c.category} ${c.purpose}`.toLowerCase().includes(filter.toLowerCase())), [filter]);
  return <AppShell>
    <Seo title="Actions Control Center — DreamCo" description="Ten stable DreamCo Actions with evidence-driven execution plans and 200 upgrade suggestions." />
    <div className="space-y-6 buddy-appear">
      <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4">
        <div><Badge className="mb-2 bg-primary/15 text-primary border-primary/30">CONTROL PLANE</Badge><h1 className="text-3xl md:text-4xl font-black">Actions Control Center</h1><p className="text-muted-foreground mt-2 max-w-3xl">These are the ten stable Actions. Each exposes twenty concrete verification and upgrade suggestions. Suggestions are not evidence until executed.</p></div>
        <div className="flex gap-2"><Link href="/actions"><Button variant="outline" className="rounded-xl">Existing Workspace <ArrowRight className="h-4 w-4" /></Button></Link><Link href="/harness"><Button className="rounded-xl"><Play className="h-4 w-4" /> Test Harness</Button></Link></div>
      </div>
      <div className="flex items-center gap-3"><div className="relative flex-1 max-w-xl"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground"/><input value={filter} onChange={e => setFilter(e.target.value)} placeholder="Find an Action..." className="w-full h-10 rounded-xl border border-border bg-card px-9 text-sm outline-none focus:ring-2 focus:ring-primary/30" data-testid="actions-control-search" /></div><Badge variant="outline">{controls.length} Actions · 200 suggestions</Badge></div>
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4" data-testid="actions-control-grid">
        {filtered.map(control => { const Icon = control.icon; const items = suggestions[control.id]; const expanded = open === control.id; return <Card key={control.id} className={cn("rounded-2xl border border-border/60 overflow-hidden", expanded && "border-primary/40 shadow-md")} data-testid={`action-control-${control.id}`}>
          <button className="w-full text-left p-5" onClick={() => setOpen(expanded ? null : control.id)} aria-expanded={expanded} data-testid={`action-toggle-${control.id}`}>
            <div className="flex items-start gap-3"><span className="h-10 w-10 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center text-primary"><Icon className="h-5 w-5" /></span><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><h2 className="font-bold">{control.name}</h2><Badge variant="outline" className="text-[10px]">{control.category}</Badge><Badge className="text-[10px] bg-muted text-muted-foreground border-border">20 suggestions</Badge></div><p className="text-xs text-muted-foreground mt-1">{control.purpose}</p></div><ChevronDown className={cn("h-5 w-5 transition-transform", expanded && "rotate-180")} /></div>
          </button>
          {expanded && <div className="border-t border-border/60 p-5 space-y-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Verification / upgrade queue</p><Link href="/harness"><Button size="sm" className="rounded-lg"><Play className="h-3.5 w-3.5" /> Open Harness</Button></Link></div><ol className="space-y-1.5">{items.map((item, i) => <li key={item} className="flex items-start gap-2 rounded-lg border border-border/40 bg-muted/20 p-2.5"><span className="text-[10px] font-mono text-muted-foreground w-5 pt-0.5">{String(i + 1).padStart(2, "0")}</span><span className="text-xs leading-relaxed">{item}</span></li>)}</ol><p className="text-[10px] text-muted-foreground pt-1">Status rule: discovered → configured → executed → verified → regressed → mastered, or blocked when evidence/dependencies are missing.</p></div>}
        </Card> })}
      </div>
    </div>
  </AppShell>;
}
