"""
DreamCo Platform — OpenRouter Adapter
======================================

``OpenRouterAdapter`` wraps the OpenRouter HTTP API
(https://openrouter.ai/api/v1/chat/completions) so that every downstream
component can call any model through a single interface without being
coupled to individual provider SDKs.

Design
------
* Requests are expressed as ``OpenRouterRequest`` dataclasses.
* Responses are normalised into ``OpenRouterResponse`` so callers are
  insulated from raw HTTP payloads.
* When no live API key is configured the adapter runs in **stub mode**,
  returning a deterministic synthetic response.  This allows the full
  pipeline to operate end-to-end in CI without external credentials.
* The adapter is intentionally synchronous so it can be run inside
  asyncio tasks, thread pools, or plain Python threads without friction.
"""

from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import Any


# ---------------------------------------------------------------------------
# Request / Response types
# ---------------------------------------------------------------------------

@dataclass
class OpenRouterRequest:
    """
    A normalised request destined for the OpenRouter chat completions API.

    Attributes
    ----------
    model : str
        OpenRouter model identifier, e.g. ``"openai/gpt-4o"`` or
        ``"anthropic/claude-3-5-sonnet"``.
    messages : list[dict]
        Chat messages in OpenAI format
        ``[{"role": "user", "content": "…"}, …]``.
    temperature : float
        Sampling temperature (0.0 – 2.0).
    max_tokens : int
        Maximum tokens to generate.
    metadata : dict
        Arbitrary extra parameters forwarded to the API verbatim.
    """

    model: str
    messages: list[dict[str, str]]
    temperature: float = 0.7
    max_tokens: int = 1024
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_payload(self) -> dict[str, Any]:
        """Serialise to the OpenRouter API request body."""
        payload: dict[str, Any] = {
            "model": self.model,
            "messages": self.messages,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }
        payload.update(self.metadata)
        return payload


@dataclass
class OpenRouterResponse:
    """
    Normalised response from the OpenRouter API (or stub).

    Attributes
    ----------
    model : str
        The model that produced the response.
    content : str
        The generated text content.
    finish_reason : str
        Why generation stopped (``"stop"`` | ``"length"`` | ``"error"``).
    prompt_tokens : int
    completion_tokens : int
    total_tokens : int
    latency_ms : float
        Wall-clock time for the API call in milliseconds.
    raw : dict
        The raw API response dict (empty in stub mode).
    stub : bool
        ``True`` when this response was generated by the local stub.
    """

    model: str
    content: str
    finish_reason: str = "stop"
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    latency_ms: float = 0.0
    raw: dict[str, Any] = field(default_factory=dict)
    stub: bool = False

    @property
    def cost_usd(self) -> float:
        """Approximate cost based on a generic $1/M token rate."""
        return round(self.total_tokens / 1_000_000, 6)


# ---------------------------------------------------------------------------
# OpenRouterAdapter
# ---------------------------------------------------------------------------

_OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
_DEFAULT_TIMEOUT = 30  # seconds


class OpenRouterAdapter:
    """
    HTTP adapter for the OpenRouter API.

    Parameters
    ----------
    api_key : str | None
        OpenRouter API key.  Falls back to ``OPENROUTER_API_KEY`` env var.
        When neither is set the adapter operates in **stub mode**.
    base_url : str
        API base URL.  Override for self-hosted or mock endpoints.
    timeout : int
        Request timeout in seconds.
    site_url : str
        Value sent as ``HTTP-Referer`` (required by OpenRouter TOS).
    app_name : str
        Value sent as ``X-Title`` for request attribution.
    """

    def __init__(
        self,
        api_key: str | None = None,
        base_url: str = _OPENROUTER_URL,
        timeout: int = _DEFAULT_TIMEOUT,
        site_url: str = "https://dreamco.ai",
        app_name: str = "DreamCobots",
    ) -> None:
        self._api_key = api_key or os.environ.get("OPENROUTER_API_KEY", "")
        self._base_url = base_url
        self._timeout = timeout
        self._site_url = site_url
        self._app_name = app_name

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    @property
    def stub_mode(self) -> bool:
        """``True`` when no API key is configured."""
        return not bool(self._api_key)

    def complete(self, request: OpenRouterRequest) -> OpenRouterResponse:
        """
        Send *request* to the OpenRouter API and return a normalised response.

        Falls back to ``_stub_response`` when in stub mode.

        Parameters
        ----------
        request : OpenRouterRequest

        Returns
        -------
        OpenRouterResponse
        """
        if self.stub_mode:
            return self._stub_response(request)
        return self._http_complete(request)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _http_complete(self, request: OpenRouterRequest) -> OpenRouterResponse:
        """Make a live HTTP call to the OpenRouter API."""
        payload = json.dumps(request.to_payload()).encode("utf-8")
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self._api_key}",
            "HTTP-Referer": self._site_url,
            "X-Title": self._app_name,
        }
        req = urllib.request.Request(
            self._base_url,
            data=payload,
            headers=headers,
            method="POST",
        )
        t0 = time.monotonic()
        try:
            with urllib.request.urlopen(req, timeout=self._timeout) as resp:
                raw: dict[str, Any] = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(
                f"OpenRouter HTTP {exc.code}: {body}"
            ) from exc
        except urllib.error.URLError as exc:
            raise RuntimeError(f"OpenRouter connection error: {exc.reason}") from exc
        latency_ms = (time.monotonic() - t0) * 1000

        choice = raw.get("choices", [{}])[0]
        message = choice.get("message", {})
        usage = raw.get("usage", {})
        return OpenRouterResponse(
            model=raw.get("model", request.model),
            content=message.get("content", ""),
            finish_reason=choice.get("finish_reason", "stop"),
            prompt_tokens=usage.get("prompt_tokens", 0),
            completion_tokens=usage.get("completion_tokens", 0),
            total_tokens=usage.get("total_tokens", 0),
            latency_ms=latency_ms,
            raw=raw,
            stub=False,
        )

    def _stub_response(self, request: OpenRouterRequest) -> OpenRouterResponse:
        """Return a deterministic synthetic response (no API call)."""
        user_content = next(
            (m.get("content", "") for m in request.messages if m.get("role") == "user"),
            "",
        )
        content = f"[STUB:{request.model}] {user_content}"
        return OpenRouterResponse(
            model=request.model,
            content=content,
            finish_reason="stop",
            prompt_tokens=len(user_content.split()),
            completion_tokens=len(content.split()),
            total_tokens=len(user_content.split()) + len(content.split()),
            latency_ms=0.0,
            raw={},
            stub=True,
        )
