from __future__ import annotations

from typing import Any, Protocol

from framework import GlobalAISourcesFlow  # noqa: F401


class QueueBackend(Protocol):
    max_depth: int

    def enqueue(self, job_id: str, *, priority: Any, tier: str = "free") -> None: ...

    def dequeue(self, *, worker_id: str, lease_seconds: int = 60) -> str | None: ...

    def ack(self, job_id: str) -> None: ...

    def retry(self, job_id: str, *, reason: str | None = None, delay_seconds: float = 0.0) -> None: ...

    def dead_letter(self, job_id: str, *, reason: str | None = None) -> None: ...

    def cancel(self, job_id: str, *, reason: str = "user_cancelled") -> bool: ...

    def recover_stalled(self, *, stall_after_seconds: int = 120) -> int: ...

    def snapshot(self) -> dict[str, Any]: ...
