"""
DreamCo Platform — Dream Memory Layer
======================================

The Dream Memory Layer is DreamCo's intelligence moat.  It persists
the **operational graph data** generated by every bot, workflow, and
capability execution:

* decisions made
* outcomes observed
* profitability by workflow path
* retry histories
* learning signals
* anomaly detections
* operational telemetry

Over time this data becomes the foundation for:

* adaptive optimisation (know which paths outperform)
* temporal reconstruction (replay past decisions)
* autonomous governance (detect drift automatically)
* Dream Brain ingestion (feed structured intelligence into the brain)

Design
------
``DreamMemory`` is intentionally kept in-memory for development.  Swap the
``_store`` for a database-backed store (PostgreSQL, Firestore, Redis) in
production without changing the interface.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional


# ---------------------------------------------------------------------------
# Memory types
# ---------------------------------------------------------------------------

class MemoryType(str, Enum):
    DECISION = "decision"          # A decision was made (with reasoning)
    OUTCOME = "outcome"            # The result of an action / workflow
    PROFITABILITY = "profitability"  # Revenue / cost observation
    RETRY = "retry"                # A retry event and its outcome
    LEARNING_SIGNAL = "learning_signal"  # A learning cycle observation
    ANOMALY = "anomaly"            # An anomalous pattern detected
    WORKFLOW_PATH = "workflow_path"  # Which execution path was taken
    TELEMETRY = "telemetry"        # Raw operational telemetry


# ---------------------------------------------------------------------------
# Memory entry
# ---------------------------------------------------------------------------

@dataclass
class MemoryEntry:
    """
    A single item stored in the Dream Memory Layer.

    Attributes
    ----------
    memory_id : str
        Unique identifier.
    memory_type : MemoryType
        Classification of this memory record.
    source : str
        Emitting component (bot_id, orchestrator name, workflow_id, etc.).
    subject : str
        The entity this memory is about (bot_id, workflow_id, capability_id).
    data : dict
        The structured payload of this memory.
    tags : list[str]
        Searchable labels.
    timestamp : float
        Unix timestamp when this memory was recorded.
    correlation_id : str | None
        Links this memory to a larger operation trace.
    profitability_usd : float | None
        Monetary outcome if applicable.
    importance : float
        Salience score 0.0 – 1.0 (used for memory pruning / prioritisation).
    metadata : dict
        Arbitrary extra metadata.
    """

    memory_type: MemoryType
    source: str
    subject: str
    data: Dict[str, Any] = field(default_factory=dict)
    tags: List[str] = field(default_factory=list)
    memory_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=time.time)
    correlation_id: Optional[str] = None
    profitability_usd: Optional[float] = None
    importance: float = 0.5
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "memory_id": self.memory_id,
            "memory_type": self.memory_type.value,
            "source": self.source,
            "subject": self.subject,
            "data": self.data,
            "tags": list(self.tags),
            "timestamp": self.timestamp,
            "correlation_id": self.correlation_id,
            "profitability_usd": self.profitability_usd,
            "importance": self.importance,
            "metadata": dict(self.metadata),
        }

    def __repr__(self) -> str:
        return (
            f"MemoryEntry(id={self.memory_id[:8]}..., "
            f"type={self.memory_type.value!r}, subject={self.subject!r})"
        )


# ---------------------------------------------------------------------------
# Dream Memory store
# ---------------------------------------------------------------------------

class DreamMemory:
    """
    In-memory operational graph data store.

    Provides indexed lookup by source, subject, memory type, tags, and
    correlation ID.  Includes summarisation helpers for Dream Brain ingestion.

    Parameters
    ----------
    max_entries : int
        Maximum number of entries to retain before the oldest are pruned.
        Set to 0 for unlimited. Default: 100_000.
    """

    def __init__(self, max_entries: int = 100_000) -> None:
        self._store: List[MemoryEntry] = []
        self._max_entries = max_entries

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def record(self, entry: MemoryEntry) -> MemoryEntry:
        """
        Store *entry* in memory.

        If ``max_entries`` is exceeded, the lowest-importance entry older
        than the median timestamp is pruned first.

        Returns the stored entry (identity, not a copy).
        """
        self._store.append(entry)
        if self._max_entries > 0 and len(self._store) > self._max_entries:
            self._prune_one()
        return entry

    def record_decision(
        self,
        source: str,
        subject: str,
        decision: str,
        reasoning: str = "",
        *,
        correlation_id: str | None = None,
        importance: float = 0.5,
        extra: Dict[str, Any] | None = None,
    ) -> MemoryEntry:
        """Convenience method for recording a decision."""
        return self.record(MemoryEntry(
            memory_type=MemoryType.DECISION,
            source=source,
            subject=subject,
            data={"decision": decision, "reasoning": reasoning, **(extra or {})},
            correlation_id=correlation_id,
            importance=importance,
        ))

    def record_outcome(
        self,
        source: str,
        subject: str,
        success: bool,
        profitability_usd: float | None = None,
        *,
        correlation_id: str | None = None,
        importance: float = 0.5,
        extra: Dict[str, Any] | None = None,
    ) -> MemoryEntry:
        """Convenience method for recording an outcome."""
        return self.record(MemoryEntry(
            memory_type=MemoryType.OUTCOME,
            source=source,
            subject=subject,
            data={"success": success, **(extra or {})},
            correlation_id=correlation_id,
            profitability_usd=profitability_usd,
            importance=importance,
        ))

    def record_retry(
        self,
        source: str,
        subject: str,
        attempt: int,
        reason: str,
        *,
        correlation_id: str | None = None,
    ) -> MemoryEntry:
        """Convenience method for recording a retry event."""
        return self.record(MemoryEntry(
            memory_type=MemoryType.RETRY,
            source=source,
            subject=subject,
            data={"attempt": attempt, "reason": reason},
            correlation_id=correlation_id,
            importance=0.3,
        ))

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def get(self, memory_id: str) -> Optional[MemoryEntry]:
        """Return the entry with *memory_id*, or ``None``."""
        for entry in self._store:
            if entry.memory_id == memory_id:
                return entry
        return None

    def query(
        self,
        *,
        source: str | None = None,
        subject: str | None = None,
        memory_type: MemoryType | None = None,
        tag: str | None = None,
        correlation_id: str | None = None,
        since: float | None = None,
        predicate: Callable[[MemoryEntry], bool] | None = None,
        limit: int | None = None,
    ) -> List[MemoryEntry]:
        """
        Flexible query over all stored memory entries.

        All supplied filters are applied with AND logic.  Results are
        returned in reverse-chronological order (newest first).

        Parameters
        ----------
        source : str | None
            Filter by emitting source.
        subject : str | None
            Filter by subject entity.
        memory_type : MemoryType | None
            Filter by memory type.
        tag : str | None
            Filter to entries containing *tag*.
        correlation_id : str | None
            Filter by correlation ID.
        since : float | None
            Include only entries with ``timestamp >= since``.
        predicate : callable | None
            Custom filter function ``(MemoryEntry) -> bool``.
        limit : int | None
            Maximum number of results.
        """
        results = list(self._store)

        if source is not None:
            results = [e for e in results if e.source == source]
        if subject is not None:
            results = [e for e in results if e.subject == subject]
        if memory_type is not None:
            results = [e for e in results if e.memory_type == memory_type]
        if tag is not None:
            results = [e for e in results if tag in e.tags]
        if correlation_id is not None:
            results = [e for e in results if e.correlation_id == correlation_id]
        if since is not None:
            results = [e for e in results if e.timestamp >= since]
        if predicate is not None:
            results = [e for e in results if predicate(e)]

        results.sort(key=lambda e: e.timestamp, reverse=True)
        if limit is not None:
            results = results[:limit]
        return results

    def query_by_bot(self, bot_id: str, **kwargs: Any) -> List[MemoryEntry]:
        """Return all entries related to *bot_id* (source or subject)."""
        return self.query(
            predicate=lambda e: e.source == bot_id or e.subject == bot_id,
            **kwargs,
        )

    def query_by_workflow(self, workflow_id: str, **kwargs: Any) -> List[MemoryEntry]:
        """Return all entries for *workflow_id*."""
        return self.query(subject=workflow_id, **kwargs)

    # ------------------------------------------------------------------
    # Summarisation
    # ------------------------------------------------------------------

    def summarize(self) -> Dict[str, Any]:
        """
        Return aggregate statistics over all stored entries.

        Used by Dream Brain ingestion to ingest a structured intelligence
        snapshot.
        """
        if not self._store:
            return {
                "total_entries": 0,
                "by_type": {},
                "total_profitability_usd": 0.0,
                "avg_importance": 0.0,
                "oldest_timestamp": None,
                "newest_timestamp": None,
            }

        by_type: Dict[str, int] = {}
        total_profit = 0.0
        total_importance = 0.0

        for entry in self._store:
            key = entry.memory_type.value
            by_type[key] = by_type.get(key, 0) + 1
            if entry.profitability_usd is not None:
                total_profit += entry.profitability_usd
            total_importance += entry.importance

        timestamps = [e.timestamp for e in self._store]
        return {
            "total_entries": len(self._store),
            "by_type": by_type,
            "total_profitability_usd": round(total_profit, 4),
            "avg_importance": round(total_importance / len(self._store), 4),
            "oldest_timestamp": min(timestamps),
            "newest_timestamp": max(timestamps),
        }

    # ------------------------------------------------------------------
    # Maintenance
    # ------------------------------------------------------------------

    def clear(self) -> None:
        """Remove all stored entries."""
        self._store.clear()

    def __len__(self) -> int:
        return len(self._store)

    def __repr__(self) -> str:
        return f"DreamMemory({len(self._store)} entries)"

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _prune_one(self) -> None:
        """Remove the least-important oldest entry."""
        if not self._store:
            return
        # Find entry with minimum importance, break ties by oldest timestamp
        victim = min(self._store, key=lambda e: (e.importance, -e.timestamp))
        self._store.remove(victim)
