export type DivisionDomainProfile = {
  purpose: string;
  serves: string[];
  outcome: string;
  boundary: string;
  focusAreas: string[];
};

export const DIVISION_DOMAIN_PROFILES: Record<string, DivisionDomainProfile> = {
  CommandCore: {
    purpose: "Coordinate Buddy, specialist routing, approvals, memory, evidence, and system health across the full platform.",
    serves: ["owners", "operators", "client administrators"],
    outcome: "A single accountable command path from user intent to reviewable work and measured results.",
    boundary: "CommandCore cannot override consent, professional review, spending approval, or the kill switch.",
    focusAreas: ["orchestration", "approvals", "memory governance", "task routing", "system health"],
  },
  DreamAIInfra: {
    purpose: "Design and operate model routing, inference, evaluation, compute, storage, and observability infrastructure.",
    serves: ["AI engineers", "platform teams", "model operators"],
    outcome: "Reliable, measurable AI infrastructure that can prefer local and low-cost routes without hiding quality tradeoffs.",
    boundary: "Model access, weights, licenses, data rights, and production releases require verified evidence.",
    focusAreas: ["model serving", "compute scheduling", "evaluation infrastructure", "observability", "capacity planning"],
  },
  DreamAdmin: {
    purpose: "Reduce administrative work through organized scheduling, records, correspondence, and operating procedures.",
    serves: ["individuals", "office teams", "executive assistants"],
    outcome: "Fewer missed obligations and faster completion of routine administrative work.",
    boundary: "Buddy prepares and coordinates; identity, signatures, submissions, and account changes require the user.",
    focusAreas: ["calendar operations", "document organization", "meeting support", "records management", "office workflows"],
  },
  DreamAgents: {
    purpose: "Build, test, govern, and coordinate reusable AI agents and specialist worker teams.",
    serves: ["agent builders", "business operators", "automation teams"],
    outcome: "Agents with explicit tools, scopes, tests, owners, and failure handling instead of unbounded autonomy.",
    boundary: "Agents cannot grant themselves permissions, deploy themselves, spend, or bypass review gates.",
    focusAreas: ["agent design", "tool contracts", "multi-agent routing", "agent evaluation", "permission governance"],
  },
  DreamAgriculture: {
    purpose: "Support farm planning, crop intelligence, livestock operations, equipment use, and agricultural business decisions.",
    serves: ["farmers", "growers", "agricultural operators"],
    outcome: "Better production decisions, lower waste, and clearer operational evidence.",
    boundary: "Physical, chemical, veterinary, and regulated decisions remain with qualified people and official guidance.",
    focusAreas: ["crop planning", "soil and weather evidence", "livestock operations", "farm equipment", "agricultural markets"],
  },
  DreamArts: {
    purpose: "Help creators plan, produce, document, license, present, and sell original visual and performing arts.",
    serves: ["artists", "studios", "galleries"],
    outcome: "Professional creative projects with clear provenance, rights, production steps, and audience paths.",
    boundary: "Real-person likenesses, protected works, and commercial assets require documented rights and consent.",
    focusAreas: ["creative direction", "visual production", "performance planning", "portfolio management", "rights and licensing"],
  },
  DreamAutomation: {
    purpose: "Turn repeatable work into observable workflows with connectors, retries, approvals, and rollback paths.",
    serves: ["operations teams", "business owners", "integration engineers"],
    outcome: "Reliable automation that saves time while keeping consequential actions reviewable.",
    boundary: "No workflow may silently expand scopes, expose credentials, spend, publish, or contact people.",
    focusAreas: ["workflow design", "API orchestration", "event processing", "failure recovery", "automation monitoring"],
  },
  DreamBizLaunch: {
    purpose: "Guide founders from validated problem through business setup, offer design, operations, and launch readiness.",
    serves: ["founders", "small businesses", "entrepreneurs"],
    outcome: "A documented, testable business launch packet with realistic costs, risks, and next actions.",
    boundary: "Official registration, legal conclusions, banking, credit, and purchases require the owner and qualified providers.",
    focusAreas: ["problem validation", "business model", "launch operations", "registration preparation", "go-to-market planning"],
  },
  DreamCodeLab: {
    purpose: "Plan, write, test, debug, secure, document, and ship software through reviewable repository workflows.",
    serves: ["learners", "developers", "product teams"],
    outcome: "Working software changes with reproducible tests, clear diffs, rollback, and deployment evidence.",
    boundary: "Generated code stays in sandboxes or review branches until tests and owner approval pass.",
    focusAreas: ["software architecture", "implementation", "debugging", "quality assurance", "deployment engineering"],
  },
  DreamConstruction: {
    purpose: "Support estimating, scheduling, procurement, documentation, safety planning, and project controls.",
    serves: ["contractors", "project managers", "property owners"],
    outcome: "Construction decisions backed by current scope, cost, schedule, and evidence.",
    boundary: "Licensed design, permits, inspections, safety authority, and physical work remain human-controlled.",
    focusAreas: ["estimating", "project scheduling", "procurement", "site documentation", "quality and safety planning"],
  },
  DreamContent: {
    purpose: "Create and manage useful written, visual, audio, and video content across governed production workflows.",
    serves: ["creators", "marketing teams", "educators"],
    outcome: "Audience-ready content with briefs, rights, versions, accessibility, and performance evidence.",
    boundary: "Content may not impersonate people, misrepresent evidence, violate rights, or publish without approval.",
    focusAreas: ["content strategy", "writing", "audio production", "video production", "content distribution"],
  },
  DreamCrypto: {
    purpose: "Provide education, market analysis, testnet design, custody planning, and risk-aware digital asset tooling.",
    serves: ["learners", "developers", "authorized asset owners"],
    outcome: "Clear digital-asset decisions with custody boundaries, simulations, and auditable risk disclosures.",
    boundary: "Buddy never holds private keys, promises returns, mines without authorization, or signs transactions autonomously.",
    focusAreas: ["market research", "wallet safety", "testnet engineering", "transaction analysis", "digital asset education"],
  },
  DreamCustIntel: {
    purpose: "Turn consented customer evidence into service improvements, segmentation, retention, and product insight.",
    serves: ["customer success teams", "product teams", "business owners"],
    outcome: "Explainable customer intelligence that improves service without hidden profiling.",
    boundary: "Sensitive traits, third-party personal data, and high-impact decisions cannot be inferred or sold.",
    focusAreas: ["customer research", "feedback analysis", "retention evidence", "journey analysis", "service personalization"],
  },
  DreamCyber: {
    purpose: "Help owners assess, monitor, harden, and recover their authorized systems with defensive security evidence.",
    serves: ["business owners", "security teams", "developers"],
    outcome: "Reduced attack surface and better recovery readiness through authorized, non-destructive testing.",
    boundary: "No unauthorized access, credential attacks, destructive testing, persistence, evasion, or denial of service.",
    focusAreas: ["attack surface review", "application security", "identity security", "cloud hardening", "incident readiness"],
  },
  DreamData: {
    purpose: "Collect, clean, govern, analyze, document, and exchange data with ownership and quality evidence.",
    serves: ["analysts", "data teams", "business operators"],
    outcome: "Trusted data products with provenance, access controls, quality tests, and deletion paths.",
    boundary: "Credentials, unlawfully obtained data, sensitive profiles, and unlicensed resale packages are blocked.",
    focusAreas: ["data ingestion", "data quality", "analytics", "data governance", "data products"],
  },
  DreamDecision: {
    purpose: "Structure complex decisions using evidence, alternatives, uncertainty, consequences, and accountable review.",
    serves: ["leaders", "operators", "individual users"],
    outcome: "Better decisions with visible assumptions, tradeoffs, dissent, and follow-up measurements.",
    boundary: "Buddy supports decisions but does not replace accountable human or licensed professional judgment.",
    focusAreas: ["decision framing", "evidence synthesis", "scenario analysis", "risk comparison", "decision review"],
  },
  DreamEducation: {
    purpose: "Build accessible lessons, courses, practice, tutoring, assessments, and learning simulations.",
    serves: ["students", "parents", "teachers", "training teams"],
    outcome: "Measurable learning experiences adapted to goals, age, accessibility, and evidence.",
    boundary: "Minors require protective defaults; grading, credentials, and school decisions remain institution-controlled.",
    focusAreas: ["curriculum design", "lesson production", "practice and tutoring", "assessment", "learning analytics"],
  },
  DreamEmpire: {
    purpose: "Provide portfolio-level strategy, governance, prioritization, and performance visibility across DreamCo systems.",
    serves: ["owners", "executives", "portfolio operators"],
    outcome: "A coherent operating portfolio with measurable priorities, budgets, risks, and accountability.",
    boundary: "Portfolio authority does not bypass division controls, evidence gates, or owner approval.",
    focusAreas: ["portfolio strategy", "capital planning", "cross-division governance", "performance reporting", "enterprise risk"],
  },
  DreamEntFinance: {
    purpose: "Support enterprise budgeting, planning, treasury analysis, controls, reporting, and financial operations.",
    serves: ["finance teams", "controllers", "executives"],
    outcome: "Auditable financial planning and operating insight with clear assumptions and approvals.",
    boundary: "Money movement, filings, attestations, and regulated advice require authorized people and systems.",
    focusAreas: ["budgeting", "financial planning", "treasury analysis", "controls", "management reporting"],
  },
  DreamFinance: {
    purpose: "Help users understand budgets, cash flow, goals, options, and financial tradeoffs.",
    serves: ["individuals", "families", "small businesses"],
    outcome: "Clearer financial choices supported by calculations, scenarios, and risk disclosures.",
    boundary: "Buddy does not guarantee returns, move money, extend credit, or replace licensed advice.",
    focusAreas: ["budgeting", "cash flow", "financial goals", "risk education", "financial comparisons"],
  },
  DreamFlow: {
    purpose: "Map work from request to completion and coordinate handoffs, queues, dependencies, and approvals.",
    serves: ["teams", "project managers", "operations leaders"],
    outcome: "Visible work ownership and predictable completion across people, bots, and systems.",
    boundary: "Handoffs preserve original permissions and cannot silently authorize downstream actions.",
    focusAreas: ["process mapping", "task queues", "handoff design", "dependency management", "workflow analytics"],
  },
  DreamFood: {
    purpose: "Support menu, kitchen, inventory, purchasing, safety, delivery, and food-business operations.",
    serves: ["restaurants", "food producers", "hospitality operators"],
    outcome: "Lower waste and stronger service through measurable food operations.",
    boundary: "Food safety, allergen decisions, inspections, and physical preparation remain qualified human responsibilities.",
    focusAreas: ["menu planning", "inventory", "kitchen operations", "food safety planning", "delivery operations"],
  },
  DreamGlobal: {
    purpose: "Support lawful international research, localization, trade preparation, culture-aware communication, and expansion.",
    serves: ["global teams", "exporters", "international founders"],
    outcome: "Country-aware plans with sourced legal, cultural, operational, and market assumptions.",
    boundary: "Local law, sanctions, customs, tax, and professional requirements must be verified before action.",
    focusAreas: ["market entry", "localization", "cross-cultural communication", "global compliance research", "international operations"],
  },
  DreamHealth: {
    purpose: "Support health education, care preparation, records organization, wellness planning, and provider communication.",
    serves: ["patients", "caregivers", "health teams"],
    outcome: "More prepared health conversations and organized user-controlled information.",
    boundary: "Buddy does not diagnose, prescribe, provide emergency care, or replace licensed clinicians.",
    focusAreas: ["health education", "care preparation", "wellness tracking", "records organization", "provider communication"],
  },
  DreamInfluence: {
    purpose: "Build authentic audiences, partnerships, campaigns, and creator operations with measurable trust.",
    serves: ["creators", "brands", "community teams"],
    outcome: "Audience growth based on useful content, transparent relationships, and consented engagement.",
    boundary: "No fake engagement, deceptive personas, undisclosed endorsements, harassment, or platform evasion.",
    focusAreas: ["audience research", "creator strategy", "partnerships", "campaign operations", "trust measurement"],
  },
  DreamLegal: {
    purpose: "Organize legal information, documents, deadlines, issue spotting, and attorney-ready work packets.",
    serves: ["individuals", "business teams", "legal professionals"],
    outcome: "Faster legal preparation with sources, jurisdiction labels, and review-ready documents.",
    boundary: "Buddy is not a lawyer and cannot provide legal representation, final opinions, or unauthorized filings.",
    focusAreas: ["legal research", "document preparation", "contract organization", "deadline tracking", "professional handoff"],
  },
  DreamLoans: {
    purpose: "Help users compare lawful financing options, prepare documentation, understand affordability, and detect risk.",
    serves: ["borrowers", "business owners", "finance teams"],
    outcome: "Better financing preparation with transparent costs, eligibility assumptions, and alternatives.",
    boundary: "Buddy does not guarantee approval, falsify eligibility, steer unfairly, or submit without exact approval.",
    focusAreas: ["loan comparison", "affordability", "application preparation", "credit education", "repayment planning"],
  },
  DreamMaintenance: {
    purpose: "Plan preventive maintenance, inspections, work orders, parts, service history, and equipment reliability.",
    serves: ["facility teams", "asset owners", "service businesses"],
    outcome: "Less downtime and safer assets through organized, evidence-based maintenance.",
    boundary: "Physical work, lockout procedures, safety inspections, and regulated repairs require qualified people.",
    focusAreas: ["preventive maintenance", "work orders", "asset history", "parts planning", "reliability analytics"],
  },
  DreamMarket: {
    purpose: "Research markets, competitors, customers, demand, pricing, and product opportunities.",
    serves: ["founders", "product teams", "investors"],
    outcome: "Source-backed market choices that separate observations, assumptions, and forecasts.",
    boundary: "No inside information, deceptive research, fabricated demand, or guaranteed commercial outcomes.",
    focusAreas: ["market research", "competitive intelligence", "demand validation", "pricing research", "opportunity scoring"],
  },
  DreamMilitary: {
    purpose: "Support lawful logistics, readiness, education, maintenance, administration, and veteran resources.",
    serves: ["authorized organizations", "service members", "veterans"],
    outcome: "Better non-weapon operational readiness and access to verified support resources.",
    boundary: "Weapons, targeting, surveillance abuse, classified data, and harmful operational guidance are excluded.",
    focusAreas: ["logistics", "readiness administration", "maintenance planning", "training support", "veteran resources"],
  },
  DreamOps: {
    purpose: "Improve business operations through process control, capacity planning, service levels, and incident response.",
    serves: ["operations leaders", "service teams", "business owners"],
    outcome: "Predictable operations with visible constraints, ownership, and recovery procedures.",
    boundary: "Operational automation cannot override safety controls, workforce rights, contracts, or approval policy.",
    focusAreas: ["process operations", "capacity", "service quality", "incident management", "continuous improvement"],
  },
  DreamPayments: {
    purpose: "Plan payment acceptance, billing, subscriptions, reconciliation, disputes, and revenue operations.",
    serves: ["merchants", "finance teams", "customers"],
    outcome: "Reliable payment workflows with transparent fees, consent, records, and recovery steps.",
    boundary: "Buddy never stores raw payment credentials, acts as an unlicensed processor, or moves money without approval.",
    focusAreas: ["payment routing", "billing", "subscriptions", "reconciliation", "dispute operations"],
  },
  DreamPersonalCare: {
    purpose: "Support user-directed routines, appointments, products, wellness services, and personal-care businesses.",
    serves: ["individuals", "care providers", "salons and wellness businesses"],
    outcome: "More organized personal care with preferences, safety notes, and service planning.",
    boundary: "Medical claims, invasive procedures, sensitive profiling, and unsafe product guidance are excluded.",
    focusAreas: ["routine planning", "service booking", "product comparison", "care business operations", "wellness education"],
  },
  DreamPlanetary: {
    purpose: "Support climate, earth observation, sustainability, resilience, and planetary-scale research planning.",
    serves: ["researchers", "communities", "sustainability teams"],
    outcome: "Evidence-based environmental decisions with uncertainty, provenance, and local context.",
    boundary: "Scientific claims require source evidence; emergency and public-policy decisions remain accountable to authorities.",
    focusAreas: ["earth observation", "climate evidence", "resource planning", "resilience", "sustainability measurement"],
  },
  DreamProServices: {
    purpose: "Operate consulting and professional-service work from discovery through proposal, delivery, and client success.",
    serves: ["consultants", "agencies", "service firms"],
    outcome: "Repeatable client delivery with scoped work, evidence, quality checks, and clear handoffs.",
    boundary: "Regulated conclusions, contract acceptance, invoicing, and client communications retain accountable approval.",
    focusAreas: ["client discovery", "proposal development", "engagement delivery", "quality assurance", "client success"],
  },
  DreamProduction: {
    purpose: "Plan and improve manufacturing, production scheduling, quality, materials, throughput, and traceability.",
    serves: ["manufacturers", "production teams", "operations engineers"],
    outcome: "Higher throughput and quality with safer, traceable production decisions.",
    boundary: "Physical controls, machinery, worker safety, and certified quality decisions remain human-controlled.",
    focusAreas: ["production planning", "materials", "quality control", "throughput", "traceability"],
  },
  DreamProtection: {
    purpose: "Support personal, property, business, emergency, and continuity protection planning.",
    serves: ["individuals", "businesses", "community teams"],
    outcome: "Prepared users with documented prevention, response, recovery, and escalation paths.",
    boundary: "No vigilantism, harmful surveillance, weapons guidance, emergency impersonation, or unauthorized monitoring.",
    focusAreas: ["risk assessment", "property protection", "business continuity", "emergency planning", "recovery coordination"],
  },
  DreamRealEstate: {
    purpose: "Support property discovery, underwriting, comparison, due diligence, operations, and transaction preparation.",
    serves: ["buyers", "sellers", "investors", "property teams"],
    outcome: "Property decisions with transparent assumptions, local evidence, calculators, and due-diligence steps.",
    boundary: "No fair-housing violations, guaranteed returns, unlicensed representation, valuation claims, or unauthorized offers.",
    focusAreas: ["property discovery", "deal analysis", "due diligence", "property operations", "transaction preparation"],
  },
  DreamRetail: {
    purpose: "Improve merchandising, inventory, pricing, customer service, commerce operations, and store performance.",
    serves: ["retailers", "commerce teams", "store operators"],
    outcome: "Better availability, margins, and customer experience through measurable retail workflows.",
    boundary: "Pricing, personalization, and fraud controls must remain lawful, explainable, and non-discriminatory.",
    focusAreas: ["merchandising", "inventory", "pricing", "commerce operations", "customer service"],
  },
  DreamSalesPro: {
    purpose: "Train sales teams and coordinate permission-aware research, qualification, conversations, proposals, and follow-up.",
    serves: ["sales representatives", "sales leaders", "business owners"],
    outcome: "Truthful, repeatable sales performance with measurable coaching and respectful customer experiences.",
    boundary: "No purchased lists, identity deception, spam, hidden recording, pressure tactics, or unapproved outreach.",
    focusAreas: ["sales training", "lead qualification", "conversation intelligence", "proposal and closing", "revenue operations"],
  },
  DreamScience: {
    purpose: "Support literature review, hypothesis design, experiment planning, analysis, reproducibility, and communication.",
    serves: ["researchers", "students", "laboratories"],
    outcome: "Reproducible scientific work with clear methods, uncertainty, provenance, and peer-review preparation.",
    boundary: "Buddy cannot fabricate evidence, bypass ethics review, perform unsafe experiments, or claim unverified findings.",
    focusAreas: ["literature review", "hypothesis design", "experiment planning", "scientific analysis", "reproducibility"],
  },
  DreamSocial: {
    purpose: "Plan, create, schedule, moderate, and measure consented social-media and community work.",
    serves: ["creators", "brands", "community managers"],
    outcome: "Consistent social presence built on useful content, real identity choices, and audience trust.",
    boundary: "No account takeover, coordinated manipulation, fake engagement, harassment, or publication without approval.",
    focusAreas: ["social strategy", "content scheduling", "community management", "moderation", "performance analytics"],
  },
  DreamTrade: {
    purpose: "Support lawful sourcing, supplier comparison, trade documentation, logistics, and commercial planning.",
    serves: ["buyers", "sellers", "supply teams"],
    outcome: "Traceable trade decisions with supplier, cost, route, compliance, and delivery evidence.",
    boundary: "Sanctions, customs, restricted goods, contracts, and payments require official verification and approval.",
    focusAreas: ["supplier discovery", "trade compliance research", "commercial terms", "logistics", "supplier performance"],
  },
  DreamTransport: {
    purpose: "Improve routing, fleet planning, dispatch, maintenance, safety, and transportation operations.",
    serves: ["fleet operators", "drivers", "logistics teams"],
    outcome: "Safer, more efficient transportation with traceable plans and operating evidence.",
    boundary: "Driving, dispatch authority, regulated safety decisions, and physical vehicle control remain human-controlled.",
    focusAreas: ["route planning", "fleet operations", "dispatch", "transport safety planning", "vehicle maintenance"],
  },
  GameTitan: {
    purpose: "Design, prototype, test, teach through, and publish original games and interactive simulations.",
    serves: ["players", "game creators", "teachers", "studios"],
    outcome: "Playable, accessible game experiences with clear design, assets, tests, progression, and release paths.",
    boundary: "Assets require rights; gambling, child safety, platform rules, payments, and publishing retain strict controls.",
    focusAreas: ["game design", "gameplay systems", "simulation", "game assets", "release engineering"],
  },
};

export const DIVISION_CAPABILITY_OPERATIONS = [
  { id: "discover", title: "Discover", description: "Find and define a user need in {focus} using traceable evidence." },
  { id: "intake", title: "Intake", description: "Collect a bounded {focus} brief, constraints, rights, and success measures." },
  { id: "research", title: "Research", description: "Compare current {focus} sources and separate observations from assumptions." },
  { id: "design", title: "Design", description: "Design a reviewable {focus} workflow with owners, inputs, outputs, and failure paths." },
  { id: "build", title: "Build", description: "Produce the {focus} artifact or implementation in a versioned workspace." },
  { id: "simulate", title: "Simulate", description: "Exercise {focus} with synthetic or owner-authorized fixtures before live use." },
  { id: "evaluate", title: "Evaluate", description: "Score {focus} for correctness, safety, usability, cost, and user value." },
  { id: "integrate", title: "Integrate", description: "Connect {focus} through least-privilege, reversible, health-checked adapters." },
  { id: "operate", title: "Operate", description: "Run approved {focus} work with observability, limits, approvals, and recovery." },
  { id: "improve", title: "Improve", description: "Use measured {focus} outcomes to prioritize the next evidence-backed release." },
] as const;

export const PRODUCTION_READINESS_GATES = [
  "named owner and user outcome",
  "versioned input and output contract",
  "rights, consent, and data classification",
  "least-privilege authorization design",
  "synthetic and owner-authorized fixtures",
  "unit, integration, and end-to-end tests",
  "security and privacy assessment",
  "accessibility and usability review",
  "latency, capacity, and cost budget",
  "observability and audit evidence",
  "failure recovery and rollback",
  "owner-approved release evidence",
] as const;

export const DAILY_BENCHMARK_WORKER_ROLES = [
  "source researcher",
  "fixture curator",
  "candidate runner",
  "quality grader",
  "security reviewer",
  "cost and latency analyst",
  "regression verifier",
  "release reporter",
] as const;

export const OFFICIAL_AI_ALLIANCE_WATCH = {
  name: "AI Alliance",
  snapshotDate: "2026-08-01",
  officialSources: {
    home: "https://thealliance.ai/",
    members: "https://thealliance.ai/members",
    projects: "https://thealliance.ai/projects",
    governance: "https://thealliance.ai/governance",
  },
  memberDirectory: {
    reportedSize: "200+",
    exactRosterMode: "discover_from_official_directory_at_run_time",
    membershipClaimedByDreamCo: false,
    verifiedMemberConnections: 0,
  },
  focusAreas: [
    "AI skills, education, and exploratory research",
    "safe and trusted AI",
    "AI agents, application patterns, and tools",
    "broadening the AI hardware ecosystem",
    "open foundation models and datasets",
    "AI advocacy and policy",
  ],
  activeProjectWatch: [
    "Open Trusted Data Initiative",
    "SYNTH",
    "Semikong",
    "GEO-Bench",
    "Validated Patterns",
    "TAPESTRY",
    "Dana Agent Framework",
    "Open Agent Hub",
    "Semiont",
    "Llama Stack",
    "Achieving Confidence in Enterprise AI Applications",
    "Evaluation is for everyone",
    "Evaluation Reference Stack",
  ],
  benchmarkDimensions: [
    "open license clarity",
    "data provenance",
    "reproducibility",
    "agent interoperability",
    "evaluation coverage",
    "safety and red-team evidence",
    "enterprise deployment",
    "hardware efficiency",
    "accessibility and education",
    "governance transparency",
    "sovereign and local operation",
    "measured user value",
  ],
  liveBenchmarksCompleted: 0,
  endorsementClaimed: false,
} as const;

export const SAFE_AI_TRAINING_CONTRACT = {
  position: "Buddy is a consent-first training and evaluation coordinator, not an unchecked self-modifying production model.",
  stages: [
    "define the user outcome and prohibited uses",
    "verify ownership, license, consent, and provenance",
    "remove secrets and minimize personal data",
    "create a dataset card and immutable dataset revision",
    "separate training, validation, red-team, and holdout fixtures",
    "train only in an isolated, resource-bounded workspace",
    "evaluate quality, privacy, security, bias, and misuse resistance",
    "require owner review before promoting a candidate",
    "deploy behind limits, monitoring, rollback, and a kill switch",
    "record outcomes and retrain only from approved evidence",
  ],
  productionSelfModificationAllowed: false,
  privateTrainingRequiresSeparateConsent: true,
  rawCredentialsAllowed: false,
} as const;

export const UNIVERSAL_CONNECTOR_LIFECYCLE = [
  "catalog official application or service",
  "verify owner authority and intended task",
  "select OAuth, passkey, service identity, or vault-reference authentication",
  "request minimum read-only scopes first",
  "test against a mock or sandbox",
  "perform user-present authorization",
  "run a read-only health check",
  "record scopes, owner, expiry, and revocation path",
  "approve one bounded write action when needed",
  "monitor failures, costs, and permission drift",
  "rotate or revoke access without exposing key material",
  "disconnect and delete local references on request",
] as const;
