export interface FormulaDefinition {
  name: string;
  category: string;
  description: string;
  formula: string;
  variables: string[];
  target: string;
  tags: string[];
}

export const FORMULA_CATEGORIES = [
  "Real Estate",
  "Car Flipping",
  "Sales",
  "Capital Deployment",
  "Risk Management",
  "Revenue Intelligence",
] as const;

export const FORMULA_LIBRARY: FormulaDefinition[] = [
  {
    name: "Core Flip Spread",
    category: "Real Estate",
    description: "Determines if a property is a strong flip candidate by calculating the spread between ARV and total costs",
    formula: "Deal Score = (ARV * 0.70) - (Purchase Price + Repairs)",
    variables: ["ARV", "Purchase Price", "Repairs"],
    target: "Deal Score > $25,000 = Strong Flip Candidate",
    tags: ["flip", "spread", "acquisition"],
  },
  {
    name: "Rental Cashflow",
    category: "Real Estate",
    description: "Calculates cash-on-cash return for rental properties to ensure minimum profitability",
    formula: "Cash-on-Cash Return = (Annual Net Income / Total Cash Invested) * 100",
    variables: ["Monthly Rent", "Monthly Expenses", "Total Cash Invested"],
    target: "Minimum 8-12% Cash-on-Cash Return",
    tags: ["rental", "cashflow", "hold"],
  },
  {
    name: "Equity Capture",
    category: "Real Estate",
    description: "Measures instant equity gained at purchase to ensure built-in profit margin",
    formula: "Instant Equity % = (ARV - Purchase Price) / ARV * 100",
    variables: ["ARV", "Purchase Price"],
    target: "15%+ minimum instant equity",
    tags: ["equity", "acquisition", "leverage"],
  },
  {
    name: "Motivation Score",
    category: "Real Estate",
    description: "Scores seller motivation level to determine negotiation leverage",
    formula: "Score = (Days on Market * 0.2) + (Price Drops * 5) + (Vacant Flag * 10)",
    variables: ["Days on Market", "Price Drops", "Vacant Flag"],
    target: "Higher score = higher negotiation leverage",
    tags: ["negotiation", "seller", "acquisition"],
  },
  {
    name: "BRRRR Recycle",
    category: "Real Estate",
    description: "Validates if a BRRRR deal returns all invested capital through refinance",
    formula: "Refi Amount >= Total Investment (Purchase + Repairs + Holding Costs)",
    variables: ["ARV", "LTV Ratio", "Purchase Price", "Repairs", "Holding Costs"],
    target: "Refi Amount >= Total Investment",
    tags: ["brrrr", "refinance", "recycle"],
  },
  {
    name: "Maximum Allowable Offer",
    category: "Real Estate",
    description: "Calculates the maximum price to offer on a flip deal using the 70% rule",
    formula: "MAO = (ARV * 0.70) - Repair Costs",
    variables: ["ARV", "Repair Costs"],
    target: "Never exceed MAO for profitable flips",
    tags: ["flip", "offer", "acquisition"],
  },
  {
    name: "Rental Yield",
    category: "Real Estate",
    description: "Calculates annual rental yield as a percentage of property value",
    formula: "Yield = (Annual Rent / Property Value) * 100",
    variables: ["Monthly Rent", "Property Value"],
    target: "5%+ gross yield for rental properties",
    tags: ["rental", "yield", "analysis"],
  },
  {
    name: "Debt Service Coverage",
    category: "Real Estate",
    description: "Measures ability to cover debt payments from rental income",
    formula: "DSCR = Net Operating Income / Annual Debt Service",
    variables: ["Net Operating Income", "Annual Debt Service"],
    target: "DSCR >= 1.25 for safe leverage",
    tags: ["leverage", "debt", "risk"],
  },
  {
    name: "Wholesale Assignment Fee",
    category: "Real Estate",
    description: "Calculates the assignment fee potential in a wholesale deal",
    formula: "Fee = End Buyer Price - Contract Price",
    variables: ["End Buyer Price", "Contract Price"],
    target: "Minimum $5,000 assignment fee",
    tags: ["wholesale", "assignment", "quick-profit"],
  },
  {
    name: "Section 8 Premium",
    category: "Real Estate",
    description: "Compares Section 8 voucher rates vs market rent for premium analysis",
    formula: "Premium = (Section 8 Rate - Market Rent) / Market Rent * 100",
    variables: ["Section 8 Rate", "Market Rent"],
    target: "Positive premium indicates above-market returns",
    tags: ["section8", "rental", "government"],
  },
  {
    name: "Car Spread Formula",
    category: "Car Flipping",
    description: "Calculates the profit spread between market value and total costs",
    formula: "Spread = Market Value - (Purchase + Repairs + Fees)",
    variables: ["Market Value", "Purchase Price", "Repair Cost", "Fees"],
    target: "Minimum 15-20% spread for viable deals",
    tags: ["spread", "profit", "acquisition"],
  },
  {
    name: "Demand Velocity Score",
    category: "Car Flipping",
    description: "Measures how quickly a vehicle model sells in a given market",
    formula: "Velocity = Listings Sold Last 30 Days / Active Listings",
    variables: ["Listings Sold (30 days)", "Active Listings"],
    target: "Above 1.0 = high demand vehicle",
    tags: ["demand", "velocity", "market"],
  },
  {
    name: "Repair Risk Multiplier",
    category: "Car Flipping",
    description: "Adjusts profit for repair cost uncertainty with a safety buffer",
    formula: "Adjusted Profit = Spread - (Repair Estimate * 1.3)",
    variables: ["Spread", "Repair Estimate"],
    target: "Must remain positive after 30% buffer",
    tags: ["repair", "risk", "buffer"],
  },
  {
    name: "Time-to-Liquidation",
    category: "Car Flipping",
    description: "Predicts average days to sell based on model and zip code data",
    formula: "TTL = Average Days on Market (Model + Zip Code)",
    variables: ["Vehicle Model", "Zip Code", "Avg Market Days"],
    target: "Target under 21 days for rapid turn",
    tags: ["liquidation", "speed", "turnover"],
  },
  {
    name: "Max Purchase Price",
    category: "Car Flipping",
    description: "Calculates the maximum purchase price for profitable car flips",
    formula: "Max Purchase = (Expected Sale * 0.75) - Repair Costs",
    variables: ["Expected Sale Price", "Repair Costs"],
    target: "Never exceed max purchase for profitability",
    tags: ["acquisition", "max-price", "limit"],
  },
  {
    name: "Capital Turn Rate",
    category: "Car Flipping",
    description: "Measures how many times capital is recycled per year",
    formula: "Turn Rate = 365 / Average Hold Period",
    variables: ["Average Hold Period (days)"],
    target: "12+ turns per year for maximum capital efficiency",
    tags: ["capital", "turnover", "efficiency"],
  },
  {
    name: "Daily Profit Rate",
    category: "Car Flipping",
    description: "Calculates profit per day held to compare deal efficiency",
    formula: "Daily Profit = Net Profit / Days Held",
    variables: ["Net Profit", "Days Held"],
    target: "Higher daily profit = better capital deployment",
    tags: ["profit", "daily", "efficiency"],
  },
  {
    name: "Lead Value Formula",
    category: "Sales",
    description: "Calculates the expected value of each lead based on conversion probability",
    formula: "Expected Value = Close Rate * Average Deal Size",
    variables: ["Close Rate", "Average Deal Size"],
    target: "Prioritize leads with highest expected value",
    tags: ["leads", "value", "conversion"],
  },
  {
    name: "CAC Efficiency",
    category: "Sales",
    description: "Measures customer acquisition efficiency by comparing lifetime value to cost",
    formula: "LTV/CAC Ratio = Customer Lifetime Value / Customer Acquisition Cost",
    variables: ["Customer Lifetime Value", "Customer Acquisition Cost"],
    target: "LTV/CAC >= 3 for healthy unit economics",
    tags: ["cac", "ltv", "efficiency"],
  },
  {
    name: "Funnel Leak Detection",
    category: "Sales",
    description: "Identifies conversion drop-offs between sales funnel stages",
    formula: "Drop-Off % = (Stage N Count - Stage N+1 Count) / Stage N Count * 100",
    variables: ["Stage N Count", "Stage N+1 Count"],
    target: "Identify stages with > 40% drop-off for optimization",
    tags: ["funnel", "conversion", "optimization"],
  },
  {
    name: "Pipeline Velocity",
    category: "Sales",
    description: "Measures the speed of revenue flowing through the sales pipeline",
    formula: "Velocity = (Opportunities * Win Rate * Deal Size) / Sales Cycle Days",
    variables: ["Opportunities", "Win Rate", "Average Deal Size", "Sales Cycle Days"],
    target: "Increasing velocity indicates improving sales efficiency",
    tags: ["pipeline", "velocity", "revenue"],
  },
  {
    name: "Commission ROI",
    category: "Sales",
    description: "Calculates return on investment for commission-based sales teams",
    formula: "ROI = (Revenue Generated - Total Commission Paid) / Total Commission Paid * 100",
    variables: ["Revenue Generated", "Total Commission Paid"],
    target: "Minimum 300% ROI on commission spend",
    tags: ["commission", "roi", "team"],
  },
  {
    name: "Closing Probability",
    category: "Sales",
    description: "Predicts deal closing likelihood based on engagement signals",
    formula: "Probability = (Meetings * 0.3) + (Proposal Sent * 0.4) + (Champion Score * 0.3)",
    variables: ["Meetings Held", "Proposal Sent", "Champion Score"],
    target: "Above 70% = high-confidence close",
    tags: ["closing", "probability", "prediction"],
  },
  {
    name: "Liquidity Ratio",
    category: "Capital Deployment",
    description: "Ensures adequate operating reserves relative to monthly burn rate",
    formula: "Ratio = Operating Reserves / Monthly Burn Rate",
    variables: ["Operating Reserves", "Monthly Burn Rate"],
    target: ">= 6 months of reserves for safety",
    tags: ["liquidity", "reserves", "safety"],
  },
  {
    name: "Reinvestment Multiplier",
    category: "Capital Deployment",
    description: "Calculates the optimal profit reinvestment percentage for growth",
    formula: "Reinvest Amount = Net Profit * 0.60",
    variables: ["Net Profit"],
    target: "60% reinvest, 30% reserve, 10% expansion",
    tags: ["reinvestment", "growth", "allocation"],
  },
  {
    name: "Capital Deployment Efficiency",
    category: "Capital Deployment",
    description: "Measures how efficiently deployed capital generates returns",
    formula: "Efficiency = Annual Returns / Total Capital Deployed * 100",
    variables: ["Annual Returns", "Total Capital Deployed"],
    target: "15%+ annual return on deployed capital",
    tags: ["efficiency", "returns", "deployment"],
  },
  {
    name: "Debt-to-Equity Ratio",
    category: "Capital Deployment",
    description: "Monitors leverage levels across the portfolio",
    formula: "D/E = Total Liabilities / Total Equity",
    variables: ["Total Liabilities", "Total Equity"],
    target: "D/E < 2.0 for conservative leverage",
    tags: ["leverage", "debt", "equity"],
  },
  {
    name: "Risk-Adjusted Return",
    category: "Risk Management",
    description: "Adjusts returns for risk level to compare deals fairly",
    formula: "RAR = Expected Return / Risk Score",
    variables: ["Expected Return", "Risk Score"],
    target: "Higher RAR = better risk-adjusted opportunity",
    tags: ["risk", "return", "comparison"],
  },
  {
    name: "Portfolio Concentration",
    category: "Risk Management",
    description: "Measures exposure to any single asset type or market",
    formula: "Concentration = Single Asset Value / Total Portfolio Value * 100",
    variables: ["Single Asset Value", "Total Portfolio Value"],
    target: "No single asset > 25% of total portfolio",
    tags: ["diversification", "concentration", "portfolio"],
  },
  {
    name: "Drawdown Recovery",
    category: "Risk Management",
    description: "Calculates time to recover from a portfolio drawdown",
    formula: "Recovery Time = Loss Amount / Monthly Net Income",
    variables: ["Loss Amount", "Monthly Net Income"],
    target: "Recovery within 6 months for acceptable risk",
    tags: ["drawdown", "recovery", "risk"],
  },
  {
    name: "Revenue Per Bot",
    category: "Revenue Intelligence",
    description: "Tracks revenue generation efficiency per AI agent",
    formula: "RPB = Total Revenue / Active Bots",
    variables: ["Total Revenue", "Active Bot Count"],
    target: "Increasing RPB indicates platform efficiency",
    tags: ["revenue", "bots", "efficiency"],
  },
  {
    name: "Churn Prediction Score",
    category: "Revenue Intelligence",
    description: "Predicts customer churn likelihood based on usage patterns",
    formula: "Score = (Login Frequency * 0.3) + (Feature Usage * 0.4) + (Support Tickets * -0.3)",
    variables: ["Login Frequency", "Feature Usage", "Support Tickets"],
    target: "Score < 40 = high churn risk, intervene immediately",
    tags: ["churn", "prediction", "retention"],
  },
  {
    name: "Dynamic Pricing Optimizer",
    category: "Revenue Intelligence",
    description: "Adjusts pricing based on demand, competition, and capacity",
    formula: "Optimal Price = Base Price * (1 + Demand Factor) * (1 - Competition Pressure)",
    variables: ["Base Price", "Demand Factor", "Competition Pressure"],
    target: "Maximize revenue while maintaining conversion",
    tags: ["pricing", "dynamic", "optimization"],
  },
  {
    name: "Revenue Leak Score",
    category: "Revenue Intelligence",
    description: "Identifies and quantifies revenue losses across the system",
    formula: "Leak Score = (Failed Transactions + Cart Abandonment + Pricing Errors) * Avg Order Value",
    variables: ["Failed Transactions", "Cart Abandonment Rate", "Pricing Errors", "Avg Order Value"],
    target: "Minimize leak score to zero",
    tags: ["leak", "revenue", "detection"],
  },
];
