#!/usr/bin/env python3
"""Turn failed GitHub Actions runs into deduplicated, actionable Issues.

Designed to run inside GitHub Actions with GH_TOKEN, GITHUB_REPOSITORY and RUN_ID.
It never prints secrets and ignores its own workflow to avoid recursion.
"""
import hashlib
import json
import os
import re
import subprocess
import sys
import urllib.parse
import zipfile
from pathlib import Path


def gh_api(path, method="GET", payload=None):
    cmd = ["gh", "api", path]
    if method != "GET":
        cmd += ["--method", method]
    if payload is not None:
        cmd += ["--input", "-"]
    p = subprocess.run(cmd, input=json.dumps(payload) if payload is not None else None,
                       text=True, capture_output=True, check=False)
    if p.returncode != 0:
        raise RuntimeError(p.stderr.strip() or f"gh api failed: {path}")
    return json.loads(p.stdout) if p.stdout.strip() else {}


def normalize(text):
    text = re.sub(r"https?://\S+", "<url>", text)
    text = re.sub(r"/home/runner/work/[^ ]+", "<runner-path>", text)
    text = re.sub(r"\b[0-9a-f]{7,40}\b", "<sha>", text, flags=re.I)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:500]


def classify(text):
    t = text.lower()
    rules = [
        ("dependency", ["npm ci", "npm install", "pip install", "no matching distribution", "ebadengine", "dependency", "lockfile"]),
        ("test", ["pytest", "test failed", "assertionerror", "xcodebuild test", "tests failed"]),
        ("lint", ["eslint", "ruff", "flake8", "black", "prettier", "lint failed"]),
        ("build", ["build failed", "xcodebuild", "compile", "typescript", "tsc", "module not found"]),
        ("configuration", ["environment variable", "secret", "configuration", "missing required"]),
        ("permissions", ["permission denied", "resource not accessible", "403", "insufficient permission"]),
        ("timeout", ["timed out", "timeout", "cancelled after"]),
    ]
    for category, needles in rules:
        if any(n in t for n in needles):
            return category
    return "workflow"


def severity(conclusion, category, text):
    if category in {"permissions", "configuration"}:
        return "high"
    if category in {"build", "test"}:
        return "high" if "main" in text.lower() else "medium"
    if category == "timeout":
        return "medium"
    return "medium" if conclusion == "failure" else "low"


def main():
    repo = os.environ["GITHUB_REPOSITORY"]
    run_id = os.environ["RUN_ID"]
    run = gh_api(f"repos/{repo}/actions/runs/{run_id}")
    if run.get("name") == "Issue Intelligence":
        return
    if run.get("conclusion") not in {"failure", "timed_out", "cancelled", "startup_failure"}:
        return

    jobs = gh_api(f"repos/{repo}/actions/runs/{run_id}/jobs?per_page=100").get("jobs", [])
    failed = [j for j in jobs if j.get("conclusion") not in {"success", "skipped", None}]
    if not failed:
        return

    evidence = []
    for job in failed:
        failed_steps = [s for s in job.get("steps", []) if s.get("conclusion") not in {"success", "skipped", None}]
        step_names = [s.get("name", "unknown") for s in failed_steps]
        evidence.append({"job": job.get("name"), "conclusion": job.get("conclusion"), "steps": step_names})

    compact = normalize(json.dumps(evidence, sort_keys=True))
    key = hashlib.sha256((run.get("workflow_id", "") and str(run.get("workflow_id")) + "|" + compact).encode()).hexdigest()[:12]
    category = classify(compact)
    level = severity(run.get("conclusion", "failure"), category, run.get("head_branch", ""))
    title = f"[CI][{level}][{category}] {run.get('name', 'Workflow')} failure ({key})"

    q = urllib.parse.quote(f'repo:{repo} is:issue in:title "{key}"')
    existing = gh_api(f"search/issues?q={q}&per_page=5").get("items", [])
    if existing:
        print(f"Issue already tracked: #{existing[0]['number']}")
        return

    body = f"""## Automated Actions failure triage\n\n**Run:** {run.get('html_url', '')}\n**Workflow:** {run.get('name', '')}\n**Branch:** `{run.get('head_branch', '')}`\n**Commit:** `{run.get('head_sha', '')}`\n**Conclusion:** `{run.get('conclusion', '')}`\n**Category:** `{category}`\n**Severity:** `{level}`\n**Deduplication key:** `{key}`\n\n### Failed jobs/steps\n```json\n{json.dumps(evidence, indent=2)}\n```\n\n### Lifecycle\n`new` → `investigating` → `fixing` → `retest` → `resolved`\n\nThis issue was generated by the DreamCo Issue Intelligence system. Fix the root cause, rerun the affected workflow, and close only after the replacement run passes.\n"""
    labels = ["ci-failure", f"severity:{level}", f"ci:{category}"]
    issue = gh_api(f"repos/{repo}/issues", method="POST", payload={"title": title, "body": body, "labels": labels})
    print(f"Created issue #{issue.get('number')} for run {run_id}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"Issue Intelligence error: {normalize(str(exc))}", file=sys.stderr)
        sys.exit(1)
