"""Honest file evidence for the 311 owner-directive sections.

A path only counts when it exists on disk. Docs-only stays catalogued.
HTML/JS/Python/workflow that actually implements the section can become
implemented. Sandbox/benchmark/regression/production are decided by the
self-build runner, never by this map.
"""

from __future__ import annotations

# section number -> candidate implementation files (not plans-only markdown)
EVIDENCE: dict[int, list[str]] = {
    3: ["website/data/master-directive-status.json", "tools/generate_master_directive_status.py"],
    4: ["tools/generate_master_directive_status.py", "website/data/master-directive-status.json"],
    5: ["website/data/master-directive-status.json", ".github/workflows/command-center-index.yml"],
    6: ["website/master-build.html", "website/master-build.js", "website/build.html"],
    7: ["website/master-build.html", ".github/workflows/pages.yml", ".github/workflows/deploy-buddy-pages.yml"],
    8: ["website/nav.js", "website/buddy.html", "website/index.html"],
    9: ["website/actions.html", "docs/ACTIONS_CONTROL_PLANE.md", ".github/workflows/actions-command-center.yml"],
    10: ["docs/BUDDY_REPAIR_ORCHESTRATOR_SPEC.md", "tools/buddy_recovery_systems.py", "website/recover.html", ".github/workflows/buddy-recovery-systems.yml"],
    11: ["docs/UNIFIED_500_MODEL_BENCHMARK_OPERATING_PLAN.md", "website/benchmark-tracker.html", ".github/workflows/benchmark-tracker.yml"],
    12: ["docs/BUDDY_BOT_BOOTCAMP.md", "tools/buddy_bootcamp_engine.py", ".github/workflows/buddy-sandbox-bootcamp.yml"],
    13: ["docs/BUDDY_1000_SOURCE_BOOTCAMP.md", "website/source-scanner.html", "tools/buddy_source_selector.py"],
    14: ["docs/OPEN_SOURCE_ADVANCEMENT_PROGRAM.md", ".github/workflows/open-source-evolution.yml"],
    15: ["tools/generate_buddy_learning_strategies.py", "website/buddy-learning-lab.html"],
    16: [".github/workflows/grok-team.yml", "tools/build_council_bot_career_paths.py"],
    17: ["website/models.html", "website/command.html", "config/500-model-full-matrix-prospectus.json"],
    18: ["website/setup-center.html", "website/connections.html"],
    19: ["docs/500_MODEL_RESEARCH.md", "tools/build_500_model_prospectus_matrix.py", "website/models.html", ".github/workflows/buddy-500-model-governance.yml"],
    20: ["tools/build_ontology_snapshot.py"],
    21: ["website/bots.html", "tools/build_legacy_bot_inventory.py", ".github/workflows/compile-md-bots.yml"],
    22: ["website/divisions.html", "docs/BUDDY_65_MASTERBOT_OPERATING_SYSTEM.md", ".github/workflows/buddy-65-masterbot-training.yml"],
    23: ["docs/BUDDY_UNIVERSAL_LEARNING_ENGINE.md", ".github/workflows/continuous-learning-runner.yml"],
    24: ["docs/DEPLOYMENT_COST_POLICY.md", "website/costs.html"],
    25: ["docs/BUDDY_LAPTOP_CLI_20_OPTIONS.md", "tools/buddy_cli.py", "tools/buddy_local_bridge.py"],
    26: ["docs/BUDDY_LAPTOP_APP_TESTING.md", "website/install.html"],
    27: ["docs/BUDDY_DEVICE_FABRIC.md", "website/phone.html"],
    28: ["website/data-control.html"],
    29: ["docs/BUDDY_AUTONOMY_LEVELS_AND_GATES.md", "website/autonomy.html", "config/buddy-autonomy-policy.yaml"],
    30: ["docs/BUDDY_THREE_QUEUE_OPERATING_MODEL.md", "website/work.html"],
    31: ["website/work.html", "website/ops.html"],
    32: ["website/revenue.html", "website/payments.html"],
    33: ["website/payments.html"],
    34: ["website/open-model-lab.html", "website/codelab.html"],
    35: ["website/connections.html", "website/connect-desk.html"],
    36: ["website/connect-desk.html"],
    37: ["website/vibe-game-builder.html", "docs/BUDDY_VIBE_CODING_CONTRACT.md"],
    38: ["docs/UNIVERSAL_CAPABILITY_ARCHITECTURE.md", ".github/workflows/repo-capability-audit.yml"],
    39: ["docs/CODING_CAPABILITY_BENCHMARK_LAB.md", "website/codelab.html"],
    40: ["docs/CONTINUOUS_INNOVATION_AND_LIBRARY_SPECIALISTS.md"],
    41: ["website/learning.html", "website/practice.html"],
    42: ["docs/AI_RESEARCH_OBSERVATORY.md", ".github/workflows/dreamco-daily-research-benchmark.yml"],
    43: ["docs/SUPERBOT_SIMULATION_LAB.md"],
    44: ["website/government.html", "tools/build_global_government_benchmarks.py"],
    45: ["docs/real_estate/BUDDY_REAL_ESTATE_DEVELOPMENT.md", "website/opportunity-hub.html"],
    46: ["docs/video-intelligence.md"],
    47: ["website/search.html"],
    48: ["website/resource-211.html"],
    49: ["docs/CUSTOMER_PRODUCTION_RUNBOOK.md"],
    50: ["docs/BUDDY_WEIGHT_OWNERSHIP.md"],
    51: ["website/success.html"],
    52: ["website/debug.html", ".github/workflows/dreamco-core-health.yml"],
    53: ["website/costs.html", "docs/DEPLOYMENT_COST_POLICY.md"],
    54: ["docs/BUDDY_REPAIR_ORCHESTRATOR_SPEC.md"],
    55: ["website/security.html", "SECURITY.md", ".github/workflows/codeql.yml"],
    56: ["website/security.html"],
    57: ["docs/PRODUCTION_READINESS_MASTER_PLAN.md", ".github/workflows/production-readiness.yml"],
    58: [".github/workflows/branch-health-daily.yml", "tools/branch_health_daily.py", "website/branch-health.html"],
    59: ["docs/ENGINEERING_CONVENTIONS.md"],
    60: ["docs/DEFINITION_OF_DONE.md", ".github/workflows/repository-test-matrix.yml"],
    61: [".github/workflows/keep-green.yml", "docs/PRODUCTION_GREENKEEPER.md"],
    62: [".github/workflows/dependency-review.yml"],
    63: ["README.md"],
    64: [".github/workflows/deploy-buddy-pages.yml", "website/install.html"],
    65: [".github/workflows/pages.yml", "website/buddy.html"],
    66: ["website/data-control.html"],
    67: ["website/revenue.html"],
    68: ["website/buddy-command-center.html", "website/command.html"],
    69: ["website/leaders.html", "website/models.html"],
    70: ["website/buddy-learning-lab.html", "docs/BUDDY_1000_SOURCE_BOT_TRAINING_GROUND.md"],
    71: ["docs/CAPABILITY_GENOME_EXPERIMENT_ENGINE.md"],
    72: ["tools/buddy_source_selector.py"],
    73: ["docs/US_WEIGHT_SYSTEM.md", "tools/buddy_weights.py"],
    74: ["docs/BUDDY_WEIGHT_OWNERSHIP.md"],
    75: ["docs/BUDDY_AGI_STYLE_REPAIR_ARCHITECTURE.md"],
    76: ["website/studio.html"],
    77: ["website/vibe-game-builder.html", "website/codelab.html"],
    78: ["website/creator-platforms.html", "website/studio.html"],
    79: ["website/my-buddy.html"],
    80: ["website/voice-command-center.html"],
    81: ["website/studio.html"],
    82: ["website/hollywood-career.html", "website/music-creator.html"],
    83: ["website/benchmark-tracker.html", "docs/CODING_CAPABILITY_BENCHMARK_LAB.md"],
    84: ["website/payments.html", "website/revenue.html"],
    85: ["website/leads.html"],
    86: ["website/opportunity-hub.html"],
    87: [".github/workflows/startup-factory-contract.yml"],
    88: ["website/divisions.html"],
    89: ["tools/build_legacy_bot_inventory.py", ".github/workflows/superbot-inventory.yml"],
    90: ["docs/NOTES_ORGANIZATION.md"],
    91: ["docs/DEFINITION_OF_DONE.md"],
    92: ["docs/PRODUCT_ENGINEERING_STANDARD.md"],
    93: [".github/workflows/consolidation-integrity-gate.yml"],
    94: [".github/workflows/keep-green.yml"],
    95: ["config/api-test-targets.json", "tools/build_api_test_matrix.py"],
    96: ["docs/ARCHITECTURE.md"],
    97: ["docs/ENGINEERING_CONVENTIONS.md"],
    98: ["docs/BUDDY_65_MASTERBOT_OPERATING_SYSTEM.md"],
    99: ["website/connect-desk.html", "website/autonomy.html"],
    100: ["tools/buddy_local_bridge.py", "website/work.html"],
    101: ["website/open-model-lab.html"],
    102: ["docs/BUDDY_LAPTOP_APP_TESTING.md"],
    103: ["website/buddy.html", "website/buddy.css"],
    104: ["website/actions.html", "docs/ACTIONS_CONTROL_PLANE.md"],
    105: ["docs/ACTIONS_RECOVERY_BUTTONS.md", "website/actions.html"],
    106: ["website/benchmark-tracker.html", "website/models.html"],
    107: ["website/costs.html"],
    108: [".github/workflows/dreamco-core-health.yml", "website/debug.html"],
    109: ["docs/DEFINITION_OF_DONE.md", ".github/workflows/production-readiness.yml"],
    110: [".github/workflows/problem-registry.yml", "docs/BUDDY_REPAIR_EVENT_SCHEMA.md"],
    111: ["docs/BENCHMARK_EVIDENCE_LIFECYCLE.md"],
    112: [".github/workflows/actions-failure-watch.yml"],
    113: ["website/recover.html", "tools/buddy_recovery_systems.py"],
    114: ["website/recover.html"],
    115: ["website/security.html", "website/data-control.html"],
    116: ["website/marketplace.html"],
    117: ["website/downloads.html"],
    118: ["website/settings.html"],
    119: ["website/buddy.html"],
    120: ["website/buddy.css"],
    121: [".github/workflows/repository-test-matrix.yml"],
    122: [".github/workflows/keep-green.yml"],
    123: ["docs/BUDDY_24H_GAP_CLOSURE.md", ".github/workflows/buddy-gap-closure-24h.yml"],
    124: ["website/data/master-directive-status.json", "docs/BENCHMARK_EVIDENCE_LIFECYCLE.md"],
    125: ["docs/BUDDY_WEB_SOURCE_CONNECTION.md"],
    126: ["docs/BUDDY_WEB_LEARNING_FABRIC.md"],
    127: ["website/data-control.html"],
    128: ["tools/buddy_cli.py", "docs/BUDDY_LAPTOP_CLI_20_OPTIONS.md"],
    129: ["tools/buddy_cli.py"],
    130: [".github/workflows/pr-review-parity-gate.yml"],
    132: ["docs/GITHUB_FIRST_PERSONAL_AI_SETUP.md"],
    133: ["docs/repository-scan-update-standard.md", ".github/workflows/repository-scan-update.yml"],
    134: [".github/workflows/pages.yml", ".github/workflows/deploy-buddy-pages.yml"],
    135: ["website/open-model-lab.html"],
    136: ["website/autonomy.html", "website/security.html"],
    137: ["website/security.html"],
    138: ["website/security.html", ".github/workflows/code-trust-gate.yml"],
    139: [".github/workflows/buddy-24h-sandbox-soak.yml"],
    140: ["docs/BENCHMARK_EVIDENCE_LIFECYCLE.md"],
    141: ["docs/BUDDY_BUILD_RUNTIME.md", "website/codelab.html"],
    142: ["website/collection-vault.html", "website/data-control.html"],
    143: [".github/workflows/business-data-trade-readiness.yml"],
    144: ["docs/CUSTOMER_PRODUCTION_RUNBOOK.md"],
    146: ["website/security.html", "SECURITY.md"],
    147: ["docs/BUDDY_ACTION_MEMORY_AND_CONTEXT.md"],
    148: ["website/dashboard.html"],
    149: ["website/success.html"],
    150: ["website/my-buddy.html"],
    152: ["website/bots.html", ".github/workflows/superbot-inventory.yml"],
    153: [".github/workflows/compile-md-bots.yml"],
    155: [".github/workflows/dreamco-core-health.yml"],
    156: ["website/costs.html", "docs/DEPLOYMENT_COST_POLICY.md"],
    157: ["docs/BENCHMARK_EVIDENCE_LIFECYCLE.md"],
    158: ["docs/BUDDY_REPAIR_ORCHESTRATOR_SPEC.md"],
    159: ["website/security.html"],
    160: ["website/payments.html"],
    161: ["website/connections.html", "website/debug.html"],
    162: ["docs/dreamco-lite/DREAMCO_LITE_MVP.md"],
    163: ["website/leads.html"],
    164: ["website/formulas.html"],
    165: ["website/timecapsule.html"],
    166: ["website/costs.html"],
    167: ["website/connections.html", "website/wiring.html"],
    168: ["website/deals.html", "website/loans.html"],
    169: ["website/government.html"],
    170: ["website/resource-211.html"],
    171: ["website/security.html"],
    172: ["website/crypto.html"],
    173: ["website/marketplace.html"],
    174: ["website/leads.html"],
    175: ["website/wiring.html"],
    176: ["website/data/master-directive-status.json"],
    177: ["website/search.html"],
    178: ["website/command.html"],
    179: ["website/master-build.html", "website/build.html"],
    180: ["tools/generate_master_directive_status.py"],
    181: ["tools/generate_master_directive_status.py"],
    182: ["tools/benchmark_gap_closure.py", ".github/workflows/benchmark-gap-planner.yml"],
    183: ["website/practice.html", "website/learning.html"],
    184: ["website/benchmark-tracker.html"],
    185: ["docs/BUDDY_BOOTCAMP_SANDBOX_SPEC.md", ".github/workflows/buddy-sandbox-bootcamp.yml"],
    186: ["tools/build_full_potential_sandbox_catalog.py"],
    187: ["docs/BUDDY_BUILD_RUNTIME.md"],
    188: ["website/open-model-lab.html"],
    189: ["docs/BUDDY_USER_TESTING_CATALOG.md", "tools/build_live_user_testing_readiness.py"],
    192: ["website/benchmark-tracker.html"],
    193: ["docs/BUDDY_CAPABILITY_GRAPH_V2.md"],
    194: [".github/workflows/buddy-fleet-health.yml", "website/bots.html"],
    195: ["website/models.html", "website/leaders.html"],
    196: ["website/open-model-lab.html", "website/buddy-open-core.html"],
    197: ["docs/BUDDY_FRONTIER_EVALUATION_HARNESS.md"],
    199: ["docs/BUDDY_SANDBOX_BOOTCAMP_DATA_PACKAGE.md"],
    201: [".github/workflows/model-progress-center.yml"],
    203: ["tools/buddy_local_bridge.py"],
    204: ["tools/buddy_local_bridge.py"],
    207: [".github/workflows/intelligent-issue-cleaner.yml", ".github/workflows/issue-intelligence.yml"],
    208: [".github/workflows/self-working-system.yml"],
    209: [".github/workflows/pr-recovery-engine.yml", "tools/branch_conflict_team.py"],
    210: [".github/workflows/dreamco-pr-review-guardian.yml"],
    211: ["website/actions.html"],
    212: ["docs/index.md"],
    217: ["docs/ARCHITECTURE.md", "SYSTEM_ARCHITECTURE.md"],
    220: ["website/command.html", "website/ops.html"],
    221: ["website/command.html"],
    222: ["website/ops.html", "website/work.html"],
    227: ["website/work.html"],
    232: ["website/payments.html", "website/pricing.html"],
    233: ["website/payments.html"],
    234: ["website/install.html"],
    240: ["docs/BUDDY_BOOTCAMP_AND_TRUST_FRAMEWORK.md", "website/security.html"],
    241: ["website/success.html", "website/master-build.html"],
    242: ["website/buddy.html", "website/recover.html"],
    243: ["website/master-build.html", "website/build.html"],
    244: ["tools/generate_master_directive_status.py"],
    245: ["tools/generate_master_directive_status.py"],
    246: [".github/workflows/repository-test-matrix.yml"],
    248: ["website/recover.html", "tools/buddy_recovery_systems.py"],
    249: ["website/buddy.html", "website/master-build.html", ".github/workflows/pages.yml"],
    250: ["website/benchmark-tracker.html", ".github/workflows/buddy-benchmark-smoke.yml"],
    251: ["website/bots.html"],
    252: ["website/divisions.html"],
    253: ["website/models.html", "website/open-model-lab.html"],
    255: ["website/actions.html", "website/ops.html"],
    257: ["docs/DREAMCO_BUDDY_MASTER_CODEX_DIRECTIVE.md"],
    258: ["website/data/master-directive-status.json"],
    259: [".github/workflows/dreamco-unified-system.yml", "website/recover.html", "website/build.html"],
    260: ["website/data/master-directive-status.json", "website/wiring.html"],
    262: ["docs/DEFINITION_OF_DONE.md"],
    263: ["docs/ENGINEERING_CONVENTIONS.md"],
    264: ["docs/BUDDY_REPAIR_ORCHESTRATOR_SPEC.md", "website/recover.html"],
    266: ["tools/build_legacy_bot_inventory.py", ".github/workflows/original-bot-placement.yml"],
    267: [".github/workflows/buddy-os-contracts.yml"],
    268: ["tools/generate_master_directive_status.py", "tools/master_directive_evidence.py"],
    269: ["docs/BENCHMARK_EVIDENCE_LIFECYCLE.md"],
    270: ["website/data-control.html"],
    271: ["website/data-control.html", "website/security.html"],
    273: ["website/open-model-lab.html"],
    275: ["docs/BENCHMARK_EVIDENCE_LIFECYCLE.md"],
    277: ["website/buddy.html"],
    278: ["docs/CODING_CAPABILITY_BENCHMARK_LAB.md"],
    281: ["website/command.html"],
    282: ["website/recover.html", "docs/BUDDY_REPAIR_INTELLIGENCE_SCORECARD.md"],
    284: ["website/payments.html"],
    288: [".github/workflows/actions-failure-sweep.yml"],
    289: [".github/workflows/issue-intelligence.yml"],
    291: [".github/workflows/codeql.yml", "website/security.html"],
    292: ["website/security.html"],
    294: ["SECURITY.md"],
    297: ["website/data-control.html"],
    298: ["website/recover.html"],
    299: ["website/recover.html", "docs/BUDDY_REPAIR_ORCHESTRATOR_SPEC.md"],
    300: ["docs/PRODUCTION_PUSH_GUIDE.md"],
    301: ["docs/DREAMCO_MASTER_PLAN.md"],
    307: ["website/autonomy.html", "website/security.html"],
    308: ["website/autonomy.html"],
    309: ["website/data/master-directive-status.json"],
    310: ["website/master-build.html", "website/build.html"],
    311: ["website/build.html", "website/data/master-directive-status.json", "tools/buddy_self_build.py"],
}

# Money / live-charge / secret surfaces: files may exist as plans, never production_verified here.
MONEY_SECTIONS = {32, 33, 84, 160, 168, 232, 233, 284}
