import {questionsFor} from './bot-intake-questions.js';
const app=document.getElementById('profile-app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), $=id=>document.getElementById(id);
const slug=document.body.dataset.bot;let profile,questions,step=0;
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function answers(){return Object.fromEntries(questions.map(q=>[q.id,$('answer-'+q.id).value.trim()]))}
function progress(){const n=Object.values(answers()).filter(Boolean).length;$('intake-count').textContent=`${n} of 30 answered · section ${step+1} of 6`;$('intake-progress-bar').style.width=n/30*100+'%'}
function showStep(n){step=Math.max(0,Math.min(5,n));document.querySelectorAll('.intake-group').forEach((el,i)=>el.hidden=i!==step);$('intake-prev').disabled=step===0;$('intake-next').disabled=step===5;progress()}
function packet(){return {schema:'dreamco.specialist_intake.v1',createdAt:new Date().toISOString(),requestedProfile:profile.slug,profileName:profile.name,routeRegistered:profile.routeRegistered,status:'prepared_not_executed',mission:profile.mission,sources:profile.sources,answers:questions.map(q=>({question:q.text,answer:$('answer-'+q.id).value.trim()})),executionEvidence:null}}
function promptFrom(p){return `Specialist request: ${p.profileName} (${p.requestedProfile}).\nMission: ${p.mission}\n\n${p.answers.filter(x=>x.answer).map(x=>x.question+'\n'+x.answer).join('\n\n')}\n\nUse the provided answers as task context. Report what can be performed with currently configured tools. Do not claim completion without execution evidence. Identify missing inputs or integrations. This intake does not authorize purchases, payments, hardware operation, or medical experiments.`}
function prepare(){const p=packet();$('intake-brief').value=promptFrom(p);$('intake-handoff').hidden=false;$('intake-route-status').textContent=profile.routeRegistered?'This profile appears in the committed Buddy fleet catalog. Open Buddy to review and send; runtime availability still depends on configuration.':'This is an additional source role, not a verified Buddy fleet route. Buddy will receive a planning request for this specialist.';return p}
try{const response=await fetch(new URL('data/bot-intake-profiles.json',import.meta.url));if(!response.ok)throw Error('Profile data unavailable');const data=await response.json();profile=data.profiles.find(p=>p.slug===slug);if(!profile)throw Error('Unknown profile');questions=questionsFor(profile);
app.innerHTML=`<section class="profile-summary"><div><p class="eyebrow">DECLARED SPECIALIZATION</p><div class="profile-tags">${profile.capabilities.map(c=>`<span>${esc(c)}</span>`).join('')}</div><p>30 intake questions tailored to this profile's mission, capabilities, and domain. Answer only what is useful; skip personal information and never enter passwords or API keys.</p></div><div><p class="eyebrow">SOURCE & EXECUTION STATUS</p><p>${profile.routeRegistered?'Registered in the committed fleet catalog.':'Additional source role; fleet routing is not evidenced.'} A declared capability is not proof of an operational model, connected API, or completed work.</p><div class="profile-sources">${profile.sources.map(s=>`<a href="https://github.com/DreamCo-Technologies/Dreamcobots/blob/main/${encodeURI(s)}" target="_blank" rel="noopener">${esc(s)} ↗</a>`).join('<br>')}</div></div></section><section><p id="intake-count" role="status"></p><div class="intake-progress"><span id="intake-progress-bar"></span></div><div class="intake-controls"><button class="button outline" id="intake-prev">← Previous 5</button><button class="button outline" id="intake-next">Next 5 →</button><button class="button outline" id="intake-save">Save on this device</button><button class="button outline" id="intake-export">Export answers ↓</button><button class="button primary" id="intake-prepare">Prepare Buddy handoff ↗</button></div><p id="intake-storage" role="status" class="quiet">Answers stay in this page unless you choose Save, Export, or Open Buddy.</p><form id="intake-form">${Array.from({length:6},(_,i)=>`<fieldset class="intake-group" ${i?'hidden':''}><legend>${i+1}. ${i===0?'Your purpose':i<3?'Capabilities and context':i<5?'Domain requirements':'Delivery and review'}</legend>${questions.slice(i*5,i*5+5).map((q,j)=>`<label class="intake-question"><span>QUESTION ${i*5+j+1} / 30 · ${esc(q.section)}</span>${esc(q.text)}<textarea id="answer-${q.id}" data-question="${q.id}" maxlength="1500" rows="3" placeholder="Optional — add relevant context, or leave unknown."></textarea></label>`).join('')}</fieldset>`).join('')}</form></section><section class="profile-handoff" id="intake-handoff" hidden><h2>Your specialist handoff</h2><p id="intake-route-status"></p><textarea id="intake-brief" rows="9" readonly></textarea><button class="button primary" id="intake-open">Open Buddy with this brief ↗</button><p>Opening Buddy pre-fills a request. It does not automatically start a task or prove that a specialist executed anything.</p></section>`;
const key='dreamco.intake.'+slug;
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.answers){for(const q of questions)if(typeof saved.answers[q.id]==='string')$('answer-'+q.id).value=saved.answers[q.id];$('intake-storage').textContent='Restored your saved draft from this device.'}}catch{}
$('intake-form').addEventListener('submit',e=>e.preventDefault());$('intake-form').addEventListener('input',progress);$('intake-prev').addEventListener('click',()=>showStep(step-1));$('intake-next').addEventListener('click',()=>showStep(step+1));$('intake-save').addEventListener('click',()=>{try{localStorage.setItem(key,JSON.stringify({savedAt:new Date().toISOString(),answers:answers()}));$('intake-storage').textContent='Draft saved on this device.'}catch{$('intake-storage').textContent='Storage unavailable. Export your answers to retain them.'}});$('intake-export').addEventListener('click',()=>download(slug+'-intake.json',packet()));$('intake-prepare').addEventListener('click',prepare);$('intake-open').addEventListener('click',()=>{const p=prepare();try{localStorage.setItem('dreamco.buddy.intake-handoff',JSON.stringify({createdAt:Date.now(),prompt:promptFrom(p)}));location.href=new URL('buddy.html?intake=1'+(profile.routeRegistered?'&bot='+encodeURIComponent(profile.slug):''),import.meta.url).href}catch{$('intake-route-status').textContent='Browser storage is unavailable. Copy the prepared brief into Buddy manually.'}});showStep(0);
}catch(error){app.textContent='This intake could not load: '+error.message+'. Return to the specialist directory to try again.'}
