(() => {
  'use strict';
  const KEY = 'dreamco.collection_vault.v1';
  const list = document.getElementById('vault-list');
  const status = document.getElementById('vault-status');
  const getItems = () => { try { return JSON.parse(localStorage.getItem(KEY) || '[]'); } catch { return []; } };
  const saveItems = (items) => localStorage.setItem(KEY, JSON.stringify(items));
  const meta = () => ({ folder: document.getElementById('vault-folder').value.trim() || 'Inbox', tags: document.getElementById('vault-tags').value.split(',').map(v=>v.trim()).filter(Boolean), project: document.getElementById('vault-project').value.trim(), privacy: document.getElementById('vault-privacy').value });
  const add = (item) => { const items = getItems(); items.unshift({ id: crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`, createdAt: new Date().toISOString(), ...meta(), ...item }); saveItems(items); render(); };
  function render() { const q = document.getElementById('vault-search').value.trim().toLowerCase(); const items = getItems().filter((item)=>!q || JSON.stringify(item).toLowerCase().includes(q)); list.innerHTML = items.map(item => `<article class="vault-item"><strong>${escapeHtml(item.title || item.name || item.type)}</strong><br><small>${escapeHtml(item.type)} · ${escapeHtml(item.folder || 'Inbox')} · ${new Date(item.createdAt).toLocaleString()}</small><p>${escapeHtml(item.note || item.body || item.url || item.mime || '')}</p><small>${(item.tags||[]).map(escapeHtml).join(' · ')}</small></article>`).join('') || '<p>No matching saved items yet.</p>'; status.textContent = `${items.length} item${items.length===1?'':'s'} shown.`; }
  function escapeHtml(value){ return String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  document.getElementById('add-files').addEventListener('click',()=>{ const files=[...document.getElementById('vault-files').files]; if(!files.length){status.textContent='Choose one or more files first.';return;} files.forEach(file=>add({type:'file',name:file.name,title:file.name,mime:file.type||'unknown',size:file.size,lastModified:file.lastModified,note:'Cataloged locally; file bytes are not persisted by this prototype.'})); status.textContent=`Added ${files.length} file record(s).`; });
  document.getElementById('add-note').addEventListener('click',()=>{ const title=document.getElementById('note-title').value.trim()||'Untitled note'; const body=document.getElementById('note-body').value.trim(); if(!body){status.textContent='Write a note first.';return;} add({type:'note',title,body}); document.getElementById('note-body').value=''; });
  document.getElementById('add-link').addEventListener('click',()=>{ const url=document.getElementById('link-url').value.trim(); if(!url){status.textContent='Enter a link first.';return;} add({type:'link',title:document.getElementById('link-title').value.trim()||url,url,note:document.getElementById('link-note').value.trim()}); });
  document.getElementById('app-import').addEventListener('click',()=>{ const app=document.getElementById('app-name').value.trim(); const route=document.getElementById('app-route').value; location.href=`buddy.html?prompt=${encodeURIComponent(`Prepare an authorized collection import from ${app||'an app'} using ${route}. Ask me which categories, files, photos, videos, audio, charts, notes, exports, or records I want. Reuse Data and Memory Center permissions, avoid scraping private data, catalog provenance, and save selected results into Buddy Collection Vault.`)}`; });
  document.getElementById('vault-search').addEventListener('input',render);
  document.getElementById('export-index').addEventListener('click',()=>{ const blob=new Blob([JSON.stringify({schema:'dreamco.collection_vault.export.v1',exportedAt:new Date().toISOString(),items:getItems()},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='buddy-collection-vault.json'; a.click(); URL.revokeObjectURL(a.href); });
  document.getElementById('clear-vault').addEventListener('click',()=>{ if(confirm('Clear this local Buddy Collection Vault catalog?')){localStorage.removeItem(KEY);render();} });
  document.getElementById('ask-buddy').addEventListener('click',()=>{ const summary=getItems().slice(0,50).map(x=>({type:x.type,title:x.title||x.name,folder:x.folder,tags:x.tags,project:x.project})); location.href=`buddy.html?prompt=${encodeURIComponent(`Help me organize my Buddy Collection Vault. Here is a metadata-only summary of up to 50 locally cataloged items: ${JSON.stringify(summary)}. Suggest folders, tags, projects, duplicates to review, and next actions. Do not assume access to file contents unless I explicitly share them.`)}`; });
  render();
})();