const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let viewer,catalog,features,limit=18,area='user',currentView='invent',selectedBot=null,lastPlan=null,repoLoaded=false,refreshing=false;
const labels={invent:'Invention lab',specialists:'Specialist fleet',tools:'All tools & features',project:'Plan a project',overview:'Project overview',build:'Build desk & resources'};
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,3500)}
function show(view,updateURL=true){if(!labels[view])view='invent';currentView=view;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!=='view-'+view);document.querySelectorAll('.rail [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('breadcrumb').textContent=(area==='owner'?'OWNER':'WORKSPACE')+' / '+labels[view].toUpperCase();if(updateURL)history.replaceState(null,'','#'+view);if(view==='specialists')renderCatalog();if(view==='tools')renderFeatures();if(view==='overview'&&!repoLoaded){refreshRepo();loadReadiness()}window.scrollTo({top:0,behavior:'instant'})}
function setArea(value){area=value;document.querySelectorAll('[data-area]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.area===area)));$('area-description').textContent=area==='owner'?'Owner view · public project data':'Public browser workspace';$('feature-area').value=area;show(area==='owner'?'overview':'invent')}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));document.querySelectorAll('[data-area]').forEach(b=>b.addEventListener('click',()=>setArea(b.dataset.area)));
window.addEventListener('hashchange',()=>show(location.hash.slice(1),false));
function download(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function onViewer(s){if(s.progress!==undefined){$('explode').value=100-s.progress;$('explode-value').textContent=(100-s.progress)+'%';$('assembly-status').textContent='Assembly sequence · '+s.progress+'%';return}if(s.robotStatus){$('robot-status').textContent=s.robotStatus;return}if(!s.parts)return;$('part-select').innerHTML=s.parts.map(p=>`<option value="${esc(p.id)}">${String(p.step).padStart(2,'0')} · ${esc(p.name)}</option>`).join('');$('part-select').value=s.selected;$('part-name').textContent=s.p.name;$('part-description').textContent=s.p.description;$('part-number').textContent=String(s.p.step).padStart(2,'0')+' / '+s.parts.length;$('part-specs').innerHTML=`<div><dt>Assembly order</dt><dd>${s.p.step} of ${s.parts.length}</dd></div><div><dt>Connection</dt><dd>${esc(s.p.connection)}</dd></div><div><dt>Build specification</dt><dd>Concept only</dd></div>`;$('explode').value=Math.round(s.explode*100);$('explode-value').textContent=Math.round(s.explode*100)+'%';$('rotate').setAttribute('aria-pressed',String(s.rotating));$('rotate').textContent=s.rotating?'Pause rotation':'Rotate model';$('interior').setAttribute('aria-pressed',String(s.interior));$('wireframe').setAttribute('aria-pressed',String(s.wire));$('isolate').setAttribute('aria-pressed',String(s.isolated));$('isolate').textContent=s.isolated?'Show all parts':'Isolate part';$('assembly-status').textContent=s.assembling?'Playing component assembly…':'Explore how the components fit together.';$('robot-controls').hidden=s.model!=='robot';$('interior').disabled=!['spacecraft','rocket'].includes(s.model);$('model-label').textContent={spacecraft:'ASTER / EXPLORATION VEHICLE',robot:'ATLAS / ROBOTICS MOTION LAB',drone:'AERO / SURVEY PLATFORM',rocket:'NOVA / ROCKET CONCEPT',research:'HELIX / RESEARCH INSTRUMENT'}[s.model];$('model-viewport').setAttribute('aria-label',`Interactive 3D ${s.model}. Use camera buttons and the component selector as a keyboard alternative.`);document.querySelectorAll('[data-model]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.model===s.model)))}
async function startViewer(){try{const {createInventionViewer}=await import('./invention-viewer.js');viewer=createInventionViewer($('model-viewport'),onViewer);$('viewer-message').hidden=true}catch(e){$('viewer-message').textContent='3D viewing is unavailable in this browser. Try a browser with WebGL enabled. The specialist fleet and all existing tools are still available.';document.querySelectorAll('.viewport-side button,.view-controls button,.inspector button,.inspector input,.inspector select,[data-model]').forEach(b=>b.disabled=true);console.error('3D viewer unavailable',e)}}
for(const [id,fn]of Object.entries({'zoom-in':()=>viewer?.zoom(.8),'zoom-out':()=>viewer?.zoom(1.25),'reset-camera':()=>viewer?.reset(),rotate:()=>viewer?.toggleRotate(),interior:()=>viewer?.toggleInterior(),wireframe:()=>viewer?.toggleWire(),isolate:()=>viewer?.toggleIsolate(),'focus-part':()=>viewer?.focus(),assemble:()=>viewer?.assemble(),'export-concept':()=>viewer&&download('dreamco-concept.json',viewer.snapshot()),'export-cad':()=>viewer&&saveText('dreamco-concept-scene-units.obj',viewer.exportOBJ(),'text/plain')}))$(id).addEventListener('click',fn);
document.querySelectorAll('[data-model]').forEach(b=>b.addEventListener('click',()=>viewer?.setModel(b.dataset.model)));$('part-select').addEventListener('change',e=>viewer?.select(e.target.value));$('explode').addEventListener('input',e=>viewer?.setExplode(Number(e.target.value)/100));
function target(){const v=['x','y','z'].map(a=>{const n=Number($('target-'+a).value);$('target-'+a+'-value').textContent=n.toFixed(1);return n});const ok=viewer?.target(v);$('robot-status').textContent=ok?'Target reachable in this simplified kinematic model.':'Target is outside the arm’s geometric reach. Try a closer position.'}
for(const a of ['x','y','z'])$('target-'+a).addEventListener('input',target);$('robot-run').addEventListener('click',()=>{viewer?.runRobot();$('robot-status').textContent='Running a predefined pick-and-place demonstration…'});$('robot-stop').addEventListener('click',()=>{viewer?.stopRobot();$('robot-status').textContent='Stopped. Demonstration reset; no hardware controlled.'});
async function json(path){const r=await fetch(path);if(!r.ok)throw Error('Data unavailable');return r.json()}
function card(b){return `<button class="bot-card" data-bot="${esc(b.slug)}"><span class="card-top"><span class="bot-monogram">${esc(b.name.slice(0,2).toUpperCase())}</span><span aria-hidden="true">↗</span></span><h3>${esc(b.name)}</h3><p>${esc(b.mission)}</p><span class="card-bottom"><span class="tag">${esc(b.division)}</span><span>${b.capabilities.length} capabilities</span></span></button>`}
function filtered(){if(!catalog)return[];const q=$('search').value.trim().toLowerCase(),d=$('division').value;let rows=catalog.bots.filter(b=>(!d||b.division===d)&&(!q||`${b.name} ${b.mission} ${b.capabilities.join(' ')}`.toLowerCase().includes(q)));if($('sort').value!=='featured')rows.sort((a,b)=>a.name.localeCompare(b.name)*($('sort').value==='za'?-1:1));return rows}
function renderCatalog(){if(!catalog)return;const rows=filtered();$('result-count').textContent=`${rows.length.toLocaleString()} profiles · showing ${Math.min(limit,rows.length)}`;$('catalog').innerHTML=rows.length?rows.slice(0,limit).map(card).join(''):'<div class="empty-state">No specialists match. Try a different skill or clear the filters.</div>';$('load-more').hidden=limit>=rows.length}
function detail(slug){const b=catalog?.bots.find(b=>b.slug===slug);if(!b)return;selectedBot=b;$('bot-detail').innerHTML=`<span class="bot-monogram">${esc(b.name.slice(0,2).toUpperCase())}</span><p class="eyebrow detail-heading">${esc(b.division)}</p><h2 id="detail-title">${esc(b.name)}</h2><p class="detail-mission">${esc(b.mission)}</p><h3>Declared capabilities</h3><ul class="cap-list">${b.capabilities.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><p class="notice">This is a specialist profile. Live model calls and external integrations require a configured, approved backend.</p><div class="detail-actions"><a class="button primary" href="bot-pages/${encodeURIComponent(b.slug)}.html">My page · 30 questions ↗</a><a class="button outline" href="buddy.html?bot=${encodeURIComponent(b.slug)}">Open with Buddy ↗</a><a class="button outline" href="calculator.html?bot=${encodeURIComponent(b.slug)}">Planning calculator</a><a class="button outline" href="bots.html?prospectus=${encodeURIComponent(b.slug)}">Full prospectus</a></div>`;$('bot-dialog').showModal()}
$('catalog').addEventListener('click',e=>{const b=e.target.closest('[data-bot]');if(b)detail(b.dataset.bot)});$('bot-dialog').querySelector('.dialog-close').addEventListener('click',()=>$('bot-dialog').close());$('bot-dialog').addEventListener('click',e=>{if(e.target===$('bot-dialog'))$('bot-dialog').close()});['search','division','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{limit=18;renderCatalog()}));$('load-more').addEventListener('click',()=>{limit+=18;renderCatalog()});$('clear-filters').addEventListener('click',()=>{$('search').value='';$('division').value='';$('sort').value='featured';limit=18;renderCatalog()});
function renderFeatures(){if(!features)return;const q=$('feature-search').value.toLowerCase(),a=$('feature-area').value,rows=features.filter(f=>(a==='all'||f.area===a)&&`${f.name} ${f.description}`.toLowerCase().includes(q));$('feature-count').textContent=`${rows.length} of ${features.length} preserved feature pages`;$('feature-grid').innerHTML=rows.length?rows.map(f=>`<a class="tool-card feature-card" href="${esc(f.href)}"><span class="feature-area">${f.area==='owner'?'Owner command center':'User workspace'}</span><h3>${esc(f.name)}</h3><p>${esc(f.description)}</p><span>Open workspace ↗</span></a>`).join(''):'<p class="empty-state">No matching tools. Try a different name or area.</p>'}
$('feature-search').addEventListener('input',renderFeatures);$('feature-area').addEventListener('change',renderFeatures);
$('plan-form').addEventListener('submit',e=>{e.preventDefault();const objective=$('objective').value.trim();if(!objective)return;const words=objective.toLowerCase().split(/\W+/).filter(w=>w.length>3);const matches=(catalog?.bots||[]).map(b=>({b,score:words.reduce((s,w)=>s+(`${b.name} ${b.mission} ${b.capabilities.join(' ')}`.toLowerCase().includes(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>x.b);lastPlan={objective,mode:'browser-local concept brief',specialists:matches.map(b=>({slug:b.slug,name:b.name})),steps:['Define the intended user, use case, and observable success criteria.','List required components, constraints, unknowns, and evidence needed.','Prototype one bounded interaction with synthetic or owner-supplied inputs.','Test the prototype and record failures before considering real-world use.'],engineeringBoundary:'Concept only. Obtain validated CAD, materials, fastener specifications, analysis and qualified review before fabrication.'};$('plan-result').innerHTML=`<h3>Your project brief</h3><p>${esc(objective)}</p><ol>${lastPlan.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="plan-specialists">${matches.map(b=>`<button data-bot="${esc(b.slug)}">${esc(b.name)} ↗</button>`).join('')}</div><div class="detail-actions"><button class="button outline" id="download-plan">Export brief ↓</button><a class="button primary" href="buddy.html?prompt=${encodeURIComponent(objective)}">Continue with Buddy ↗</a></div><p class="quiet">Specialists are matched by keywords. This brief is not an AI-generated engineering design.</p>`;$('plan-result').hidden=false;$('download-plan').addEventListener('click',()=>download('dreamco-project-brief.json',lastPlan));$('plan-result').querySelectorAll('[data-bot]').forEach(b=>b.addEventListener('click',()=>detail(b.dataset.bot)))});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{$('objective').value=b.dataset.prompt;$('objective').focus()}));
async function refreshRepo(){if(refreshing)return;refreshing=true;repoLoaded=true;$('refresh-repo').disabled=true;$('repo-status').textContent='Checking public GitHub workflow activity…';try{const r=await fetch('https://api.github.com/repos/DreamCo-Technologies/Dreamcobots/actions/runs?per_page=8',{headers:{Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(r.status===403||r.status===429?'GitHub rate limit reached':'GitHub unavailable');const data=await r.json();$('workflow-list').innerHTML=(data.workflow_runs||[]).map(run=>{const url=new URL(run.html_url);if(url.origin!=='https://github.com')return '';const status=run.conclusion||run.status;return `<a class="workflow-row" href="${esc(url.href)}" target="_blank" rel="noopener"><strong>${esc(run.name)}</strong><small><span class="${status==='success'?'success':status==='failure'?'failure':''}">${esc(status.replaceAll('_',' '))}</span><span>${esc(new Date(run.updated_at).toLocaleString())}</span></small></a>`}).join('');$('repo-status').textContent='Last checked '+new Date().toLocaleTimeString()+'. Latest 8 runs; not application uptime.'}catch(e){$('repo-status').textContent=e.message+'. Previously loaded runs, if shown, may be stale. Open GitHub for current status.'}finally{refreshing=false;$('refresh-repo').disabled=false}}
$('refresh-repo').addEventListener('click',refreshRepo);setInterval(()=>{if(currentView==='overview'&&!document.hidden&&navigator.onLine)refreshRepo()},120000);
async function loadReadiness(){try{const d=await json('data/master-directive-status.json'),counts=d.summary.status_counts,total=d.summary.directive_sections;$('readiness-bars').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="readiness-row"><div><span>${esc(k.replaceAll('_',' '))}</span><span>${v} / ${total}</span></div><div class="bar-track"><span style="width:${v/total*100}%"></span></div></div>`).join('')}catch{$('readiness-bars').textContent='Readiness evidence unavailable.'}}
Promise.allSettled([json('data/command-center-catalog.json').then(d=>{catalog=d;$('division').innerHTML='<option value="">All 45 divisions</option>'+d.divisions.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} (${x.profile_count})</option>`).join('');renderCatalog()}),json('data/command-center-features.json').then(d=>{features=d.features;$('feature-total').textContent=features.length;renderFeatures()})]).then(results=>{if(results[0].status==='rejected')$('result-count').textContent='Catalog unavailable. Use the existing Bot Fleet page.';if(results[1].status==='rejected')$('feature-count').textContent='Feature directory unavailable. Existing page links remain available.'});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)&&!$('bot-dialog').open){e.preventDefault();show('specialists');$('search').focus()}});
show(location.hash.slice(1)||'invent',false);startViewer();
const context=document.modelContext;if(context?.registerTool){const abort=new AbortController();for(const tool of [{name:'select_invention_component',description:'Select a component in the visible concept viewer; no hardware actions.',inputSchema:{type:'object',properties:{componentId:{type:'string'}},required:['componentId'],additionalProperties:false},execute({componentId}){if(!viewer?.snapshot().parts.some(p=>p.id===componentId))throw Error('Unknown component');show('invent');viewer.select(componentId);return{selected:componentId}}},{name:'search_dreamco_specialists',description:'Search the visible DreamCo specialist catalog. Profiles are not live service claims.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},execute({query}){if(typeof query!=='string'||query.length>300)throw Error('Invalid query');$('search').value=query;$('division').value='';limit=18;show('specialists');return{count:filtered().length,profiles:filtered().slice(0,6).map(b=>({name:b.name,slug:b.slug}))}}}])Promise.resolve(context.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:abort.signal})).catch(()=>{});window.addEventListener('pagehide',()=>abort.abort(),{once:true})}
function saveText(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const resourceItems=[
 {name:'FreeCAD',category:'design',url:'https://www.freecad.org/',description:'Develop parametric mechanical designs and detailed drawings in a dedicated CAD environment.'},
 {name:'OpenSCAD',category:'design',url:'https://openscad.org/',description:'Create programmable solid geometry. Concept meshes exported here are not parametric manufacturing models.'},
 {name:'KiCad',category:'design',url:'https://www.kicad.org/',description:'Create schematics and PCB layouts, inspect boards in 3D, and work with electrical design checks.'},
 {name:'OpenRocket',category:'hardware',url:'https://openrocket.info/',description:'Explore model-rocket design and flight simulation using a dedicated simulator. The spacecraft showcase here is conceptual.'},
 {name:'McMaster-Carr',category:'hardware',url:'https://www.mcmaster.com/',description:'Consult supplier part listings and specifications after an appropriate part requirement has been established. No purchase is initiated here.'},
 {name:'FDA drug development process',category:'medicine',url:'https://www.fda.gov/patients/learn-about-drug-and-device-approvals/drug-development-process',description:'Follow the research pathway from discovery and preclinical work through clinical research, review, and post-market monitoring. A concept is not a new validated medicine.'},
 {name:'Idea-to-Store navigator',category:'launch',url:'buddy-invention-lab.html',description:'Reuse DreamCo’s existing invention, IP, compliance, funding, manufacturing, and launch planning resources.'},
 {name:'Manufacturer marketplace',category:'launch',url:'manufacturer-marketplace.html',description:'Explore the existing manufacturing research and sourcing workspace. Supplier contact and orders require approval.'},
 {name:'Resource connections',category:'launch',url:'resource-connection-center.html',description:'Prepare a governed connection plan for existing resources. A planned connection is not a live integration.'}
];
function renderResources(){const filter=$('resource-filter').value;$('resource-grid').innerHTML=resourceItems.filter(r=>filter==='all'||r.category===filter).map(r=>`<a class="tool-card feature-card" href="${esc(r.url)}" ${r.url.startsWith('https:')?'target="_blank" rel="noopener"':''}><span class="feature-area">${esc(r.category)}</span><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><span>Open resource ↗</span></a>`).join('')}$('resource-filter').addEventListener('change',renderResources);renderResources();
let buildSnapshot,ledger={};try{const saved=JSON.parse(localStorage.getItem('dreamco.invention.part-drafts.v1')||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))ledger=saved}catch{}
function fillPart(){if(!buildSnapshot)return;const id=$('build-part').value,p=buildSnapshot.parts.find(p=>p.id===id),entry=ledger[buildSnapshot.model+':'+id]||{};for(const el of $('part-form').elements){if(el.name)el.value=entry[el.name]??(el.name==='quantity'?1:'')}$('part-ledger-status').textContent=entry.savedAt?'Draft saved on this device: '+new Date(entry.savedAt).toLocaleString()+'. Unverified.':p.connection+' · No verified specification supplied.';$('build-assembly').innerHTML=buildSnapshot.parts.map(p=>`<div class="assembly-step ${p.id===id?'active':''}"><button data-ledger-part="${esc(p.id)}">${String(p.assemblyStep).padStart(2,'0')} · ${esc(p.name)}</button></div>`).join('');$('build-assembly').querySelectorAll('[data-ledger-part]').forEach(b=>b.addEventListener('click',()=>{$('build-part').value=b.dataset.ledgerPart;fillPart()}))}
$('load-model-parts').addEventListener('click',()=>{if(!viewer)return toast('The 3D viewer is not available.');buildSnapshot=viewer.snapshot();$('build-part').innerHTML=buildSnapshot.parts.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');fillPart()});$('build-part').addEventListener('change',fillPart);
$('part-form').addEventListener('submit',e=>{e.preventDefault();if(!buildSnapshot)return toast('Load a prototype before saving a part.');const row=Object.fromEntries(new FormData(e.target));row.quantity=Number(row.quantity);row.status='owner_entered_unverified';row.savedAt=new Date().toISOString();ledger[buildSnapshot.model+':'+$('build-part').value]=row;try{localStorage.setItem('dreamco.invention.part-drafts.v1',JSON.stringify(ledger));fillPart();toast('Draft specification saved on this device.')}catch{toast('Browser storage unavailable. Export the ledger to keep your draft.')}});
$('export-bom').addEventListener('click',()=>{if(!buildSnapshot)return toast('Load a prototype first.');download('dreamco-parts-ledger.json',{schema:'dreamco.parts_ledger.v1',model:buildSnapshot.model,boundary:buildSnapshot.boundary,parts:buildSnapshot.parts.map(p=>({...p,specification:ledger[buildSnapshot.model+':'+p.id]||{status:'unspecified',quantity:null,dimensions:null,thread:null,torque:null,sourceUrl:null}})),engineeringApproval:false,manufacturingStarted:false,resources:resourceItems})});
