/* Fleet runtime truth dashboard. Reads data/fleet-runtime-status.json (generated by tools/fleet_runtime_audit.py). */
(function () {
  'use strict';
  const REPO = 'https://github.com/DreamCo-Technologies/Dreamcobots/blob/main/';
  const PAGE = 200;
  const byId = (id) => document.getElementById(id);
  const esc = (v) => String(v == null ? '' : v).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const state = { data: null, rows: [], filtered: [], shown: PAGE, meta: null, cards: null, wfQuery: '' };
  const BR = window.BuddyRun;

  function testsText(t) {
    if (!t) return '—';
    if (!t.ran) return 'not run' + (t.reason ? ' (' + esc(t.reason) + ')' : '');
    if (t.timeout) return 'timeout';
    return (t.passed || 0) + ' passed, ' + ((t.failed || 0) + (t.errors || 0)) + ' failed';
  }

  function renderTotals(data) {
    const totals = data.summary.by_state;
    byId('fr-state-totals').innerHTML = data.states.map((s) =>
      '<div><span>' + esc(s) + '</span><strong class="fr-state-' + esc(s) + (totals[s] ? '' : ' is-zero') + '">' + (totals[s] || 0) + '</strong></div>').join('');
  }

  function renderDivisions(data) {
    const table = byId('fr-division-table');
    table.tHead.innerHTML = '<tr><th>Division</th>' + data.states.map((s) => '<th>' + esc(s) + '</th>').join('') + '<th>Total</th></tr>';
    table.tBodies[0].innerHTML = Object.entries(data.summary.by_division).map(([name, counts]) =>
      '<tr><td><a href="#" data-division="' + esc(name) + '">' + esc(name) + '</a> · <a href="#division-' + esc(name) + '">card</a></td>' +
      data.states.map((s) => '<td class="num">' + (counts[s] || 0) + '</td>').join('') + '<td class="num">' + counts.total + '</td></tr>').join('');
    table.addEventListener('click', (event) => {
      const link = event.target.closest('a[data-division]');
      if (!link) return;
      event.preventDefault();
      byId('fr-division-filter').value = link.dataset.division;
      applyFilters();
      byId('fr-bots-title').scrollIntoView({ behavior: 'smooth' });
    });
  }

  function botRow(row) {
    const pieces = state.data.contract_pieces;
    const missing = row.missing.map((i) => '<span class="fr-chip">' + esc(pieces[i]) + '</span>').join('');
    const flags = row.flags.map((f) => '<span class="fr-chip">' + esc(f) + '</span>').join('');
    const spec = '<a href="' + REPO + 'bots/' + encodeURIComponent(row.slug) + '.md">spec</a>';
    const prospectus = row.division !== 'UNASSIGNED' ? ' · <a href="bots.html?prospectus=' + encodeURIComponent(row.slug) + '">prospectus</a>' : '';
    const card = state.cards && state.meta ? BR.resolveBot(state.cards.get(row.slug), state.meta) : null;
    const run = card ? BR.runControls(card) + '<details class="br-custom-details"><summary>Customize</summary>' + BR.botCustomizeForm(card, state.meta.customize) + '</details>'
      : (state.cards ? '<span class="br-missing">no prospectus</span>' : '<span class="fr-note">loading…</span>');
    return '<tr id="bot-' + esc(row.slug) + '"><td><strong>' + esc(row.name) + '</strong><br><code>' + esc(row.slug) + '</code></td>' +
      '<td>' + esc(row.division) + '</td><td>' + esc(row.engine) + '</td>' +
      '<td><span class="fr-state fr-state-' + esc(row.state) + '">' + esc(row.state) + '</span></td>' +
      '<td><div class="fr-chips">' + (missing || '—') + '</div></td><td><div class="fr-chips">' + (flags || '—') + '</div></td>' +
      '<td>' + spec + prospectus + '</td><td class="br-cell">' + run + '</td></tr>';
  }

  function renderBots() {
    const visible = state.filtered.slice(0, state.shown);
    byId('fr-bot-table').tBodies[0].innerHTML = visible.map(botRow).join('');
    byId('fr-result-count').textContent = state.filtered.length + ' of ' + state.rows.length + ' bots';
    byId('fr-more').hidden = state.filtered.length <= state.shown;
  }

  function applyFilters() {
    const q = byId('fr-search').value.trim().toLowerCase();
    const st = byId('fr-state-filter').value;
    const div = byId('fr-division-filter').value;
    const eng = byId('fr-engine-filter').value;
    state.filtered = state.rows.filter((r) =>
      (!st || r.state === st) && (!div || r.division === div) && (!eng || r.engine === eng) &&
      (!q || (r.slug + ' ' + r.name + ' ' + r.division + ' ' + r.engine + ' ' + r.flags.join(' ')).toLowerCase().includes(q)));
    state.shown = PAGE;
    renderBots();
  }

  function fillSelect(id, values) {
    byId(id).insertAdjacentHTML('beforeend', values.map((v) => '<option value="' + esc(v) + '">' + esc(v) + '</option>').join(''));
  }

  function renderFolders(data) {
    byId('fr-folder-table').tBodies[0].innerHTML = data.code_folders.map((f) => {
      const imp = f.import_probe ? (f.import_probe.modules - f.import_probe.failed) + '/' + f.import_probe.modules + ' ok' : '—';
      const tc = f.typecheck ? (f.typecheck.ran ? (f.type_errors || 0) + ' errors' : 'not run') : '—';
      return '<tr><td><a href="' + REPO + esc(f.folder) + '">' + esc(f.folder) + '</a></td><td class="fr-verdict-' + esc(f.verdict) + '"><strong>' + esc(f.verdict) + '</strong></td>' +
        '<td class="num">' + (f.code_files || 0) + '</td><td>' + imp + '</td><td>' + testsText(f.tests) + '</td><td>' + testsText(f.node_tests) + '</td><td>' + tc + '</td></tr>';
    }).join('');
  }

  function renderWorkflows() {
    const meta = state.meta;
    if (!meta) return;
    const q = state.wfQuery.toLowerCase();
    const cards = meta.workflows.filter((c) => !q || (c.id + ' ' + c.title + ' ' + c.does + ' ' + c.risk_tier).toLowerCase().includes(q));
    byId('fr-wf-count').textContent = cards.length + ' of ' + meta.workflows.length + ' workflows · ' + meta.counts.workflow_buttons + ' runnable';
    byId('fr-wf-list').innerHTML = cards.map((c) => '<li id="job-' + esc(c.id) + '"><div><strong>' + esc(c.title) + '</strong> <code>' + esc(c.id) + '</code> <span class="br-tier br-tier-' + esc(c.risk_tier) + '">' + esc(c.risk_tier) + '</span></div>' + BR.runControls(c) + '</li>').join('');
  }

  function renderDivisionCards() {
    const meta = state.meta;
    if (!meta || !meta.divisions) return;
    const audited = new Map((state.data.divisions || []).map((d) => [d.name, d]));
    byId('fr-div-cards').innerHTML = meta.divisions.map((c) => {
      const name = c.id.slice('division:'.length);
      const a = audited.get(name) || {};
      return '<article class="fr-div-card" id="division-' + esc(name) + '"><h3>' + esc(name) + ' <span class="fr-state fr-state-' + esc(c.readiness.state) + '">' + esc(c.readiness.state) + '</span></h3>' +
        '<p>' + esc(c.bots) + ' bots · ' + esc(c.runnable_bots) + ' runnable · smoke: ' + esc((c.smoke_bots || []).join(', ') || 'none') + ' — ' + (a.smoke_passed ? 'passed' : 'not passed') + '</p>' +
        '<p class="fr-note"><a href="#" data-division="' + esc(name) + '">show bots</a> · <a href="divisions.html">division directory</a> · <a href="' + esc(c.links.source) + '" rel="noopener">division source</a></p>' +
        BR.runControls(c) + '<details class="br-custom-details"><summary>Customize division</summary>' + BR.divisionCustomizeForm(c, meta.customize) + '</details></article>';
    }).join('');
    byId('fr-div-cards').addEventListener('click', (event) => {
      const link = event.target.closest('a[data-division]');
      if (!link) return;
      event.preventDefault();
      byId('fr-division-filter').value = link.dataset.division;
      applyFilters();
      byId('fr-bots-title').scrollIntoView({ behavior: 'smooth' });
    });
    const m = /^#division-(.+)$/.exec(location.hash || '');
    if (m) { const el = document.getElementById('division-' + decodeURIComponent(m[1])); if (el) el.scrollIntoView({ block: 'start' }); }
  }

  function renderLinks(data) {
    const l = data.links;
    byId('fr-links-summary').textContent = l.links_checked + ' internal links/routes checked across ' + l.files_scanned + ' files; ' + l.broken_count + ' broken; ' + l.server_api_refs.length + ' server-only /api references (need the DreamCo server, not static Pages).';
    byId('fr-links-broken').innerHTML = l.broken.slice(0, 200).map((b) => '<li><code>' + esc(b.source) + '</code> → <code>' + esc(b.href) + '</code></li>').join('');
  }

  function focusHash() {
    const slug = decodeURIComponent((location.hash || '').replace(/^#bot-/, ''));
    if (!slug || slug === location.hash) return;
    const idx = state.rows.findIndex((r) => r.slug === slug);
    if (idx < 0) return;
    byId('fr-search').value = slug;
    applyFilters();
    const el = document.getElementById('bot-' + slug);
    if (el) el.scrollIntoView({ block: 'center' });
  }

  function init(data) {
    state.data = data;
    const cols = data.bot_columns;
    state.rows = data.bots.map((b) => Object.fromEntries(cols.map((c, i) => [c, b[i]])));
    renderTotals(data);
    renderDivisions(data);
    fillSelect('fr-state-filter', data.states);
    fillSelect('fr-division-filter', Object.keys(data.summary.by_division));
    fillSelect('fr-engine-filter', Object.keys(data.summary.by_engine));
    ['fr-search', 'fr-state-filter', 'fr-division-filter', 'fr-engine-filter'].forEach((id) => byId(id).addEventListener('input', applyFilters));
    byId('fr-more').addEventListener('click', () => { state.shown += PAGE; renderBots(); });
    state.filtered = state.rows;
    renderBots();
    renderFolders(data);
    renderLinks(data);
    focusHash();
    window.addEventListener('hashchange', focusHash);
    BR.wireCustomize(document.body);
    BR.loadMeta().then((meta) => {
      state.meta = meta;
      renderWorkflows();
      renderDivisionCards();
      byId('fr-wf-search').addEventListener('input', (e) => { state.wfQuery = e.target.value.trim(); renderWorkflows(); });
      return BR.loadBots();
    }).then((cards) => { state.cards = cards; renderBots(); })
      .catch((err) => { byId('fr-wf-count').textContent = 'Run prospectus unavailable: ' + err.message; });
  }

  fetch('data/fleet-runtime-status.json', { cache: 'no-cache' })
    .then((r) => { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })
    .then(init)
    .catch((err) => {
      byId('fr-state-totals').innerHTML = '<div><span>Status unavailable</span><strong>' + esc(err.message) + '</strong></div>';
    });
})();
