import * as T from './vendor/three/three.module.js';
import {OrbitControls} from './vendor/three/OrbitControls.js';
import {detailInvention} from './invention-detail.js';
import {solveArmTarget} from './invention-kinematics.js';
export function createInventionViewer(container,onChange) {
 const scene=new T.Scene(), camera=new T.PerspectiveCamera(40,1,.1,150), renderer=new T.WebGLRenderer({antialias:true,alpha:true});
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 container.append(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=3;controls.maxDistance=26;controls.maxPolarAngle=Math.PI*.9;controls.autoRotate=!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.autoRotateSpeed=.7;
 scene.add(new T.HemisphereLight(0xb5e9ff,0x10251e,2.1));const key=new T.DirectionalLight(0xffffff,3.5);key.position.set(-6,10,-5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-10;key.shadow.camera.right=10;key.shadow.camera.top=10;key.shadow.camera.bottom=-10;scene.add(key);const rim=new T.DirectionalLight(0x70f7d6,3);rim.position.set(7,3,6);scene.add(rim);const fill=new T.DirectionalLight(0x7994ff,2);fill.position.set(-7,0,4);scene.add(fill);
 const grid=new T.GridHelper(30,40,0x245e65,0x162b3a);grid.position.y=-2.15;grid.material.transparent=true;grid.material.opacity=.4;scene.add(grid);
 const starGeo=new T.BufferGeometry(),starPoints=[];let seed=73;for(let i=0;i<350;i++){seed=(seed*16807)%2147483647;let a=seed/2147483647*6.28;seed=(seed*16807)%2147483647;let b=(seed/2147483647-.5)*2;starPoints.push(Math.cos(a)*35,b*25,Math.sin(a)*35)}starGeo.setAttribute('position',new T.Float32BufferAttribute(starPoints,3));scene.add(new T.Points(starGeo,new T.PointsMaterial({color:0xaccadc,size:.045,transparent:true,opacity:.65})));
 let root,parts=[],selected,model='spacecraft',explode=0,assembly=null,interior=false,isolated=false,wire=false,robot=null,robotRun=null,rotors=[],last=performance.now(),visible=true;
 const ray=new T.Raycaster(),pointer=new T.Vector2();
 function mat(color,metal=.55,rough=.36){return new T.MeshStandardMaterial({color,metalness:metal,roughness:rough})}
 function mesh(g,geometry,material,pos=[0,0,0],rot=[0,0,0]){const m=new T.Mesh(geometry,material.clone());m.position.set(...pos);m.rotation.set(...rot);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
 function box(g,size,pos,material){return mesh(g,new T.BoxGeometry(...size),material,pos)}
 function cylinder(g,r1,r2,h,pos,m,rot=[0,0,0]){return mesh(g,new T.CylinderGeometry(r1,r2,h,32),m,pos,rot)}
 function part(id,name,description,offset,connection='Conceptual mounting interface',shell=false){const g=new T.Group();root.add(g);const p={id,name,description,offset:new T.Vector3(...offset),group:g,origin:g.position.clone(),connection,shell,step:parts.length+1};parts.push(p);return p}
 function annotate(){parts.forEach(p=>{p.origin.copy(p.group.position);p.group.traverse(o=>{if(o.isMesh){o.userData.part=p.id;o.userData.baseEmissive=o.material.emissive?.clone();o.userData.baseOpacity=o.material.opacity}})})}
 function hull(g,material,y=.1){const sections=[[-4.5,.035,.08],[-3.1,.72,.46],[-1,1.04,.6],[2.5,.98,.54],[3.25,.65,.4]],verts=[],indices=[];sections.forEach(([z,w,h])=>[[-w,h],[w,h],[w,-h],[-w,-h]].forEach(([x,a])=>verts.push(x,a+y,z)));for(let k=0;k<4;k++)for(let j=0;j<4;j++){const a=k*4+j,b=k*4+(j+1)%4,c=b+4,d=a+4;indices.push(a,b,d,b,c,d)}indices.push(0,3,1,1,3,2,16,17,19,17,18,19);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(verts,3));for(let i=0;i<indices.length;i+=3){[indices[i+1],indices[i+2]]=[indices[i+2],indices[i+1]]}geo.setIndex(indices);geo.computeVertexNormals();return mesh(g,geo,material)}
 function wing(g,side,m){const sh=new T.Shape();sh.moveTo(.65*side,-1.5);sh.lineTo(4.1*side,2.7);sh.lineTo(3.4*side,3.4);sh.lineTo(.65*side,2.6);sh.closePath();const geo=new T.ExtrudeGeometry(sh,{depth:.15,bevelEnabled:true,bevelThickness:.05,bevelSize:.05,bevelSegments:1,steps:1});mesh(g,geo,m,[0,.03,0],[Math.PI/2,0,0]);}
 function buildSpacecraft(){const white=mat(0xc2cfdb,.65,.28),dark=mat(0x1a2b3b,.75,.3),trim=mat(0x527485,.8,.3),glow=new T.MeshStandardMaterial({color:0x67eacc,emissive:0x2dcfae,emissiveIntensity:2});
  let p=part('lower-hull','Structural keel','The central reference structure carries the cabin, wings, and propulsion modules. This model shows interfaces, not a flight-qualified load path.',[0,-1.7,0],'Align the keel as the assembly reference');hull(p.group,dark,-.24);p.group.scale.y=.6;
  p=part('cabin','Habitat deck','A visible interior with two concept crew stations, a central passage, and equipment bays. Use Look inside to lift the outer shell.',[0,.9,0],'Place the interior module on the keel');box(p.group,[1.65,.12,5.2],[0,.12,-.2],trim);for(const x of [-.44,.44]){box(p.group,[.38,.5,.38],[x,.43,-2.1],dark);box(p.group,[.4,.07,.55],[x,.26,-2],white);box(p.group,[.42,.25,.35],[x,.42,-2.75],trim);box(p.group,[.32,.03,.2],[x,.56,-2.75],glow)}for(let z=-.6;z<2;z+=.8){box(p.group,[.45,.55,.55],[-.52,.43,z],white);box(p.group,[.45,.55,.55],[.52,.43,z],dark)}
  p=part('upper-shell','Upper pressure shell','The outer fairing separates to reveal the cabin. Panel edges illustrate service access; pressure, thermal and radiation performance are unvalidated.',[0,2.3,0],'Seat the cover over the cabin reference points',true);hull(p.group,white,.8);p.group.scale.y=.65;for(let z=-1.5;z<2.5;z+=.55)box(p.group,[1.5,.025,.025],[0,1.45,z],trim);
  p=part('canopy','Cockpit canopy','A dark transparent canopy provides a concept view of the crew stations. Material thickness and optical performance are unspecified.',[0,2.1,-1.8],'Align with the cockpit opening',true);const glass=new T.MeshPhysicalMaterial({color:0x24485e,metalness:.2,roughness:.15,transparent:true,opacity:.82});const canopy=mesh(p.group,new T.SphereGeometry(1,32,20),glass,[0,.76,-2.2]);canopy.scale.set(.7,.35,1.12);
  for(const side of [-1,1]){p=part(side<0?'port-wing':'starboard-wing',side<0?'Port lifting surface':'Starboard lifting surface','A detachable swept surface with an illustrative structural spar. Aerodynamic and thermal behavior are not simulated.',[side*2.5,.2,.3],'Align spar and wing-root reference points');wing(p.group,side,white);box(p.group,[1.7,.09,.16],[side*2.1,.13,2.65],trim);const fin=box(p.group,[.1,1.1,1.2],[side*3.15,.43,2.6],dark);fin.rotation.z=-side*.2;
   p=part(side<0?'engine-port':'engine-starboard',side<0?'Port propulsion pod':'Starboard propulsion pod','An illustrative engine shell, nozzle, and luminous exhaust. No propulsion, fuel, thrust, or thermal analysis is performed.',[side*2.1,-.1,2.6],'Attach the pod to the aft mounting interface');cylinder(p.group,.42,.5,2.25,[side*1.4,0,2],trim,[Math.PI/2,0,0]);cylinder(p.group,.48,.35,.5,[side*1.4,0,3.2],dark,[Math.PI/2,0,0]);cylinder(p.group,.31,.38,.06,[side*1.4,0,3.48],glow,[Math.PI/2,0,0]);for(let i=0;i<4;i++)cylinder(p.group,.44,.44,.06,[side*1.4,0,1.35+i*.42],dark,[Math.PI/2,0,0]);}
  p=part('dorsal-array','Navigation & sensor spine','A concept communications and navigation assembly. Sensor fusion and autonomous navigation are not connected.',[0,2.5,1.2],'Fit above the rear service bay');box(p.group,[.16,.9,1.4],[0,.8,1.5],dark);mesh(p.group,new T.SphereGeometry(.21,16,12),trim,[0,1.4,1.6]);
  for(let i=0;i<8;i++){const side=i%2?1:-1,z=-.8+Math.floor(i/2)*.85;p=part('fastener-'+(i+1),'Service fastener '+String(i+1).padStart(2,'0'),'An individually selectable illustrative service fastener. Thread, size, material, preload and torque are intentionally unspecified; validated CAD and a bill of materials are required for fabrication.',[side*.8,1.6+i*.06,0],'Concept mounting point only — no manufacturing specification');cylinder(p.group,.073,.073,.095,[side*.83,.96,z],trim);box(p.group,[.085,.008,.016],[side*.83,1.012,z],dark)}
 }
 function buildDrone(){const white=mat(0xc7d5dc),dark=mat(0x172634),cyan=mat(0x61d7b9);let p=part('core','Flight computer enclosure','Concept avionics enclosure. Autonomous flight and sensor analysis are not connected.',[0,1,0]);box(p.group,[1.55,.55,1.9],[0,.15,0],white);box(p.group,[1.1,.15,1.2],[0,.51,0],dark);p=part('battery','Removable battery module','Illustrative power module with a visible connector. Energy storage and flight endurance are not validated.',[0,-1.5,0]);box(p.group,[1.05,.37,1.5],[0,-.35,0],dark);for(let i=0;i<4;i++)box(p.group,[.1,.035,.5],[-.34+i*.22,-.15,0],cyan);
  for(let i=0;i<4;i++){const x=i%2?1:-1,z=i<2?1:-1;p=part('arm-'+i,'Rotor arm '+(i+1),'A replaceable arm, motor and propeller assembly. Rotation is visual only; no lift or stability calculation is performed.',[x*1.3,.3,z*1.3]);const beam=box(p.group,[2.1,.16,.25],[x*1.2,.05,z*1.2],dark);beam.rotation.y=-x*z*Math.PI/4;cylinder(p.group,.23,.26,.3,[x*2,.2,z*2],cyan);const rotor=new T.Group();rotor.position.set(x*2,.42,z*2);p.group.add(rotor);box(rotor,[1.9,.035,.14],[0,0,0],dark);box(rotor,[.14,.035,1.9],[0,0,0],dark);rotors.push(rotor);cylinder(p.group,.1,.1,.5,[x*1,-.36,z],dark)}
  p=part('sensor','Gimballed sensor pod','An illustrative camera and range sensor. The model does not capture images, scan the room, or pilot hardware.',[0,-1.5,-1]);mesh(p.group,new T.SphereGeometry(.37,24,16),dark,[0,-.68,-.5]);cylinder(p.group,.19,.19,.17,[0,-.67,-.84],cyan,[Math.PI/2,0,0]);
 }
 function buildRocket(){const white=mat(0xcbd8df),dark=mat(0x183043),mint=mat(0x70dfbf);root.position.y=-.4;
 let p=part('rocket-body','Main airframe','An educational rocket-shaped concept. No propulsion design, pressure rating, or flight qualification is supplied.',[0,.4,0]);cylinder(p.group,.7,.7,4.8,[0,.5,0],white);for(let y=-1;y<3;y+=.8)cylinder(p.group,.71,.71,.07,[0,y,0],dark);
 p=part('rocket-nose','Nose fairing','A removable visual fairing over the conceptual payload section. Geometry is not an aerodynamic simulation.',[0,2.5,0],'Illustrative fairing interface',true);mesh(p.group,new T.ConeGeometry(.7,1.6,40),white,[0,3.7,0]);
 p=part('rocket-payload','Payload module','A visualization of a payload enclosure. Payload mass, vibration and thermal limits remain unspecified.',[1.8,1,0]);cylinder(p.group,.52,.52,.9,[0,2.4,0],mint);
 p=part('rocket-base','Aft service ring','A concept attachment ring. Motor selection and flight testing belong in a validated model-rocket workflow.',[0,-1.4,0]);cylinder(p.group,.78,.78,.4,[0,-2,0],dark);
 for(let i=0;i<4;i++){const a=i*Math.PI/2;p=part('rocket-fin-'+i,'Stabilizer '+(i+1),'An individually selectable conceptual stabilizer. Stability and structural loads have not been evaluated.',[Math.cos(a)*2,0,Math.sin(a)*2]);const f=box(p.group,[.12,1.3,1.2],[Math.cos(a)*.88,-1.55,Math.sin(a)*.88],mint);f.rotation.y=a+Math.PI/2;f.rotation.z=.15;}
 }
 function buildResearch(){const white=mat(0xc5d4de),dark=mat(0x172c40),mint=mat(0x6cd5be),glass=new T.MeshPhysicalMaterial({color:0x89d4df,transparent:true,opacity:.5,roughness:.15});
 let p=part('research-base','Instrument base','Concept instrument stand for a research workspace. Not a diagnostic device or a validated laboratory instrument.',[0,-1.4,0]);box(p.group,[4,.35,3],[0,-1.7,0],dark);
 p=part('research-frame','Optical support frame','A visual support column and bridge. Alignment, vibration and dimensional tolerances require an engineering design.',[-2,0,0]);box(p.group,[.45,3.5,.65],[-1.4,.15,.5],white);box(p.group,[2.8,.4,.65],[-.2,1.7,.5],white);
 p=part('research-optics','Imaging head','Illustrative optics enclosure. It does not capture images, diagnose conditions, or predict efficacy.',[0,2,0]);cylinder(p.group,.45,.3,1.1,[.55,1.05,.5],dark);cylinder(p.group,.3,.3,.12,[.55,.46,.5],mint);
 p=part('research-stage','Sample stage','A removable concept stage. No biological samples, procedures, or experiments are represented.',[2,0,0]);box(p.group,[2.2,.2,1.7],[.2,-.65,.35],white);mesh(p.group,new T.TorusGeometry(.5,.06,12,36),mint,[.55,-.53,.5],[Math.PI/2,0,0]);
 p=part('research-carrier','Empty sample carrier','A generic empty container illustrates component handling. This is not a drug, molecular structure, or treatment prototype.',[0,1.2,1.8]);cylinder(p.group,.4,.4,.2,[.55,-.42,.5],glass);
 p=part('research-control','Control enclosure','A concept user-interface panel. Sensor collection and instrument control require an implemented, validated connection.',[2,0,-1.5]);const screen=box(p.group,[1.2,.8,.12],[1.45,-.95,-.9],mint);screen.rotation.x=-.3;
 }
 function buildRobot(){const silver=mat(0xbecbd3),dark=mat(0x152735),cyan=mat(0x5bd5b4),jointMat=mat(0x4a687c,.85,.28);root.position.y=-1.4;grid.position.y=-1.42;
  let p=part('base','Rotating base','A yaw joint aims the arm toward a target in the horizontal plane. The base angle is computed from target X and Z.',[0,-1,0],'Scene reference; no physical mounting design');cylinder(p.group,1,1.12,.26,[0,.13,0],dark);cylinder(p.group,.58,.7,.36,[0,.43,0],silver);for(let i=0;i<8;i++){const a=i*Math.PI/4;cylinder(p.group,.07,.07,.035,[Math.cos(a)*.88,.28,Math.sin(a)*.88],jointMat)}
  const yaw=new T.Group();yaw.position.y=.65;root.add(yaw);const shoulder=new T.Group();yaw.add(shoulder);
  p=part('upper-arm','Shoulder & upper link','First articulated link in the two-link inverse-kinematics chain. Link length is 2 illustrative scene units, not a manufacturing dimension.',[-1.5,.8,0],'Rotate about the shoulder axis');root.remove(p.group);shoulder.add(p.group);cylinder(p.group,.34,.34,.68,[0,0,0],jointMat,[Math.PI/2,0,0]);box(p.group,[.43,1.7,.46],[0,1,0],silver);box(p.group,[.045,1.15,.48],[.24,1,0],cyan);cylinder(p.group,.29,.29,.63,[0,2,0],jointMat,[Math.PI/2,0,0]);
  const elbow=new T.Group();elbow.position.y=2;shoulder.add(elbow);p=part('forearm','Elbow & forearm','Second link follows the solved elbow angle. Reachability is checked geometrically; collisions, forces and joint limits are not simulated.',[1.5,.8,0],'Rotate relative to the upper link');root.remove(p.group);elbow.add(p.group);box(p.group,[.34,1.3,.38],[0,.78,0],silver);box(p.group,[.36,.75,.045],[0,.8,-.21],cyan);cylinder(p.group,.24,.24,.4,[0,1.5,0],jointMat);
  p=part('gripper','Parallel gripper','A two-finger concept gripper illustrates grasping a demonstration block. It does not model contact, grip force or hardware control.',[0,1.5,.8],'Attach the tool flange to the wrist');root.remove(p.group);elbow.add(p.group);box(p.group,[.65,.18,.35],[0,1.74,0],dark);const fingers=[];for(const x of [-.25,.25])fingers.push(box(p.group,[.1,.4,.2],[x,1.96,0],cyan));
  p=part('workpiece','Demonstration workpiece','A concept block for a preprogrammed pick-and-place trajectory. The green target ring represents the requested end-effector position.',[1,0,1],'Scene object; attachment occurs only in the animation');const cube=box(p.group,[.38,.38,.38],[2,.22,1],cyan);p=part('destination','Destination fixture','A receiving tray for the demonstration block. Collision-free motion is not guaranteed by this simplified simulation.',[-1,0,-1]);box(p.group,[1.05,.1,1.05],[-1.9,.05,-1.2],dark);for(const x of [-.5,.5])box(p.group,[.06,.2,1.05],[-1.9+x,.15,-1.2],silver);
  const target=mesh(root,new T.TorusGeometry(.2,.025,8,40),new T.MeshBasicMaterial({color:0x8af5cf}),[2,1.4,1],[Math.PI/2,0,0]);robot={yaw,shoulder,elbow,fingers,cube,target,homeParent:cube.parent};pose([2,1.4,1]);
 }
 function pose(v){if(!robot)return false;const angles=solveArmTarget(...v);robot.target.position.set(...v);if(!angles)return false;robot.yaw.rotation.y=angles.yaw;robot.shoulder.rotation.z=-angles.shoulder;robot.elbow.rotation.z=-angles.elbow;return true}
 function setModel(name){if(!['spacecraft','robot','drone','rocket','research'].includes(name))throw new Error('Unknown model');if(root){scene.remove(root);root.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose()}})}root=new T.Group();scene.add(root);parts=[];rotors=[];robot=null;robotRun=null;model=name;explode=0;assembly=null;interior=false;isolated=false;wire=false;grid.position.y=-2.15;if(name==='spacecraft')buildSpacecraft();else if(name==='drone')buildDrone();else if(name==='rocket')buildRocket();else if(name==='research')buildResearch();else buildRobot();detailInvention(parts,model);annotate();selected=parts[0].id;reset();notify()}
 function notify(){const p=parts.find(p=>p.id===selected);onChange({model,parts:parts.map(({id,name,description,connection,step})=>({id,name,description,connection,step})),selected,p: p&&{id:p.id,name:p.name,description:p.description,connection:p.connection,step:p.step},explode,interior,isolated,rotating:controls.autoRotate,wire,assembling:!!assembly})}
 function reset(){controls.target.set(0,model==='robot'?.65:0,0);camera.position.set(model==='robot'?7:9,model==='robot'?5:6,model==='robot'?8:-10);controls.update()}
 function select(id){if(!parts.some(p=>p.id===id))return;selected=id;notify()}
 let down;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY]});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(root.children,true).find(h=>h.object.userData.part&&h.object.visible);if(hit)select(hit.object.userData.part)});
 function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(!visible||document.hidden)return;if(assembly){const t=Math.max(0,Math.min(1,(now-assembly)/6000));explode=1-t;onChange({progress:Math.round((1-explode)*100)});if(t===1){assembly=null;notify()}}parts.forEach((p,i)=>{const amount=assembly?Math.max(0,Math.min(1,explode*1.5-i/parts.length*.5)):explode;p.group.position.copy(p.origin).addScaledVector(p.offset,amount);p.group.visible=!(interior&&p.shell)&&(!isolated||p.id===selected);p.group.traverse(o=>{if(o.isMesh){o.material.wireframe=wire;if(o.material.emissive){o.material.emissive.copy(o.userData.baseEmissive||new T.Color());if(p.id===selected)o.material.emissive.lerp(new T.Color(0x2b8b74),.3)}}})});if(!matchMedia('(prefers-reduced-motion: reduce)').matches)rotors.forEach(r=>r.rotation.y+=dt*5);
  if(robotRun&&robot){const t=Math.max(0,(now-robotRun.start)/1000),sequence=[[2,1.4,1],[2,.22,1],[2,2.2,1],[-1.9,2.2,-1.2],[-1.9,.35,-1.2],[-1.9,1.8,-1.2]],segment=Math.min(4,Math.floor(t/1.4)),q=Math.min(1,(t/1.4)-segment),ease=q*q*(3-2*q),a=sequence[segment],b=sequence[segment+1];pose(a.map((v,i)=>v+(b[i]-v)*ease));if(t>1.35&&t<5.55){if(robot.cube.parent!==robot.elbow){robot.elbow.attach(robot.cube);robot.cube.position.set(0,2,0)}robot.fingers.forEach((f,i)=>f.position.x=(i?1:-1)*.2)}else if(t>=5.55){if(robot.cube.parent===robot.elbow){robot.homeParent.attach(robot.cube);robot.cube.position.set(-1.9,.35,-1.2)}robot.fingers.forEach((f,i)=>f.position.x=(i?1:-1)*.29)}if(t>=7){robotRun=null;onChange({robotStatus:'Pick-and-place demonstration complete. No hardware was controlled.'})}}
 controls.update();renderer.render(scene,camera)}
 const ro=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;if(w&&h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}});ro.observe(container);const observer=new IntersectionObserver(([e])=>{visible=e.isIntersecting});observer.observe(container);requestAnimationFrame(frame);
 const api={setModel,select,reset,zoom(f){camera.position.sub(controls.target).multiplyScalar(f).add(controls.target)},toggleRotate(){controls.autoRotate=!controls.autoRotate;notify()},toggleInterior(){interior=!interior;isolated=false;if(interior){camera.position.set(5,9,-5);controls.target.set(0,0,0)}notify()},toggleWire(){wire=!wire;notify()},toggleIsolate(){isolated=!isolated;notify()},focus(){const p=parts.find(p=>p.id===selected);if(p){const center=new T.Box3().setFromObject(p.group).getCenter(new T.Vector3());controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(3,2,3));controls.autoRotate=false;notify()}},setExplode(v){assembly=null;explode=Math.max(0,Math.min(1,Number(v)));notify()},assemble(){isolated=false;interior=false;assembly=performance.now();notify()},target(v){robotRun=null;return pose(v)},runRobot(){if(!robot)return;explode=0;isolated=false;robot.homeParent.attach(robot.cube);robot.cube.position.set(2,.22,1);robotRun={start:performance.now()};controls.autoRotate=false;notify()},stopRobot(){robotRun=null;if(robot){robot.homeParent.attach(robot.cube);robot.cube.position.set(2,.22,1);pose([2,1.4,1])}notify()},exportOBJ(){root.updateMatrixWorld(true);let out='# DreamCo concept mesh. Arbitrary scene units; not validated for manufacture.\n',offset=1;root.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position,idx=o.geometry.index;out+='o '+(o.userData.part||'concept')+'\n';for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld);out+=`v ${v.x} ${v.y} ${v.z}\n`}for(let i=0;i<(idx?idx.count:p.count);i+=3){out+=`f ${offset+(idx?idx.getX(i):i)} ${offset+(idx?idx.getX(i+1):i+1)} ${offset+(idx?idx.getX(i+2):i+2)}\n`}offset+=p.count});return out},snapshot(){return {schema:'dreamco.concept_configuration.v1',model,selected,explode,interior,parts:parts.map(({id,name,step,connection})=>({id,name,assemblyStep:step,connection})),boundary:'Concept illustration only. No engineering validation, fastener specifications, physical simulation or hardware control.'}}};setModel('spacecraft');return api;
}
