(function(){
  const byId=(id)=>document.getElementById(id);let payload;const fmt=new Intl.NumberFormat('en-US');
  function metric(id,value){byId(id).textContent=fmt.format(Number(value||0))}
  function renderAudit(){const target=byId('audit-grid');target.replaceChildren();Object.entries(payload.repository_audit||{}).filter(([,v])=>typeof v==='number').forEach(([key,value])=>{const card=document.createElement('article');const label=document.createElement('span');label.textContent=key.replaceAll('_',' ');const count=document.createElement('strong');count.textContent=fmt.format(value);card.append(label,count);target.append(card)})}
  function renderPlan(){const plan=payload.unified_plan;metric('plan-source-count',plan.source_count);byId('goal-signal-count').textContent=`${fmt.format(plan.goal_signal_count)} goal signals indexed`;const lanes=byId('lane-grid');plan.lanes.forEach(lane=>{const card=document.createElement('article');card.className='lane-card';const title=document.createElement('h3');title.textContent=lane.id;const count=document.createElement('strong');count.textContent=`${fmt.format(lane.source_count)} sources · ${lane.parallel_limit} parallel slots`;const dependencies=document.createElement('p');dependencies.className='muted';dependencies.textContent=lane.depends_on.length?`Depends on: ${lane.depends_on.join(', ')}`:'Foundation lane';card.append(title,count,dependencies);lanes.append(card)});const sources=byId('plan-source-list');plan.sources.forEach(source=>{const row=document.createElement('div');row.className='source-row';const path=document.createElement('code');path.textContent=source.path;const title=document.createElement('span');title.textContent=source.title;const meta=document.createElement('span');meta.className='pill';meta.textContent=`${source.lane} · ${source.goal_signal_count} signals`;row.append(path,title,meta);sources.append(row)})}
  function renderItems(){const query=byId('directive-search').value.trim().toLowerCase(),status=byId('directive-status').value,priority=byId('directive-priority').value;const items=payload.items.filter(item=>(!query||`${item.section} ${item.title} ${item.acceptance_excerpt}`.toLowerCase().includes(query))&&(!status||item.status===status)&&(!priority||item.priority===priority));byId('result-count').textContent=`${fmt.format(items.length)} of ${fmt.format(payload.items.length)} sections shown`;const target=byId('directive-list');target.replaceChildren();items.forEach(item=>{const card=document.createElement('article');card.className='directive-item';const top=document.createElement('div');top.className='directive-top';const heading=document.createElement('h3');heading.textContent=`${item.section}. ${item.title}`;const pills=document.createElement('div');pills.className='pills';[item.priority,item.status].forEach(value=>{const pill=document.createElement('span');pill.className=`pill pill-${value}`;pill.textContent=value;pills.append(pill)});top.append(heading,pills);const excerpt=document.createElement('p');excerpt.className='muted';excerpt.textContent=item.acceptance_excerpt||'No acceptance excerpt recorded.';const evidence=document.createElement('div');evidence.className='evidence';evidence.textContent=item.evidence_refs.length?`Evidence: ${item.evidence_refs.join(' · ')}`:`Next gate: ${item.next_status}; implementation evidence required.`;card.append(top,excerpt,evidence);target.append(card)});if(!items.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='No directive sections match these filters.';target.append(empty)}}
  async function init(){const response=await fetch('data/master-directive-status.json',{cache:'no-store'});if(!response.ok)throw new Error(`Master directive data unavailable: ${response.status}`);payload=await response.json();const counts=payload.summary.status_counts;metric('section-count',payload.summary.directive_sections);metric('catalogued-count',counts.catalogued);metric('implemented-count',counts.implemented);metric('production-count',counts.production_verified);byId('truth-boundary').textContent=payload.summary.truth;byId('source-hash').textContent=`directive ${payload.source_sha256.slice(0,12)}`;payload.evidence_taxonomy.forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value.replaceAll('_',' ');byId('directive-status').append(option)});renderAudit();renderPlan();renderItems();['directive-search','directive-status','directive-priority'].forEach(id=>byId(id).addEventListener('input',renderItems))}
  init().catch(error=>{byId('truth-boundary').textContent=error.message;document.documentElement.dataset.masterBuild='offline'})
})();
