const $=id=>document.getElementById(id), HOME='DreamCo-Technologies/Dreamcobots';
let project=HOME, branch='main', files=[], library=null, limit=40, generation=0;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
export function parseProject(value){let s=value.trim().replace(/\/$/,'');if(s.startsWith('https://github.com/'))s=s.slice(19);if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(s)||s.split('/').some(p=>p==='.'||p==='..'))throw Error('Use owner/project or a https://github.com/owner/project link.');return s.replace(/\.git$/,'')}
function github(path=''){return `https://github.com/${project}${path}`}
function buddy(prompt){return `buddy.html?prompt=${encodeURIComponent(`For GitHub project ${project}: ${prompt} Use everyday language, explain the next step, and distinguish plans from verified working features.`)}`}
function link(text,url){const a=el('a',text);a.href=url;return a}
function fileURL(path){return github(`/blob/${encodeURIComponent(branch)}/${path.split('/').map(encodeURIComponent).join('/')}`)}
function kind(path){return /plan|roadmap|backlog|strategy|directive/i.test(path)?'Plans':/\.(md|txt|rst)$/i.test(path)?'Documents':/^(App_bots|bots)\//.test(path)?'Bots':/^(tests|\.github\/workflows)\//.test(path)?'Build checks':path.startsWith('website/')?'Website':'Code & data'}
function renderFiles(){const tokens=$('file-search').value.toLowerCase().trim().split(/\s+/).filter(Boolean),category=$('file-kind').value;const matches=files.filter(f=>(!category||f.kind===category)&&tokens.every(t=>`${f.path} ${f.title} ${f.summary||''} ${f.words||''}`.toLowerCase().includes(t)));$('file-count').textContent=`${matches.length.toLocaleString()} matches · ${files.length.toLocaleString()} files in this library`;$('file-list').replaceChildren();for(const f of matches.slice(0,limit)){const row=el('article',undefined,'file-row'),copy=el('div'),actions=el('div',undefined,'file-actions');copy.append(el('span',f.kind,'tag'),el('h3',f.title),el('code',f.path));if(f.summary)copy.append(el('p',f.summary));actions.append(link('Read ↗',fileURL(f.path)),link('Explain',buddy(`Read and explain ${f.path}. Source: ${fileURL(f.path)}. If the source cannot be accessed, say so and ask for the contents; do not guess.`)));row.append(copy,actions);$('file-list').append(row)}if(!matches.length)$('file-list').append(el('p','No matches. Try a shorter word or choose Everything.','empty'));$('more-files').hidden=matches.length<=limit}
async function api(path,signal){const r=await fetch(`https://api.github.com/repos/${project}${path}`,{signal,headers:{Accept:'application/vnd.github+json'}});if(!r.ok){if(r.status===403||r.status===429)throw Error('GitHub is limiting requests. Try again later, or use the direct GitHub links.');if(r.status===404)throw Error('This project was not found or needs sign-in. Check the name or open it on GitHub.');throw Error(`GitHub could not load this information (${r.status}).`)}return r.json()}
function activity(id,rows,type){const list=$(id);list.replaceChildren();for(const row of rows){const article=el('article',undefined,'activity-row');const url=row.html_url;const safe=typeof url==='string'&&url.startsWith(github('/') );const status=type==='checks'?({success:'Passed',failure:'Needs attention',cancelled:'Stopped',skipped:'Not needed',timed_out:'Took too long',action_required:'Your help is needed'}[row.conclusion]||({queued:'Waiting',in_progress:'Working',waiting:'Waiting for approval',completed:'Finished'}[row.status]||'Status unavailable')):row.draft?'Draft — still being prepared':type==='changes'?'Ready for someone to review':'Open task';article.append(el('span',`${status}${row.number?` · #${row.number}`:''}`));article.append(safe?link(row.title||row.name||'Build check',url):el('h3',row.title||row.name||'Build check'));if(row.updated_at)article.append(el('span',`Updated ${new Date(row.updated_at).toLocaleString()}`));list.append(article)}if(!rows.length)list.append(el('p','Nothing to show in this recent snapshot. Use GitHub to see the full history.','empty'));else list.prepend(el('p',`Showing ${rows.length} recent entries. Open GitHub for the complete history.`, 'note'))}
function setupLinks(){$('project-name').textContent=project.replace('/',' / ');$('github-project').href=github();$('all-files').href=github();$('new-task').href=github('/issues/new');$('all-checks').href=github('/actions');$('ask-buddy').href=buddy('Help me understand this project and pick the next useful step.');document.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>{location.href=buddy(b.dataset.guide)})}
async function loadProject(next){const ticket=++generation;project=next;branch=project===HOME?(library?.ref||'main'):'main';files=project===HOME&&library?library.files:[];limit=40;setupLinks();renderFiles();$('library-note').textContent=project===HOME&&library?library.scope:'Other public projects have file-path search. Open a file to read its complete contents.';$('connection-status').textContent='Reading public project updates…';for(const id of ['task-list','change-list','check-list'])$(id).replaceChildren(el('p','Loading…'));
const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const meta=await api('',controller.signal);if(ticket!==generation)return;branch=project===HOME?(library?.ref||'main'):meta.default_branch;renderFiles();const results=await Promise.allSettled([api('/issues?state=open&per_page=30',controller.signal),api('/pulls?state=open&per_page=30',controller.signal),api('/actions/runs?per_page=30',controller.signal),project===HOME&&library?Promise.resolve(null):api(`/git/trees/${encodeURIComponent(meta.default_branch)}?recursive=1`,controller.signal)]);if(ticket!==generation)return;const targets=['task-list','change-list','check-list'];results.slice(0,3).forEach((r,i)=>{if(r.status==='fulfilled')activity(targets[i],i===0?r.value.filter(x=>!x.pull_request):i===2?r.value.workflow_runs||[]:r.value,['tasks','changes','checks'][i]);else $(targets[i]).replaceChildren(el('p',r.reason.message||'Could not load this area. Use the GitHub link.','empty'))});const tree=results[3];if(tree.status==='fulfilled'&&tree.value){files=tree.value.tree.filter(f=>f.type==='blob').map(f=>({path:f.path,title:f.path.split('/').pop(),kind:kind(f.path)}));renderFiles();$('library-note').textContent=tree.value.truncated?'GitHub returned a partial file list for this large project. Browse original files for everything.':'All files returned by GitHub for the main working version. Search matches file paths; use Read for the full contents.'}else if(tree.status==='rejected')$('library-note').textContent=tree.reason.message;$('connection-status').textContent=`Checked ${new Date().toLocaleTimeString()} · ${results.some(r=>r.status==='rejected')?'Some live sections could not load.':'Public project information loaded.'}`;}catch(e){if(ticket!==generation)return;$('connection-status').textContent=e.name==='AbortError'?'GitHub took too long. The saved DreamCo library and direct links are still available.':e.message;for(const id of ['task-list','change-list','check-list'])$(id).replaceChildren(el('p','Live information is unavailable. Open this project on GitHub to continue.','empty'))}finally{clearTimeout(timer)}}
$('repo-form').addEventListener('submit',e=>{e.preventDefault();try{const next=parseProject($('repo-input').value);const u=new URL(location.href);u.searchParams.set('repo',next);history.replaceState(null,'',u);loadProject(next)}catch(err){$('connection-status').textContent=err.message}});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==b.dataset.tab)});
$('file-search').oninput=$('file-kind').onchange=()=>{limit=40;renderFiles()};$('more-files').onclick=()=>{limit+=40;renderFiles()};
try{const response=await fetch('data/repository-library.json');if(!response.ok)throw Error();library=await response.json()}catch{ $('library-note').textContent='The saved library could not load; trying GitHub.' }
let initial=HOME;try{initial=parseProject(new URLSearchParams(location.search).get('repo')||HOME)}catch{}$('repo-input').value=initial;loadProject(initial);
