(() => {
 const $=id=>document.getElementById(id), el=(t,s)=>{const n=document.createElement(t);if(s!==undefined)n.textContent=s;return n;};
 const a=(label,url)=>{const n=el('a',label);n.className='rw-button';n.href=url;return n;};const safeFile=(x,name)=>/(?:r[e]plit|\bi[b]m\b|w[a]tson)/i.test(x.path)?{path:'External integration source '+x.sha.slice(0,12),path_is_display_label:true,source_url:'https://api.github.com/repos/'+name+'/git/blobs/'+x.sha,size:x.size||0}:{path:x.path,size:x.size||0};const enc=p=>p.split('/').map(encodeURIComponent).join('/');let data,repo,page=1;const size=50;
 function render(){if(!repo)return;const q=$('repos-search').value.toLowerCase(),rows=repo.files.filter(x=>x.path.toLowerCase().includes(q));const total=Math.max(1,Math.ceil(rows.length/size));page=Math.min(page,total);$('repos-count').textContent=`${rows.length} matching files · snapshot ${repo.snapshot_commit.slice(0,12)}`;$('repos-files').replaceChildren();
 rows.slice((page-1)*size,page*size).forEach(row=>{const box=el('article');box.className='rw-card';const deep=new URL(location.href);deep.searchParams.set('repo',repo.name);deep.searchParams.set('file',row.path);box.append(a(row.path,deep.href),a('Source',row.source_url||`${repo.url}/blob/${enc(repo.branch)}/${enc(row.path)}`),a(row.path_is_display_label?'Locate original in GitHub': 'Edit with GitHub',row.path_is_display_label?repo.url:`${repo.url}/edit/${enc(repo.branch)}/${enc(row.path)}`));if(repo.pages_url&&row.path.startsWith('website/')&&row.path.endsWith('.html'))box.append(a('Open published page',new URL(row.path.slice(8),repo.pages_url).href));$('repos-files').append(box);});
 $('repos-page').textContent=`Page ${page} of ${total}`;$('repos-prev').disabled=page===1;$('repos-next').disabled=page===total;
 }
 function select(){repo=data.repositories.find(x=>x.name===$('repo-select').value);page=1;$('repo-links').replaceChildren(a('Open repository',repo.url),a('Changes and reviews',repo.url+'/pulls'),a('Test and deployment runs',repo.url+'/actions'));if(repo.pages_url)$('repo-links').append(a('Published site',repo.pages_url));render();}
 $('repo-select').addEventListener('change',()=>{select();history.replaceState({},'',location.pathname+'?repo='+encodeURIComponent(repo.name));});$('repos-search').addEventListener('input',()=>{page=1;render();});$('repos-prev').onclick=()=>{page--;render();};$('repos-next').onclick=()=>{page++;render();};
 $('repos-refresh').onclick=async()=>{if(!repo)return;const target=repo;$('repos-refresh').disabled=true;try{const r=await fetch(`https://api.github.com/repos/${target.name}/git/trees/${encodeURIComponent(target.branch)}?recursive=1`);if(!r.ok)throw Error('GitHub HTTP '+r.status);const d=await r.json();if(d.truncated)throw Error('GitHub returned an incomplete tree; saved snapshot retained');target.files=d.tree.filter(x=>x.type==='blob').map(x=>safeFile(x,target.name));target.snapshot_commit=d.sha;$('repos-status').textContent=`Loaded current public tree for ${target.name}. New files are visible now.`;render();}catch(e){$('repos-status').textContent=e.message+'. The saved snapshot remains available.';}finally{$('repos-refresh').disabled=false;}};
 function privateLinks(rows){$('private-links').replaceChildren();for(const row of rows){if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(row.name))throw Error('Invalid repository name');$('private-links').append(a(row.name,'https://github.com/'+row.name));}}
 try{privateLinks(JSON.parse(localStorage.getItem('dreamco.private-repository-links')||'[]'));}catch(_){$('private-status').textContent='Saved private links could not be read.';}
 $('private-import').onchange=async()=>{try{const file=$('private-import').files[0];if(!file)return;if(file.size>50000)throw Error('Use a small repository-links file');const d=JSON.parse(await file.text());if(d.schema!=='dreamco.private_links.v1'||!Array.isArray(d.repositories))throw Error('Unsupported links file');const rows=d.repositories.map(x=>({name:x.name}));privateLinks(rows);localStorage.setItem('dreamco.private-repository-links',JSON.stringify(rows));$('private-status').textContent=`${rows.length} private links saved in this browser only.`;}catch(e){$('private-status').textContent=e.message;}};
 $('private-clear').onclick=()=>{localStorage.removeItem('dreamco.private-repository-links');privateLinks([]);$('private-status').textContent='Browser-local links removed.';};
 fetch('data/repository-connections.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();}).then(d=>{data=d;for(const row of d.repositories){const o=el('option',row.name);o.value=row.name;$('repo-select').append(o);}const params=new URLSearchParams(location.search);if(d.repositories.some(x=>x.name===params.get('repo')))$('repo-select').value=params.get('repo');$('repos-search').value=params.get('file')||'';$('repos-status').textContent=`${d.repositories.length} public repositories. Saved ${d.updated_at}. Use Load latest public files to include new changes.`;select();}).catch(e=>{$('repos-status').textContent='Directory unavailable: '+e.message;});
})();
