"""
provider_catalog.py — 200 AI Providers in normalized AIProviderObject format.

Every entry follows the schema defined in provider_schema.py.  IDs match the
company/platform slugs used in model_registry.AI_PROVIDER_REGISTRY_200 so the
two registries can be joined without ambiguity.
"""

from __future__ import annotations

from framework import GlobalAISourcesFlow  # noqa: F401

from bots.ai_provider_registry.provider_schema import (
    AIProviderObject,
    PRICING_FREE, PRICING_FREEMIUM, PRICING_PAID, PRICING_ENTERPRISE, PRICING_OPEN_SOURCE,
    RISK_LOW, RISK_MEDIUM,
)

# Layer constants (inlined to avoid circular imports with taxonomy)
_IL = "intelligence"    # Intelligence
_EL = "execution"       # Execution
_INF = "infrastructure" # Infrastructure
_IND = "industry"       # Industry
_CR = "creative"        # Creative
_PH = "physical"        # Physical


def _p(
    id_: str,
    name: str,
    pricing: str,
    category: str,
    layer: str,
    core_skill: str,
    best_at: str,
    agent_role: str,
    bundle_fit: list[str],
    tier: str,
    api_access: bool = True,
    embedding_ready: bool = False,
    risk_level: str = RISK_LOW,
    competition_cluster: str = "general",
    open_source: bool = False,
    notes: str = "",
) -> AIProviderObject:
    return AIProviderObject(
        id=id_,
        name=name,
        pricing=pricing,
        categories=[category],
        core_skill=core_skill,
        best_at=best_at,
        agent_role=agent_role,
        bundle_fit=bundle_fit,
        tier=tier,
        api_access=api_access,
        embedding_ready=embedding_ready,
        risk_level=risk_level,
        competition_cluster=competition_cluster,
        layer=layer,
        sub_layer=category,
        open_source=open_source,
        notes=notes,
    )


PROVIDER_CATALOG: list[AIProviderObject] = [

    # ── Foundation Models ─────────────────────────────────────────────────
    _p("openai", "OpenAI", PRICING_FREEMIUM, "foundation_models", _IL,
       "Generative language models, reasoning, multimodal AI",
       "Best-in-class GPT capabilities for text, code, reasoning",
       "Foundation LLM Agent", ["core_llm_pack", "developer_pack"],
       "enterprise", embedding_ready=True, competition_cluster="llm_core"),

    _p("anthropic", "Anthropic", PRICING_PAID, "foundation_models", _IL,
       "Safety-first LLMs (Claude family)",
       "Mitigates hallucination risk; regulated domains",
       "Safety & Compliance Agent", ["core_llm_pack", "legal_ai_pack"],
       "enterprise", embedding_ready=True, competition_cluster="llm_core"),

    _p("xai", "xAI (Grok)", PRICING_PAID, "foundation_models", _IL,
       "Large models (Grok), autonomous reasoning",
       "Alternative LLM diversity and redundancy",
       "Companion LLM Agent", ["core_llm_pack"],
       "pro", competition_cluster="llm_core"),

    _p("mistral_ai", "Mistral AI", PRICING_OPEN_SOURCE, "foundation_models", _IL,
       "Open-source LLMs, efficient training",
       "European model options, open-source flexibility",
       "Open LLM Specialist Agent", ["core_llm_pack"],
       "pro", open_source=True, competition_cluster="llm_core"),

    _p("cohere", "Cohere", PRICING_FREEMIUM, "foundation_models", _IL,
       "Text generation, enterprise LLMs",
       "Regulated industry use cases",
       "Enterprise Language Agent", ["core_llm_pack"],
       "enterprise", embedding_ready=True, competition_cluster="llm_core"),

    _p("google_ai_platform", "Google AI", PRICING_FREEMIUM, "foundation_models", _IL,
       "Gemini models, search AI, cloud ML tools",
       "Deep enterprise and search tech reach",
       "Multi-Modal AI Agent", ["core_llm_pack"],
       "enterprise", embedding_ready=True, competition_cluster="llm_core"),

    _p("deepmind", "Google DeepMind", PRICING_ENTERPRISE, "foundation_models", _IL,
       "Reinforcement learning, foundational research",
       "Research insights & breakthrough models",
       "R&D Agent", [],
       "enterprise", competition_cluster="llm_core"),

    _p("deepl_ai", "DeepL AI", PRICING_FREEMIUM, "foundation_models", _IL,
       "Translation AI",
       "Best-in-class language translation",
       "Language & Localization Agent", ["core_llm_pack"],
       "pro", competition_cluster="translation"),

    _p("sakana_ai", "Sakana AI", PRICING_PAID, "regional_emerging", _IL,
       "Research-oriented AI",
       "Novel AI architectures",
       "Research & Discover Agent", [],
       "enterprise", competition_cluster="research"),

    _p("aleph_alpha", "Aleph Alpha", PRICING_ENTERPRISE, "regional_emerging", _IL,
       "European sovereign LLMs",
       "Regulated AI markets in EU",
       "Sovereign AI Agent", [],
       "enterprise", competition_cluster="llm_core"),

    _p("baidu_ai", "Baidu AI (ERNIE)", PRICING_PAID, "regional_emerging", _IL,
       "Chinese LLM & search AI",
       "Regional AI ecosystem in Asia",
       "Regional Expansion Agent", [],
       "enterprise", competition_cluster="llm_core"),

    _p("tencent_ai_lab", "Tencent AI Lab", PRICING_ENTERPRISE, "regional_emerging", _IL,
       "Vision & NLP research",
       "Multimodal research",
       "Global Research Agent", [],
       "enterprise", competition_cluster="research"),

    _p("alibaba_damo", "Alibaba DAMO Academy", PRICING_ENTERPRISE, "regional_emerging", _IL,
       "AI research + commerce AI",
       "AI in e-commerce at scale",
       "AI Commerce Agent", ["sales_marketing_pack"],
       "enterprise", competition_cluster="llm_core"),

    # ── Developer Tools ───────────────────────────────────────────────────
    _p("huggingface_co", "Hugging Face", PRICING_FREEMIUM, "developer_tools", _EL,
       "Open model hub, transformers ecosystem",
       "Access to open models worldwide",
       "Model Router & Selector Agent", ["developer_pack"],
       "pro", open_source=True, competition_cluster="model_hub"),

    _p("anysphere_cursor", "Anysphere (Cursor)", PRICING_PAID, "developer_tools", _EL,
       "Code generation & editing tools",
       "AI-powered code editing",
       "Coding Support Agent", ["developer_pack"],
       "pro", competition_cluster="dev_tools"),

    _p("replit_co", "Replit AI", PRICING_FREEMIUM, "developer_tools", _EL,
       "AI coding assistance",
       "Developer copilots and deployment",
       "Code Execution Agent", ["developer_pack"],
       "pro", competition_cluster="dev_tools"),

    _p("stackblitz", "StackBlitz", PRICING_FREEMIUM, "developer_tools", _EL,
       "Web dev + AI integration",
       "Browser-based development",
       "DevOps & Tools Agent", ["developer_pack"],
       "pro", competition_cluster="dev_tools"),

    _p("octoml", "OctoML", PRICING_PAID, "developer_tools", _EL,
       "Model optimization",
       "Efficient model deployment",
       "Optimization Agent", ["developer_pack"],
       "enterprise", competition_cluster="dev_tools"),

    _p("wandb", "Weights & Biases", PRICING_FREEMIUM, "developer_tools", _EL,
       "ML experiment tracking",
       "Model training observability",
       "ML Experiment Agent", ["developer_pack", "data_analytics_pack"],
       "pro", competition_cluster="mlops"),

    _p("langchain_ai", "LangChain", PRICING_OPEN_SOURCE, "developer_tools", _EL,
       "LLM application framework",
       "Building AI agent chains",
       "Agent Framework Agent", ["developer_pack"],
       "free", open_source=True, competition_cluster="agent_frameworks"),

    _p("vercel_ai", "Vercel AI SDK", PRICING_FREEMIUM, "developer_tools", _EL,
       "AI SDK & deployment",
       "Serverless AI app hosting",
       "Deployment Agent", ["developer_pack"],
       "pro", competition_cluster="dev_tools"),

    _p("supabase_ai", "Supabase AI", PRICING_FREEMIUM, "developer_tools", _EL,
       "AI-enhanced backend-as-a-service",
       "Vector embeddings + real-time DB",
       "Backend Intelligence Agent", ["developer_pack"],
       "pro", embedding_ready=True, competition_cluster="dev_tools"),

    _p("codeium", "Codeium", PRICING_FREEMIUM, "developer_tools", _EL,
       "AI code completion",
       "Fast code suggestions and autocomplete",
       "Code Completion Agent", ["developer_pack"],
       "free", competition_cluster="dev_tools"),

    _p("tabnine", "Tabnine", PRICING_FREEMIUM, "developer_tools", _EL,
       "AI code assistant",
       "Privacy-focused code AI",
       "Secure Code Agent", ["developer_pack"],
       "pro", competition_cluster="dev_tools"),

    _p("github_copilot_co", "GitHub Copilot", PRICING_PAID, "developer_tools", _EL,
       "AI pair programming",
       "In-IDE code generation",
       "Pair Programming Agent", ["developer_pack"],
       "pro", competition_cluster="dev_tools"),

    _p("figma_ai_co", "Figma AI", PRICING_FREEMIUM, "developer_tools", _EL,
       "Collaborative UI design AI",
       "Interface prototyping",
       "UI/UX Design Agent", ["developer_pack"],
       "pro", competition_cluster="design_tools"),

    _p("uipath_test", "UiPath Test Suite", PRICING_PAID, "developer_tools", _EL,
       "AI testing automation",
       "Software QA automation",
       "QA Automation Agent", ["developer_pack"],
       "enterprise", competition_cluster="dev_tools"),

    _p("comet_ml", "Comet ML", PRICING_FREEMIUM, "developer_tools", _EL,
       "ML experiment management",
       "Code + data + model versioning",
       "MLOps Agent", ["developer_pack"],
       "pro", competition_cluster="mlops"),

    # ── Cloud & Infrastructure ────────────────────────────────────────────
    _p("azure_ai_co", "Microsoft Azure AI", PRICING_FREEMIUM, "cloud_infrastructure", _INF,
       "Copilots, Azure ML, cognitive services",
       "Scalable enterprise AI deployments",
       "Enterprise Cloud Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="cloud"),

    _p("aws_ai_co", "AWS AI Services", PRICING_FREEMIUM, "cloud_infrastructure", _INF,
       "Sagemaker, Rekognition, Comprehend",
       "Cloud-native AI services at scale",
       "Scalable Cloud Services Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="cloud"),

    _p("together_ai_co", "Together AI", PRICING_PAID, "cloud_infrastructure", _INF,
       "Model hosting & infrastructure",
       "Cost-effective model hosting",
       "Infrastructure Agent", ["infrastructure_pack"],
       "pro", competition_cluster="model_hosting"),

    _p("lambda_cloud", "Lambda Cloud", PRICING_PAID, "cloud_infrastructure", _INF,
       "Cloud AI compute platform",
       "GPU cloud for training",
       "Scalable Compute Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="cloud"),

    _p("openrouter_ai", "OpenRouter", PRICING_PAID, "cloud_infrastructure", _INF,
       "Multi-model API routing",
       "Unified LLM access gateway",
       "Model Orchestration Agent", ["infrastructure_pack"],
       "pro", competition_cluster="model_routing"),

    _p("runpod_ai", "RunPod", PRICING_PAID, "cloud_infrastructure", _INF,
       "GPU hosting marketplace",
       "On-demand AI compute",
       "Compute Marketplace Agent", ["infrastructure_pack"],
       "pro", competition_cluster="cloud"),

    _p("modal_labs", "Modal", PRICING_PAID, "cloud_infrastructure", _INF,
       "Serverless AI compute",
       "On-demand GPU workloads",
       "Serverless Compute Agent", ["infrastructure_pack"],
       "pro", competition_cluster="cloud"),

    _p("replicate_co", "Replicate", PRICING_PAID, "cloud_infrastructure", _INF,
       "Model hosting API",
       "Run open-source models via API",
       "Model Serving Agent", ["infrastructure_pack"],
       "pro", competition_cluster="model_hosting"),

    _p("neon_db", "Neon", PRICING_FREEMIUM, "cloud_infrastructure", _INF,
       "Serverless Postgres",
       "AI-ready database infrastructure",
       "Database Agent", ["infrastructure_pack"],
       "pro", embedding_ready=True, competition_cluster="databases"),

    _p("cerebras_cloud", "Cerebras AI Cloud", PRICING_ENTERPRISE, "cloud_infrastructure", _INF,
       "Wafer-scale model training",
       "Training extremely large models",
       "Ultra-Scale Training Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="cloud"),

    # ── Hardware & Compute ────────────────────────────────────────────────
    _p("nvidia_co", "NVIDIA", PRICING_PAID, "hardware_compute", _INF,
       "GPUs, CUDA & AI infrastructure",
       "Most widely used AI compute platform",
       "Hardware & Performance Advisor", ["infrastructure_pack"],
       "enterprise", competition_cluster="hardware"),

    _p("sambanova", "SambaNova Systems", PRICING_ENTERPRISE, "hardware_compute", _INF,
       "AI accelerators & integrated systems",
       "High-performance compute for large-scale training",
       "Compute Optimization Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="hardware"),

    _p("groq_ai", "Groq LPU", PRICING_PAID, "hardware_compute", _INF,
       "AI inference acceleration",
       "Low-latency model serving",
       "Performance Optimization Agent", ["infrastructure_pack"],
       "pro", competition_cluster="hardware"),

    _p("cerebras_ai", "Cerebras Systems", PRICING_ENTERPRISE, "hardware_compute", _INF,
       "Wafer-scale AI chips",
       "Massive model training at scale",
       "Mega-Model Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="hardware"),

    _p("graphcore_ai", "Graphcore", PRICING_PAID, "hardware_compute", _INF,
       "AI processors (IPUs)",
       "Intelligence Processing Units",
       "Hardware Strategy Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="hardware"),

    _p("tenstorrent", "Tenstorrent", PRICING_ENTERPRISE, "hardware_compute", _INF,
       "AI chip architecture",
       "Custom AI processors",
       "AI Silicon Strategy Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="hardware"),

    _p("mythic_ai", "Mythic AI", PRICING_ENTERPRISE, "hardware_compute", _INF,
       "Analog AI chips",
       "Edge inference efficiency",
       "Edge Inference Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="hardware"),

    _p("sima_ai", "SiMa.ai", PRICING_ENTERPRISE, "hardware_compute", _INF,
       "Embedded ML chips",
       "Low-power AI at the edge",
       "Embedded Systems Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="hardware"),

    _p("scale_computing", "Scale Computing", PRICING_PAID, "hardware_compute", _INF,
       "Edge AI infrastructure",
       "On-prem AI deployment",
       "Edge Infrastructure Agent", ["infrastructure_pack"],
       "enterprise", competition_cluster="hardware"),

    # ── Enterprise Platforms ──────────────────────────────────────────────
    _p("ibm_watsonx", "IBM Watson / watsonx", PRICING_PAID, "enterprise_platforms", _IND,
       "NLP, automation, analytics",
       "Legacy enterprise integrations",
       "Enterprise Integration Agent", [],
       "enterprise", competition_cluster="enterprise"),

    _p("palantir_co", "Palantir Technologies", PRICING_ENTERPRISE, "enterprise_platforms", _IND,
       "AI-driven data intelligence platforms",
       "Government & enterprise analytics (Foundry, AIP)",
       "Strategic Intelligence Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="enterprise"),

    _p("c3_ai_co", "C3.ai", PRICING_ENTERPRISE, "enterprise_platforms", _IND,
       "Enterprise AI applications",
       "Predictive maintenance & industrial AI",
       "Industrial Intelligence Agent", [],
       "enterprise", competition_cluster="enterprise"),

    _p("notion_ai_co", "Notion AI", PRICING_FREEMIUM, "enterprise_platforms", _IND,
       "AI productivity assistant",
       "Knowledge management",
       "Knowledge Management Agent", [],
       "pro", competition_cluster="productivity"),

    _p("procore_ai", "Procore AI", PRICING_ENTERPRISE, "enterprise_platforms", _IND,
       "Construction intelligence",
       "Construction project automation",
       "Construction Analytics Agent", [],
       "enterprise", competition_cluster="enterprise"),

    _p("sap_ai_co", "SAP Business AI", PRICING_ENTERPRISE, "enterprise_platforms", _IND,
       "Enterprise resource AI",
       "ERP automation & optimization",
       "ERP Optimization Agent", [],
       "enterprise", competition_cluster="enterprise"),

    _p("oracle_ai_co", "Oracle AI", PRICING_ENTERPRISE, "enterprise_platforms", _IND,
       "Enterprise database AI",
       "AI-driven business analytics",
       "Database Intelligence Agent", [],
       "enterprise", competition_cluster="enterprise"),

    _p("servicenow_ai", "ServiceNow AI", PRICING_ENTERPRISE, "enterprise_platforms", _IND,
       "IT workflow automation",
       "Service automation at scale",
       "IT Service Agent", ["automation_pack"],
       "enterprise", competition_cluster="enterprise"),

    _p("dataiku_ai", "Dataiku", PRICING_PAID, "enterprise_platforms", _IND,
       "Collaborative data science platform",
       "Enterprise AI pipelines",
       "Enterprise ML Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="enterprise"),

    _p("veritone", "Veritone AI", PRICING_ENTERPRISE, "enterprise_platforms", _IND,
       "Enterprise AI platform",
       "Media & government AI analytics",
       "Enterprise Analytics Agent", [],
       "enterprise", competition_cluster="enterprise"),

    # ── Analytics & Automation ────────────────────────────────────────────
    _p("databricks_co", "Databricks", PRICING_PAID, "analytics_automation", _EL,
       "Unified analytics + ML model ops (Lakehouse)",
       "Central data workflows, model deployment",
       "DataOps & Enterprise AI Agent", ["data_analytics_pack"],
       "enterprise", embedding_ready=True, competition_cluster="data_platforms"),

    _p("scale_ai", "Scale AI", PRICING_PAID, "data_search", _INF,
       "Data labeling, ground truth datasets",
       "High-quality model fine-tuning data",
       "Data Labeling & Quality Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="data_labeling"),

    _p("datarobot_co", "DataRobot", PRICING_PAID, "analytics_automation", _EL,
       "Automated ML lifecycle",
       "AutoML workflows for enterprises",
       "AutoML Process Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="automl"),

    _p("h2o_co", "H2O.ai", PRICING_OPEN_SOURCE, "analytics_automation", _EL,
       "AutoML",
       "Democratized machine learning",
       "AutoML Optimization Agent", ["data_analytics_pack"],
       "free", open_source=True, competition_cluster="automl"),

    _p("uipath_co", "UiPath AI", PRICING_FREEMIUM, "analytics_automation", _EL,
       "Robotic Process Automation (RPA)",
       "Business workflow automation",
       "Process Automation Agent", ["automation_pack"],
       "enterprise", competition_cluster="rpa"),

    _p("automation_anywhere", "Automation Anywhere", PRICING_ENTERPRISE, "analytics_automation", _EL,
       "Intelligent automation",
       "Enterprise workflow bots",
       "Enterprise RPA Agent", ["automation_pack"],
       "enterprise", competition_cluster="rpa"),

    _p("adept_ai", "Adept AI", PRICING_ENTERPRISE, "analytics_automation", _EL,
       "Action-taking AI for software tools",
       "Automating workflows inside apps",
       "Software Control Agent", ["automation_pack"],
       "enterprise", competition_cluster="agents"),

    _p("uipath_autopilot", "UiPath Autopilot", PRICING_ENTERPRISE, "analytics_automation", _EL,
       "AI-driven RPA copilots",
       "Hybrid human-AI automation",
       "Smart Automation Agent", ["automation_pack"],
       "enterprise", competition_cluster="rpa"),

    _p("samsara_ai", "Samsara AI", PRICING_PAID, "analytics_automation", _EL,
       "IoT AI analytics",
       "Fleet management intelligence",
       "IoT Monitoring Agent", ["automation_pack"],
       "enterprise", competition_cluster="iot"),

    _p("gro_intelligence", "Gro Intelligence", PRICING_ENTERPRISE, "analytics_automation", _EL,
       "Agricultural AI analytics",
       "Climate & crop modeling",
       "Agricultural Forecasting Agent", [],
       "enterprise", competition_cluster="specialized"),

    _p("climate_ai_co", "ClimateAI", PRICING_ENTERPRISE, "analytics_automation", _EL,
       "Climate risk modeling",
       "Supply chain resilience",
       "Climate Risk Agent", [],
       "enterprise", competition_cluster="specialized"),

    _p("tomorrow_io", "Tomorrow.io", PRICING_FREEMIUM, "analytics_automation", _EL,
       "Weather intelligence AI",
       "Predictive weather forecasting",
       "Weather Intelligence Agent", [],
       "pro", competition_cluster="specialized"),

    _p("afresh_ai", "Afresh", PRICING_ENTERPRISE, "analytics_automation", _EL,
       "Grocery AI demand forecasting",
       "Retail food optimization",
       "Retail Forecasting Agent", [],
       "enterprise", competition_cluster="specialized"),

    _p("alteryx_ai", "Alteryx AI", PRICING_PAID, "analytics_automation", _EL,
       "Data analytics automation",
       "No-code analytics workflows",
       "Analytics Automation Agent", ["data_analytics_pack"],
       "pro", competition_cluster="analytics"),

    _p("tibco_ai", "TIBCO AI", PRICING_ENTERPRISE, "analytics_automation", _EL,
       "Real-time analytics AI",
       "Event-driven intelligence",
       "Real-Time Intelligence Agent", [],
       "enterprise", competition_cluster="analytics"),

    _p("fractal_analytics", "Fractal Analytics", PRICING_ENTERPRISE, "analytics_automation", _EL,
       "AI consulting + analytics",
       "Retail & healthcare analytics",
       "Analytics Consulting Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="analytics"),

    _p("weights_ai", "Weights AI", PRICING_PAID, "analytics_automation", _EL,
       "AI model monitoring",
       "Model drift detection",
       "Model Health Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="mlops"),

    _p("snorkel_ai", "Snorkel AI", PRICING_PAID, "data_search", _INF,
       "Self-serve dataset labeling",
       "Programmatic data labeling",
       "Data Quality & Labeling Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="data_labeling"),

    _p("labelbox", "Labelbox", PRICING_FREEMIUM, "data_search", _INF,
       "Data labeling platform",
       "Training data management",
       "Data Preparation Agent", ["data_analytics_pack"],
       "pro", competition_cluster="data_labeling"),

    _p("vast_data", "VAST Data", PRICING_PAID, "data_search", _INF,
       "AI data infrastructure",
       "Massive-scale data storage for AI",
       "Data Engineering Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="data_platforms"),

    # ── Conversational AI ─────────────────────────────────────────────────
    _p("perplexity_co", "Perplexity AI", PRICING_FREEMIUM, "conversational_ai", _IL,
       "AI-augmented search & answer engine",
       "Competitive reference search module",
       "Search & Retrieval Agent", ["core_llm_pack"],
       "pro", competition_cluster="search"),

    _p("character_ai_co", "Character.AI", PRICING_FREEMIUM, "conversational_ai", _IL,
       "Personality-based conversational agents",
       "Role-based AI characters",
       "Personality Simulation Agent", ["creative_pack"],
       "pro", competition_cluster="consumer_ai"),

    _p("inflection_ai", "Inflection AI", PRICING_FREEMIUM, "conversational_ai", _IL,
       "Conversational assistants",
       "Personal AI companions",
       "Personal Assistant Agent", [],
       "pro", competition_cluster="consumer_ai"),

    _p("intercom_ai", "Intercom AI", PRICING_PAID, "conversational_ai", _IL,
       "AI customer support",
       "SaaS chat support automation",
       "Support Automation Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="customer_support"),

    _p("zendesk_ai", "Zendesk AI", PRICING_PAID, "conversational_ai", _IL,
       "AI helpdesk systems",
       "Ticket automation at scale",
       "Service Desk Agent", [],
       "enterprise", competition_cluster="customer_support"),

    _p("moveworks", "Moveworks", PRICING_ENTERPRISE, "conversational_ai", _IL,
       "IT service automation",
       "Employee IT support chatbot",
       "IT Support Agent", ["automation_pack"],
       "enterprise", competition_cluster="customer_support"),

    _p("forethought_ai", "Forethought AI", PRICING_ENTERPRISE, "conversational_ai", _IL,
       "Customer support AI",
       "Ticket triage and resolution",
       "Ticket Triage Agent", [],
       "enterprise", competition_cluster="customer_support"),

    # ── Vision, Speech & Media ────────────────────────────────────────────
    _p("elevenlabs_co", "ElevenLabs", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "Voice generation & expressive AI",
       "Natural voice synthesis and cloning",
       "Voice & Speech Agent", ["creative_pack"],
       "pro", competition_cluster="tts"),

    _p("midjourney_co", "Midjourney", PRICING_PAID, "vision_speech_media", _CR,
       "AI art & visuals",
       "High-quality creative imagery",
       "Vision & Creative Agent", ["creative_pack"],
       "pro", competition_cluster="image_gen"),

    _p("runway_co", "Runway", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "Video editing & generative video",
       "Motion media creation",
       "Video Media Agent", ["creative_pack"],
       "pro", competition_cluster="video_gen"),

    _p("synthesia", "Synthesia", PRICING_PAID, "vision_speech_media", _CR,
       "AI avatars, video synthesis",
       "Humanized video content at scale",
       "Presentation & Training Content Agent", ["creative_pack"],
       "enterprise", competition_cluster="video_gen"),

    _p("suno_co", "Suno", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "Music & sound generation",
       "AI music composition",
       "Audio Creative Agent", ["creative_pack"],
       "pro", competition_cluster="audio_gen"),

    _p("stability_ai", "Stability AI", PRICING_OPEN_SOURCE, "vision_speech_media", _CR,
       "Open-source image models",
       "Diffusion-based generative art",
       "Visual Generation Agent", ["creative_pack"],
       "free", open_source=True, competition_cluster="image_gen"),

    _p("assemblyai", "AssemblyAI", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "Speech-to-text APIs",
       "Audio transcription accuracy",
       "Transcription Agent", ["creative_pack"],
       "pro", competition_cluster="stt"),

    _p("speechmatics", "Speechmatics", PRICING_PAID, "vision_speech_media", _CR,
       "Enterprise transcription",
       "Multilingual speech AI",
       "Enterprise Speech Agent", [],
       "enterprise", competition_cluster="stt"),

    _p("resemble_ai", "Resemble AI", PRICING_PAID, "vision_speech_media", _CR,
       "Voice cloning",
       "Synthetic voice creation",
       "Synthetic Voice Agent", ["creative_pack"],
       "pro", competition_cluster="tts"),

    _p("pika_labs_co", "Pika Labs", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "Generative video",
       "Short-form AI video creation",
       "Video Generation Agent", ["creative_pack"],
       "pro", competition_cluster="video_gen"),

    _p("luma_ai_co", "Luma AI", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "3D generative AI",
       "AI 3D capture and modeling",
       "3D Modeling Agent", ["creative_pack"],
       "pro", competition_cluster="3d_gen"),

    _p("sensetime", "SenseTime", PRICING_ENTERPRISE, "vision_speech_media", _CR,
       "Computer vision",
       "Facial recognition & smart cities",
       "Surveillance & Vision Agent", ["security_pack"],
       "enterprise", competition_cluster="computer_vision"),

    _p("trigo", "Trigo", PRICING_ENTERPRISE, "vision_speech_media", _CR,
       "Computer vision for retail",
       "Checkout-free store technology",
       "Vision Retail Agent", [],
       "enterprise", competition_cluster="computer_vision"),

    _p("standard_ai_retail", "Standard AI", PRICING_ENTERPRISE, "vision_speech_media", _CR,
       "Autonomous checkout vision",
       "Retail automation systems",
       "Store Automation Agent", [],
       "enterprise", competition_cluster="computer_vision"),

    _p("snap_ai_co", "Snap AI", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "AR filters + consumer AI",
       "Visual social AI experiences",
       "Social Vision Agent", ["creative_pack"],
       "pro", competition_cluster="ar"),

    _p("captions_ai", "Captions", PRICING_PAID, "vision_speech_media", _CR,
       "AI-enhanced video editing",
       "Automated video production",
       "Media Production Agent", ["creative_pack"],
       "pro", competition_cluster="video_gen"),

    _p("otter_ai_co", "Otter.ai", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "Meeting transcription AI",
       "Real-time meeting notes",
       "Meeting Intelligence Agent", [],
       "pro", competition_cluster="stt"),

    _p("descript_co", "Descript", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "AI audio/video editing",
       "Text-based media editing",
       "Media Editor Agent", ["creative_pack"],
       "pro", competition_cluster="video_gen"),

    _p("canva_ai_co", "Canva AI", PRICING_FREEMIUM, "vision_speech_media", _CR,
       "Design AI tools",
       "Easy content creation for everyone",
       "Graphic Design Agent", ["creative_pack"],
       "free", competition_cluster="design_tools"),

    # ── Data & Search ─────────────────────────────────────────────────────
    _p("pinecone_co", "Pinecone", PRICING_FREEMIUM, "data_search", _INF,
       "Vector database",
       "RAG systems and semantic search",
       "Retrieval Augmentation Agent", ["data_analytics_pack"],
       "pro", embedding_ready=True, competition_cluster="vector_db"),

    _p("weaviate_co", "Weaviate", PRICING_OPEN_SOURCE, "data_search", _INF,
       "Open-source vector DB",
       "Semantic search infrastructure",
       "Vector Search Agent", ["data_analytics_pack"],
       "free", open_source=True, embedding_ready=True, competition_cluster="vector_db"),

    _p("redis_ai", "Redis AI", PRICING_FREEMIUM, "data_search", _INF,
       "In-memory AI data store",
       "Fast inference pipelines",
       "Real-Time Processing Agent", ["infrastructure_pack"],
       "pro", embedding_ready=True, competition_cluster="vector_db"),

    _p("elastic_ai_co", "Elastic AI", PRICING_FREEMIUM, "data_search", _INF,
       "Search + ML integration",
       "Enterprise search at scale",
       "Enterprise Search Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="search"),

    _p("glean", "Glean", PRICING_PAID, "data_search", _INF,
       "AI-powered search within org data",
       "Enterprise knowledge retrieval",
       "Enterprise Search Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="search"),

    _p("hebbia", "Hebbia", PRICING_PAID, "data_search", _INF,
       "Search for complex data",
       "Enterprise NLP-powered search",
       "Enterprise NLP Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="search"),

    _p("thoughtspot", "ThoughtSpot", PRICING_PAID, "data_search", _INF,
       "AI-driven analytics search",
       "Natural language BI queries",
       "BI Search Agent", ["data_analytics_pack"],
       "pro", competition_cluster="bi"),

    _p("zeta_alpha", "Zeta Alpha", PRICING_PAID, "data_search", _INF,
       "AI research search engine",
       "Academic and research search",
       "AI Research Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="search"),

    _p("snowflake_ai_co", "Snowflake Cortex AI", PRICING_PAID, "data_search", _INF,
       "Data cloud AI",
       "Data warehousing + ML integration",
       "Data Warehouse Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="data_platforms"),

    _p("cloudera_ai", "Cloudera AI", PRICING_ENTERPRISE, "data_search", _INF,
       "Big data AI",
       "Enterprise ML pipelines",
       "Big Data Agent", ["data_analytics_pack"],
       "enterprise", competition_cluster="data_platforms"),

    _p("vannevar_labs", "Vannevar Labs", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Intelligence & analytics AI",
       "Defense and security analytics",
       "Security & Defense Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    # ── Security & Compliance ─────────────────────────────────────────────
    _p("darktrace_co", "Darktrace", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Cybersecurity AI",
       "Self-learning threat detection",
       "Cyber Threat Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    _p("crowdstrike_co", "CrowdStrike AI", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Endpoint AI security",
       "Real-time cyber defense",
       "Endpoint Security Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    _p("sentinelone_co", "SentinelOne AI", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Autonomous threat response",
       "AI-driven cybersecurity defense",
       "Autonomous Defense Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    _p("snyk_ai", "Snyk AI", PRICING_FREEMIUM, "security_compliance", _IND,
       "DevSecOps AI",
       "Code vulnerability detection",
       "Code Security Agent", ["developer_pack", "security_pack"],
       "pro", competition_cluster="security"),

    _p("vectra_ai_co", "Vectra AI", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Network threat detection",
       "Cyber anomaly detection",
       "Network Defense Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    _p("cybereason", "Cybereason", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Endpoint threat hunting",
       "Incident response AI",
       "Threat Response Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    _p("arctic_wolf", "Arctic Wolf", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Managed detection AI",
       "Security operations center",
       "SOC Automation Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    _p("abnormal_security", "Abnormal Security", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Email security AI",
       "Phishing & BEC detection",
       "Email Security Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    _p("tessian", "Tessian", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Human layer security",
       "Preventing data loss via email",
       "Data Loss Prevention Agent", ["security_pack"],
       "enterprise", competition_cluster="security"),

    _p("anduril_co", "Anduril Industries", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Defense AI systems",
       "Autonomous defense platforms",
       "Tactical Systems Agent", ["security_pack"],
       "enterprise", competition_cluster="defense"),

    _p("shield_ai_co", "Shield AI", PRICING_ENTERPRISE, "security_compliance", _IND,
       "Military AI pilots",
       "Autonomous aircraft systems",
       "Autonomous Aviation Agent", ["security_pack"],
       "enterprise", competition_cluster="defense"),

    _p("anthropic_safety", "Anthropic Constitutional AI", PRICING_ENTERPRISE,
       "security_compliance", _IND,
       "Safe model training methodology",
       "AI alignment frameworks",
       "AI Ethics Agent", ["security_pack"],
       "enterprise", competition_cluster="ai_safety"),

    # ── Robotics & Physical AI ────────────────────────────────────────────
    _p("boston_dynamics_ai", "Boston Dynamics", PRICING_ENTERPRISE, "robotics_physical_ai", _PH,
       "Robotics & autonomous movement",
       "Industrial & humanoid robotics",
       "Physical Robotics Agent", ["robotics_pack"],
       "enterprise", api_access=False, competition_cluster="robotics"),

    _p("figure_ai_co", "Figure AI", PRICING_ENTERPRISE, "robotics_physical_ai", _PH,
       "Humanoid robotics",
       "AI-powered general-purpose robots",
       "Humanoid Systems Agent", ["robotics_pack"],
       "enterprise", api_access=False, competition_cluster="robotics"),

    _p("sanctuary_ai", "Sanctuary AI", PRICING_ENTERPRISE, "robotics_physical_ai", _PH,
       "General intelligence robotics",
       "Cognitive robotics systems",
       "Embodied Intelligence Agent", ["robotics_pack"],
       "enterprise", api_access=False, competition_cluster="robotics"),

    _p("covariant_ai", "Covariant", PRICING_ENTERPRISE, "robotics_physical_ai", _PH,
       "AI for warehouse robotics",
       "Robotic picking systems",
       "Logistics Automation Agent", ["robotics_pack"],
       "enterprise", competition_cluster="robotics"),

    _p("nuro", "Nuro", PRICING_ENTERPRISE, "robotics_physical_ai", _PH,
       "Autonomous delivery vehicles",
       "Self-driving logistics",
       "Autonomous Transport Agent", ["robotics_pack"],
       "enterprise", competition_cluster="autonomous_vehicles"),

    _p("wayve", "Wayve", PRICING_ENTERPRISE, "robotics_physical_ai", _PH,
       "Autonomous driving AI",
       "Vision-first driving models",
       "Self-Driving Intelligence Agent", ["robotics_pack"],
       "enterprise", competition_cluster="autonomous_vehicles"),

    _p("cruise_av", "Cruise", PRICING_ENTERPRISE, "robotics_physical_ai", _PH,
       "Robotaxi systems",
       "Urban autonomous mobility",
       "Urban Mobility Agent", ["robotics_pack"],
       "enterprise", competition_cluster="autonomous_vehicles"),

    _p("aurora_innov", "Aurora Innovation", PRICING_ENTERPRISE, "robotics_physical_ai", _PH,
       "Autonomous trucking AI",
       "Freight autonomy systems",
       "Freight Autonomy Agent", ["robotics_pack"],
       "enterprise", competition_cluster="autonomous_vehicles"),

    _p("skydio_ai", "Skydio", PRICING_PAID, "robotics_physical_ai", _PH,
       "AI drone navigation",
       "Autonomous drones",
       "Drone Intelligence Agent", ["robotics_pack"],
       "pro", competition_cluster="drones"),

    # ── Healthcare & Bio ──────────────────────────────────────────────────
    _p("abridge_ai", "Abridge AI", PRICING_PAID, "healthcare_bio", _IND,
       "Clinical summarization for doctors",
       "Medical note automation",
       "Healthcare Assistant Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="healthtech"),

    _p("tempus_ai_co", "Tempus", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "Precision medicine AI",
       "Clinical data analytics",
       "Medical Intelligence Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="healthtech"),

    _p("path_ai", "PathAI", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "AI pathology",
       "Diagnostic imaging analysis",
       "Medical Imaging Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="healthtech"),

    _p("insilico_medicine", "Insilico Medicine", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "Drug discovery AI",
       "AI-designed pharmaceuticals",
       "Drug Discovery Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="drug_discovery"),

    _p("benevolentai", "BenevolentAI", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "Biomedical research AI",
       "Target identification for drugs",
       "BioResearch Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="drug_discovery"),

    _p("aidoc", "Aidoc", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "Radiology AI",
       "Real-time scan detection",
       "Radiology Assistant Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="healthtech"),

    _p("olive_ai", "Olive AI", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "Healthcare workflow automation",
       "Hospital admin automation",
       "Health Ops Automation Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="healthtech"),

    _p("recursion_pharma", "Recursion Pharmaceuticals", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "AI drug modeling",
       "Biological simulation",
       "Molecular Modeling Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="drug_discovery"),

    _p("atomwise", "Atomwise", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "Structure-based drug discovery",
       "AI molecular screening",
       "Chemical Screening Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="drug_discovery"),

    _p("owkin", "Owkin", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "Federated learning healthcare",
       "Privacy-preserving medical AI",
       "Federated Medical Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="healthtech"),

    _p("viz_ai_co", "Viz.ai", PRICING_ENTERPRISE, "healthcare_bio", _IND,
       "Medical imaging AI",
       "Stroke detection & triage",
       "Emergency Triage Agent", ["healthcare_ai_pack"],
       "enterprise", competition_cluster="healthtech"),

    # ── FinTech & Risk ────────────────────────────────────────────────────
    _p("kasisto_ai", "Kasisto", PRICING_ENTERPRISE, "fintech_risk", _IND,
       "Conversational finance AI",
       "Banking assistant chatbots",
       "Financial Assistant Agent", ["finance_ai_pack"],
       "enterprise", competition_cluster="fintech"),

    _p("zest_ai", "Zest AI", PRICING_ENTERPRISE, "fintech_risk", _IND,
       "AI credit scoring",
       "Fair lending risk models",
       "Credit Risk Agent", ["finance_ai_pack"],
       "enterprise", competition_cluster="fintech"),

    _p("upstart_ai", "Upstart", PRICING_PAID, "fintech_risk", _IND,
       "AI lending platform",
       "Risk-based loan approvals",
       "Loan Decision Agent", ["finance_ai_pack"],
       "pro", competition_cluster="fintech"),

    _p("tractable_ai", "Tractable AI", PRICING_ENTERPRISE, "fintech_risk", _IND,
       "Visual AI for insurance",
       "Auto damage assessment",
       "Insurance Assessment Agent", ["finance_ai_pack"],
       "enterprise", competition_cluster="fintech"),

    _p("lemonade_ai_co", "Lemonade AI", PRICING_PAID, "fintech_risk", _IND,
       "AI-native insurance",
       "Instant claims processing",
       "Claims Processing Agent", ["finance_ai_pack"],
       "pro", competition_cluster="fintech"),

    _p("bloomberg_ai_co", "Bloomberg AI", PRICING_ENTERPRISE, "fintech_risk", _IND,
       "Financial AI & analytics",
       "Market intelligence and data",
       "Market Intelligence Agent", ["finance_ai_pack"],
       "enterprise", competition_cluster="fintech"),

    _p("two_sigma_ai", "Two Sigma AI", PRICING_ENTERPRISE, "fintech_risk", _IND,
       "Quantitative AI trading",
       "Algorithmic trading models",
       "Quant Trading Agent", ["finance_ai_pack"],
       "enterprise", competition_cluster="fintech"),

    _p("kensho_ai_co", "Kensho Technologies", PRICING_ENTERPRISE, "fintech_risk", _IND,
       "Financial analytics AI",
       "Market event analysis",
       "Financial Research Agent", ["finance_ai_pack"],
       "enterprise", competition_cluster="fintech"),

    _p("stripe_ai_co", "Stripe AI", PRICING_PAID, "fintech_risk", _IND,
       "Payment fraud detection AI",
       "Financial transaction intelligence",
       "Payment Intelligence Agent", ["finance_ai_pack"],
       "pro", competition_cluster="fintech"),

    _p("plaid_ai", "Plaid AI", PRICING_PAID, "fintech_risk", _IND,
       "Financial data connectivity",
       "Bank account intelligence",
       "Financial Data Agent", ["finance_ai_pack"],
       "pro", competition_cluster="fintech"),

    # ── Legal & Contracts ─────────────────────────────────────────────────
    _p("harvey_ai_co", "Harvey AI", PRICING_PAID, "legal_contracts", _IND,
       "Legal AI workflows",
       "Legal document analysis and workflows",
       "Legal AI Compliance Agent", ["legal_ai_pack"],
       "enterprise", competition_cluster="legaltech"),

    _p("luminance_ai", "Luminance", PRICING_PAID, "legal_contracts", _IND,
       "Contract review AI",
       "Automated contract analysis",
       "Contracts & Compliance Agent", ["legal_ai_pack"],
       "enterprise", competition_cluster="legaltech"),

    _p("ironclad_ai", "Ironclad", PRICING_ENTERPRISE, "legal_contracts", _IND,
       "Contract lifecycle AI",
       "Legal workflow automation",
       "Contract Lifecycle Agent", ["legal_ai_pack"],
       "enterprise", competition_cluster="legaltech"),

    _p("evisort", "Evisort", PRICING_ENTERPRISE, "legal_contracts", _IND,
       "Contract analysis AI",
       "Legal document intelligence",
       "Legal Document Agent", ["legal_ai_pack"],
       "enterprise", competition_cluster="legaltech"),

    _p("relativity_ai_co", "Relativity AI", PRICING_ENTERPRISE, "legal_contracts", _IND,
       "E-discovery AI",
       "Legal data search and analysis",
       "Litigation Intelligence Agent", ["legal_ai_pack"],
       "enterprise", competition_cluster="legaltech"),

    _p("everlaw", "Everlaw", PRICING_ENTERPRISE, "legal_contracts", _IND,
       "Litigation analytics",
       "Court case data processing",
       "Case Analytics Agent", ["legal_ai_pack"],
       "enterprise", competition_cluster="legaltech"),

    _p("docusign_ai_co", "DocuSign AI", PRICING_PAID, "legal_contracts", _IND,
       "eSignature AI",
       "Intelligent agreement management",
       "Agreement Agent", ["legal_ai_pack"],
       "pro", competition_cluster="legaltech"),

    _p("legalzoom_ai", "LegalZoom AI", PRICING_PAID, "legal_contracts", _IND,
       "Legal document automation",
       "Small business legal services",
       "Small Business Legal Agent", ["legal_ai_pack"],
       "pro", competition_cluster="legaltech"),

    _p("clio_ai", "Clio AI", PRICING_PAID, "legal_contracts", _IND,
       "Law practice management AI",
       "Legal firm operations",
       "Practice Management Agent", ["legal_ai_pack"],
       "enterprise", competition_cluster="legaltech"),

    # ── Education & Training ──────────────────────────────────────────────
    _p("speak_ai_co", "Speak AI", PRICING_PAID, "education_training", _IND,
       "AI language tutor",
       "Language learning automation",
       "Education & Tutoring Agent", ["education_pack"],
       "pro", competition_cluster="edtech"),

    _p("coursera_ai_co", "Coursera AI", PRICING_FREEMIUM, "education_training", _IND,
       "AI-powered education",
       "Personalized learning paths",
       "Learning Optimization Agent", ["education_pack"],
       "pro", competition_cluster="edtech"),

    _p("duolingo_ai_co", "Duolingo AI", PRICING_FREEMIUM, "education_training", _IND,
       "Adaptive language learning",
       "Gamified AI tutoring",
       "Language Tutor Agent", ["education_pack"],
       "free", competition_cluster="edtech"),

    _p("khan_academy_ai", "Khan Academy AI", PRICING_FREE, "education_training", _IND,
       "AI teaching assistants",
       "Student tutoring at scale",
       "Academic Tutor Agent", ["education_pack"],
       "free", competition_cluster="edtech"),

    _p("udacity_ai", "Udacity AI", PRICING_PAID, "education_training", _IND,
       "Career-based AI education",
       "Tech skill training programs",
       "Career Skill Agent", ["education_pack"],
       "pro", competition_cluster="edtech"),

    # ── Sales & Marketing ─────────────────────────────────────────────────
    _p("writer_ai", "Writer", PRICING_PAID, "sales_marketing", _EL,
       "Automated writing for business",
       "Enterprise content generation",
       "Content Generation Agent", ["sales_marketing_pack"],
       "enterprise", competition_cluster="content_ai"),

    _p("grammarly_co", "Grammarly", PRICING_FREEMIUM, "sales_marketing", _EL,
       "AI writing enhancement",
       "Grammar, tone, and style",
       "Writing Enhancement Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="content_ai"),

    _p("jasper_ai_co", "Jasper AI", PRICING_PAID, "sales_marketing", _EL,
       "Marketing copy AI",
       "Brand content generation",
       "Marketing Automation Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="content_ai"),

    _p("clay_ai", "Clay AI", PRICING_PAID, "sales_marketing", _EL,
       "Sales/marketing automation AI",
       "Lead enrichment and outreach",
       "Sales Intelligence Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="sales_ai"),

    _p("gong_io", "Gong.io", PRICING_ENTERPRISE, "sales_marketing", _EL,
       "AI sales intelligence",
       "Sales call analysis",
       "Sales Performance Agent", ["sales_marketing_pack"],
       "enterprise", competition_cluster="sales_ai"),

    _p("chorus_ai", "Chorus.ai", PRICING_ENTERPRISE, "sales_marketing", _EL,
       "Conversation analytics",
       "Revenue intelligence from calls",
       "Revenue Optimization Agent", ["sales_marketing_pack"],
       "enterprise", competition_cluster="sales_ai"),

    _p("drift_ai", "Drift AI", PRICING_PAID, "sales_marketing", _EL,
       "Conversational marketing bots",
       "Lead capture automation",
       "Lead Generation Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="sales_ai"),

    _p("sprinklr_ai", "Sprinklr AI", PRICING_ENTERPRISE, "sales_marketing", _EL,
       "Social media intelligence",
       "Brand analytics & monitoring",
       "Brand Intelligence Agent", ["sales_marketing_pack"],
       "enterprise", competition_cluster="marketing_ai"),

    _p("hootsuite_ai_co", "Hootsuite AI", PRICING_FREEMIUM, "sales_marketing", _EL,
       "Social media automation",
       "Content scheduling + AI insights",
       "Social Automation Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="marketing_ai"),

    _p("tome_ai", "Tome AI", PRICING_FREEMIUM, "sales_marketing", _EL,
       "AI presentation builder",
       "Automated slide creation",
       "Presentation Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="content_ai"),

    _p("copy_ai_co", "Copy.ai", PRICING_FREEMIUM, "sales_marketing", _EL,
       "AI copywriting",
       "Marketing content generation",
       "Copywriting Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="content_ai"),

    _p("lavender_ai", "Lavender AI", PRICING_PAID, "sales_marketing", _EL,
       "Email coaching AI",
       "Sales email optimization",
       "Email Optimization Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="sales_ai"),

    _p("apollo_io_ai", "Apollo.io AI", PRICING_FREEMIUM, "sales_marketing", _EL,
       "Sales intelligence platform",
       "Lead database & outreach",
       "Lead Database Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="sales_ai"),

    _p("zoominfo_ai", "ZoomInfo AI", PRICING_ENTERPRISE, "sales_marketing", _EL,
       "B2B data intelligence",
       "Contact & company data",
       "B2B Intelligence Agent", ["sales_marketing_pack"],
       "enterprise", competition_cluster="sales_ai"),

    _p("clearbit_ai", "Clearbit AI", PRICING_PAID, "sales_marketing", _EL,
       "Data enrichment",
       "Real-time lead enrichment",
       "Data Enrichment Agent", ["sales_marketing_pack"],
       "pro", competition_cluster="sales_ai"),

    # ── Gaming & Simulation ───────────────────────────────────────────────
    _p("unity_ai", "Unity AI", PRICING_FREEMIUM, "gaming_simulation", _CR,
       "AI for gaming engines",
       "Intelligent NPC behavior",
       "Game AI Agent", ["gaming_pack"],
       "pro", competition_cluster="gaming"),

    _p("inworld_ai_co", "Inworld AI", PRICING_FREEMIUM, "gaming_simulation", _CR,
       "AI characters for games",
       "Interactive NPC personalities",
       "NPC Personality Agent", ["gaming_pack"],
       "pro", competition_cluster="gaming"),

    _p("roblox_ai", "Roblox AI", PRICING_FREEMIUM, "gaming_simulation", _CR,
       "User-generated AI gaming tools",
       "AI creation tools for players",
       "Creator Gaming Agent", ["gaming_pack"],
       "free", competition_cluster="gaming"),

    _p("epic_games_ai", "Epic Games AI", PRICING_FREEMIUM, "gaming_simulation", _CR,
       "Unreal Engine AI tools",
       "Simulation & 3D AI rendering",
       "Simulation Intelligence Agent", ["gaming_pack"],
       "pro", competition_cluster="gaming"),

    _p("niantic_ai", "Niantic AI", PRICING_PAID, "gaming_simulation", _CR,
       "AR world mapping",
       "Spatial computing & AR",
       "Spatial Intelligence Agent", ["gaming_pack"],
       "enterprise", competition_cluster="ar"),

    _p("magic_leap_ai", "Magic Leap AI", PRICING_ENTERPRISE, "gaming_simulation", _CR,
       "AR hardware + AI",
       "Mixed reality enterprise",
       "Mixed Reality Agent", ["gaming_pack"],
       "enterprise", competition_cluster="ar"),

    # ── Web3 & Blockchain ─────────────────────────────────────────────────
    _p("opensea_ai", "OpenSea AI", PRICING_FREEMIUM, "web3_blockchain", _IND,
       "NFT analytics AI",
       "Digital asset prediction",
       "Digital Asset Agent", ["web3_pack"],
       "pro", competition_cluster="web3"),

    _p("chainalysis", "Chainalysis", PRICING_ENTERPRISE, "web3_blockchain", _IND,
       "Blockchain analytics AI",
       "Crypto compliance & tracing",
       "Blockchain Compliance Agent", ["web3_pack", "security_pack"],
       "enterprise", competition_cluster="web3"),

    _p("fireblocks_ai", "Fireblocks AI", PRICING_ENTERPRISE, "web3_blockchain", _IND,
       "Crypto custody automation",
       "Secure digital asset transfers",
       "Crypto Security Agent", ["web3_pack"],
       "enterprise", competition_cluster="web3"),

    # ── HR & Workforce ────────────────────────────────────────────────────
    _p("deel_ai", "Deel AI", PRICING_PAID, "hr_workforce", _IND,
       "Global HR automation",
       "International payroll intelligence",
       "Workforce Automation Agent", ["hr_pack"],
       "enterprise", competition_cluster="hrtech"),

    _p("rippling_ai", "Rippling AI", PRICING_PAID, "hr_workforce", _IND,
       "Workforce management AI",
       "HR data automation",
       "HR Data Agent", ["hr_pack"],
       "enterprise", competition_cluster="hrtech"),

    _p("workday_ai_co", "Workday AI", PRICING_ENTERPRISE, "hr_workforce", _IND,
       "Enterprise HR analytics",
       "Workforce planning at scale",
       "Workforce Planning Agent", ["hr_pack"],
       "enterprise", competition_cluster="hrtech"),

    _p("gusto_ai", "Gusto AI", PRICING_PAID, "hr_workforce", _IND,
       "Payroll & HR AI",
       "Small business payroll automation",
       "Payroll Agent", ["hr_pack"],
       "pro", competition_cluster="hrtech"),

    _p("bamboohr_ai", "BambooHR AI", PRICING_PAID, "hr_workforce", _IND,
       "HR management platform",
       "Employee data management",
       "Employee Data Agent", ["hr_pack"],
       "pro", competition_cluster="hrtech"),

    _p("lattice_ai_co", "Lattice AI", PRICING_PAID, "hr_workforce", _IND,
       "Performance management AI",
       "Employee performance analytics",
       "Performance Analytics Agent", ["hr_pack"],
       "enterprise", competition_cluster="hrtech"),
]

# Fast lookup by id
PROVIDER_CATALOG_BY_ID: dict[str, AIProviderObject] = {p.id: p for p in PROVIDER_CATALOG}

__all__ = ["PROVIDER_CATALOG", "PROVIDER_CATALOG_BY_ID"]
